/* Generated by tools/generate_target_abi.py. */
#ifndef R_RUNTIME_TARGET_ABI_H
#define R_RUNTIME_TARGET_ABI_H

#include <float.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>
#include <wchar.h>

#define R_RUNTIME_TARGET_MANIFEST_SHA256 "27d7f8e8c06893f2a4f10651fc0df9ea58ba8b95ea0db2decc7b73509f444b0e"
#define R_RUNTIME_TARGET_MANIFEST_SHA256_BYTES \
    { \
        UINT8_C(0x27), UINT8_C(0xd7), UINT8_C(0xf8), UINT8_C(0xe8), UINT8_C(0xc0), UINT8_C(0x68), UINT8_C(0x93), UINT8_C(0xf2), \
        UINT8_C(0xa4), UINT8_C(0xf1), UINT8_C(0x06), UINT8_C(0x51), UINT8_C(0xfc), UINT8_C(0x0d), UINT8_C(0xf9), UINT8_C(0xea), \
        UINT8_C(0x58), UINT8_C(0xba), UINT8_C(0x8b), UINT8_C(0x95), UINT8_C(0xea), UINT8_C(0x0d), UINT8_C(0xb2), UINT8_C(0xde), \
        UINT8_C(0xcc), UINT8_C(0x7b), UINT8_C(0x73), UINT8_C(0x50), UINT8_C(0x9f), UINT8_C(0x44), UINT8_C(0x4b), UINT8_C(0x0e) \
    }

_Static_assert(SIZE_MAX >= UINT64_C(2305843009213693951),
               "target manifest maximum object size is not representable");
#define R_RUNTIME_TARGET_MAXIMUM_OBJECT_SIZE \
    ((size_t)UINT64_C(2305843009213693951))

#define R_RUNTIME_STACK_PROTECTED_LOW_BYTES \
    ((size_t)65536)
#define R_RUNTIME_STACK_CALL_TRANSITION_BYTES \
    ((size_t)16384)
#define R_RUNTIME_GENERATED_FRAME_MAX_BYTES \
    ((size_t)262144)

_Static_assert(CHAR_BIT == 8,
               "target manifest byte width mismatch");
_Static_assert(sizeof(size_t) * CHAR_BIT == 64U,
               "target manifest usize width mismatch");
_Static_assert(sizeof(ptrdiff_t) * CHAR_BIT == 64U,
               "target manifest isize width mismatch");
_Static_assert(FLT_EVAL_METHOD == 0,
               "target manifest floating evaluation method mismatch");

_Static_assert(sizeof(char) == 1U && _Alignof(char) == 1U,
               "target manifest c_char layout mismatch");
_Static_assert(CHAR_MIN == INT64_C(-128) && CHAR_MAX == INT64_C(127),
               "target manifest c_char range mismatch");

_Static_assert(sizeof(signed char) == 1U && _Alignof(signed char) == 1U,
               "target manifest c_schar layout mismatch");
_Static_assert(SCHAR_MIN == INT64_C(-128) && SCHAR_MAX == INT64_C(127),
               "target manifest c_schar range mismatch");

_Static_assert(sizeof(unsigned char) == 1U && _Alignof(unsigned char) == 1U,
               "target manifest c_uchar layout mismatch");
_Static_assert(UCHAR_MAX == UINT64_C(255),
               "target manifest c_uchar range mismatch");

_Static_assert(sizeof(short) == 2U && _Alignof(short) == 2U,
               "target manifest c_short layout mismatch");
_Static_assert(SHRT_MIN == INT64_C(-32768) && SHRT_MAX == INT64_C(32767),
               "target manifest c_short range mismatch");

_Static_assert(sizeof(unsigned short) == 2U && _Alignof(unsigned short) == 2U,
               "target manifest c_ushort layout mismatch");
_Static_assert(USHRT_MAX == UINT64_C(65535),
               "target manifest c_ushort range mismatch");

_Static_assert(sizeof(int) == 4U && _Alignof(int) == 4U,
               "target manifest c_int layout mismatch");
_Static_assert(INT_MIN == INT64_C(-2147483648) && INT_MAX == INT64_C(2147483647),
               "target manifest c_int range mismatch");

_Static_assert(sizeof(unsigned int) == 4U && _Alignof(unsigned int) == 4U,
               "target manifest c_uint layout mismatch");
_Static_assert(UINT_MAX == UINT64_C(4294967295),
               "target manifest c_uint range mismatch");

_Static_assert(sizeof(long) == 8U && _Alignof(long) == 8U,
               "target manifest c_long layout mismatch");
_Static_assert(LONG_MIN == (-INT64_C(9223372036854775807) - INT64_C(1)) && LONG_MAX == INT64_C(9223372036854775807),
               "target manifest c_long range mismatch");

_Static_assert(sizeof(unsigned long) == 8U && _Alignof(unsigned long) == 8U,
               "target manifest c_ulong layout mismatch");
_Static_assert(ULONG_MAX == UINT64_C(18446744073709551615),
               "target manifest c_ulong range mismatch");

_Static_assert(sizeof(long long) == 8U && _Alignof(long long) == 8U,
               "target manifest c_llong layout mismatch");
_Static_assert(LLONG_MIN == (-INT64_C(9223372036854775807) - INT64_C(1)) && LLONG_MAX == INT64_C(9223372036854775807),
               "target manifest c_llong range mismatch");

_Static_assert(sizeof(unsigned long long) == 8U && _Alignof(unsigned long long) == 8U,
               "target manifest c_ullong layout mismatch");
_Static_assert(ULLONG_MAX == UINT64_C(18446744073709551615),
               "target manifest c_ullong range mismatch");

_Static_assert(sizeof(_Bool) == 1U && _Alignof(_Bool) == 1U,
               "target manifest c_bool layout mismatch");
_Static_assert((_Bool)0 == 0 && (_Bool)1 == 1 && (_Bool)2 == 1,
               "target manifest c_bool representation mismatch");

_Static_assert(sizeof(wchar_t) == 4U && _Alignof(wchar_t) == 4U,
               "target manifest c_wchar layout mismatch");
_Static_assert(WCHAR_MIN == INT64_C(-2147483648) && WCHAR_MAX == INT64_C(2147483647),
               "target manifest c_wchar range mismatch");

_Static_assert(sizeof(wint_t) == 4U && _Alignof(wint_t) == 4U,
               "target manifest c_wint layout mismatch");
_Static_assert(WINT_MIN == INT64_C(-2147483648) && WINT_MAX == INT64_C(2147483647),
               "target manifest c_wint range mismatch");

_Static_assert(sizeof(int8_t) == 1U && _Alignof(int8_t) == 1U,
               "target manifest c_int8 layout mismatch");
_Static_assert(INT8_MIN == INT64_C(-128) && INT8_MAX == INT64_C(127),
               "target manifest c_int8 range mismatch");

_Static_assert(sizeof(uint8_t) == 1U && _Alignof(uint8_t) == 1U,
               "target manifest c_uint8 layout mismatch");
_Static_assert(UINT8_MAX == UINT64_C(255),
               "target manifest c_uint8 range mismatch");

_Static_assert(sizeof(int16_t) == 2U && _Alignof(int16_t) == 2U,
               "target manifest c_int16 layout mismatch");
_Static_assert(INT16_MIN == INT64_C(-32768) && INT16_MAX == INT64_C(32767),
               "target manifest c_int16 range mismatch");

_Static_assert(sizeof(uint16_t) == 2U && _Alignof(uint16_t) == 2U,
               "target manifest c_uint16 layout mismatch");
_Static_assert(UINT16_MAX == UINT64_C(65535),
               "target manifest c_uint16 range mismatch");

_Static_assert(sizeof(int32_t) == 4U && _Alignof(int32_t) == 4U,
               "target manifest c_int32 layout mismatch");
_Static_assert(INT32_MIN == INT64_C(-2147483648) && INT32_MAX == INT64_C(2147483647),
               "target manifest c_int32 range mismatch");

_Static_assert(sizeof(uint32_t) == 4U && _Alignof(uint32_t) == 4U,
               "target manifest c_uint32 layout mismatch");
_Static_assert(UINT32_MAX == UINT64_C(4294967295),
               "target manifest c_uint32 range mismatch");

_Static_assert(sizeof(int64_t) == 8U && _Alignof(int64_t) == 8U,
               "target manifest c_int64 layout mismatch");
_Static_assert(INT64_MIN == (-INT64_C(9223372036854775807) - INT64_C(1)) && INT64_MAX == INT64_C(9223372036854775807),
               "target manifest c_int64 range mismatch");

_Static_assert(sizeof(uint64_t) == 8U && _Alignof(uint64_t) == 8U,
               "target manifest c_uint64 layout mismatch");
_Static_assert(UINT64_MAX == UINT64_C(18446744073709551615),
               "target manifest c_uint64 range mismatch");

_Static_assert(sizeof(intptr_t) == 8U && _Alignof(intptr_t) == 8U,
               "target manifest c_intptr layout mismatch");
_Static_assert(INTPTR_MIN == (-INT64_C(9223372036854775807) - INT64_C(1)) && INTPTR_MAX == INT64_C(9223372036854775807),
               "target manifest c_intptr range mismatch");

_Static_assert(sizeof(uintptr_t) == 8U && _Alignof(uintptr_t) == 8U,
               "target manifest c_uintptr layout mismatch");
_Static_assert(UINTPTR_MAX == UINT64_C(18446744073709551615),
               "target manifest c_uintptr range mismatch");

_Static_assert(sizeof(intmax_t) == 8U && _Alignof(intmax_t) == 8U,
               "target manifest c_intmax layout mismatch");
_Static_assert(INTMAX_MIN == (-INT64_C(9223372036854775807) - INT64_C(1)) && INTMAX_MAX == INT64_C(9223372036854775807),
               "target manifest c_intmax range mismatch");

_Static_assert(sizeof(uintmax_t) == 8U && _Alignof(uintmax_t) == 8U,
               "target manifest c_uintmax layout mismatch");
_Static_assert(UINTMAX_MAX == UINT64_C(18446744073709551615),
               "target manifest c_uintmax range mismatch");

_Static_assert(sizeof(float) == 4U && _Alignof(float) == 4U &&
                   FLT_RADIX == 2 && FLT_MANT_DIG == 24 &&
                   FLT_MIN_EXP == -125 &&
                   FLT_MAX_EXP == 128,
               "target manifest c_float representation mismatch");

_Static_assert(sizeof(double) == 8U && _Alignof(double) == 8U &&
                   FLT_RADIX == 2 && DBL_MANT_DIG == 53 &&
                   DBL_MIN_EXP == -1021 &&
                   DBL_MAX_EXP == 1024,
               "target manifest c_double representation mismatch");

_Static_assert(sizeof(long double) == 8U && _Alignof(long double) == 8U &&
                   FLT_RADIX == 2 && LDBL_MANT_DIG == 53 &&
                   LDBL_MIN_EXP == -1021 &&
                   LDBL_MAX_EXP == 1024,
               "target manifest c_long_double representation mismatch");

_Static_assert(sizeof(size_t) == 8U && _Alignof(size_t) == 8U,
               "target manifest c_size layout mismatch");
_Static_assert(SIZE_MAX == UINT64_C(18446744073709551615),
               "target manifest c_size range mismatch");

_Static_assert(sizeof(ptrdiff_t) == 8U && _Alignof(ptrdiff_t) == 8U,
               "target manifest c_ptrdiff layout mismatch");
_Static_assert(PTRDIFF_MIN == (-INT64_C(9223372036854775807) - INT64_C(1)) && PTRDIFF_MAX == INT64_C(9223372036854775807),
               "target manifest c_ptrdiff range mismatch");

#endif
