#include "frontend_internal.h"

static const RStandardErrorErasureDescriptor r_standard_error_erasures[] = {
    {"error",
     "from_address",
     "std.error::from_address",
     "std.net::address_error",
     "r_std_error_from_address",
     "r_std_error"},
    {"error",
     "from_alloc",
     "std.error::from_alloc",
     "std.alloc::alloc_error",
     "r_std_error_from_alloc",
     "r_std_error"},
    {"error",
     "from_async",
     "std.error::from_async",
     "std.async::start_error",
     "r_std_error_from_async",
     "r_std_error"},
    {"error",
     "from_barrier",
     "std.error::from_barrier",
     "std.sync::barrier_error",
     "r_std_error_from_barrier",
     "r_std_error"},
    {"error",
     "from_boundary",
     "std.error::from_boundary",
     "std.string::boundary_error",
     "r_std_error_from_boundary",
     "r_std_error"},
    {"error",
     "from_bytes",
     "std.error::from_bytes",
     "std.bytes::bytes_error",
     "r_std_error_from_bytes",
     "r_std_error"},
    {"error",
     "from_duration",
     "std.error::from_duration",
     "std.time::duration_error",
     "r_std_error_from_duration",
     "r_std_error"},
    {"error",
     "from_format",
     "std.error::from_format",
     "std.format::format_error",
     "r_std_error_from_format",
     "r_std_error"},
    {"error",
     "from_parse",
     "std.error::from_parse",
     "std.convert::parse_error",
     "r_std_error_from_parse",
     "r_std_error"},
    {"error",
     "from_path",
     "std.error::from_path",
     "std.fs::path_error",
     "r_std_error_from_path",
     "r_std_error"},
    {"error",
     "from_range",
     "std.error::from_range",
     "std.convert::range_error",
     "r_std_error_from_range",
     "r_std_error"},
    {"error",
     "from_string",
     "std.error::from_string",
     "std.string::string_error",
     "r_std_error_from_string",
     "r_std_error"},
    {"error",
     "from_thread",
     "std.error::from_thread",
     "std.thread::thread_error",
     "r_std_error_from_thread",
     "r_std_error"},
    {"c",
     "runtime_as_error",
     "std.c::runtime_as_error",
     "std.c::runtime_error",
     "r_std_c_runtime_as_error",
     "r_std_c"},
    {"c",
     "string_as_error",
     "std.c::string_as_error",
     "std.c::string_error",
     "r_std_c_string_as_error",
     "r_std_c"},
    {"env",
     "as_error",
     "std.env::as_error",
     "std.env::env_error",
     "r_std_env_as_error",
     "r_std_env"},
    {"net",
     "as_error",
     "std.net::as_error",
     "std.net::net_error",
     "r_std_net_as_error",
     "r_std_net"},
    {"process",
     "as_error",
     "std.process::as_error",
     "std.process::process_error",
     "r_std_process_as_error",
     "r_std_process"},
    /* R-SLIB-ERR-0004: generated inline from the mapping of the main boundary; no symbol. */
    {"error", "from_fault", "std.error::from_fault", "std.error::fault", NULL, "r_std_error"},
};

size_t r_standard_error_erasure_count(void) {
    return sizeof(r_standard_error_erasures) / sizeof(r_standard_error_erasures[0]);
}

const RStandardErrorErasureDescriptor *r_standard_error_erasure(uint64_t operation_id) {
    if ((operation_id == UINT64_C(0)) ||
        (operation_id > (uint64_t)r_standard_error_erasure_count())) {
        return NULL;
    }
    return &r_standard_error_erasures[(size_t)operation_id - 1U];
}
