#ifndef R_STANDARD_SCOPED_OPERATIONS_H
#define R_STANDARD_SCOPED_OPERATIONS_H

#include "frontend_internal.h"

/* A scoped standard operation (Library R-SLIB-ASYNC-0012) borrows a caller view for the
   lifetime of a task-group loan (Core R-STMT-0017). Arguments are the shared handle borrow,
   an optional by-value extra argument, the byte view and the deadline, in that order. The extra
   argument is a named standard type or u64. */
typedef struct RStandardScopedOperationDescriptor {
    RStandardCallOperation operation;
    const char *module;      /* "std.io", "std.fs" or "std.net" */
    const char *name;        /* unqualified operation name */
    const char *handle_type; /* named standard type behind the shared borrow */
    const char *extra_type;  /* by-value argument before the view, or NULL */
    bool exclusive_view;     /* u8[] when true, const u8[] otherwise */
    const char *result_type; /* "usize", "void" or a named standard type */
    const char *error_type;  /* the single checked completion error */
    const char *rule;
    const char *native_name; /* C start function */
    const char *c_deadline;  /* C deadline struct */
    const char *c_start;     /* C start result struct */
    const char *c_view;      /* C view struct with data/length members */
} RStandardScopedOperationDescriptor;

static inline const RStandardScopedOperationDescriptor *
r_standard_scoped_operation(RStandardCallOperation operation) {
    static const RStandardScopedOperationDescriptor descriptors[] = {
        {R_STANDARD_CALL_IO_READ_INTO,
         "std.io",
         "read_into",
         "std.io::input",
         NULL,
         true,
         "usize",
         "std.io::io_error",
         "R-SLIB-IO-0008",
         "r_std_io_read_into",
         "RStdIoDeadline",
         "RStdIoTaskStartResult",
         "RStdIoMutableBytes"},
        {R_STANDARD_CALL_IO_WRITE_FROM,
         "std.io",
         "write_from",
         "std.io::output",
         NULL,
         false,
         "usize",
         "std.io::io_error",
         "R-SLIB-IO-0008",
         "r_std_io_write_from",
         "RStdIoDeadline",
         "RStdIoTaskStartResult",
         "RStdIoConstBytes"},
        {R_STANDARD_CALL_IO_WRITE_ALL_FROM,
         "std.io",
         "write_all_from",
         "std.io::output",
         NULL,
         false,
         "void",
         "std.io::io_error",
         "R-SLIB-IO-0008",
         "r_std_io_write_all_from",
         "RStdIoDeadline",
         "RStdIoTaskStartResult",
         "RStdIoConstBytes"},
        {R_STANDARD_CALL_FS_READ_INTO,
         "std.fs",
         "read_into",
         "std.fs::file",
         NULL,
         true,
         "usize",
         "std.io::io_error",
         "R-SLIB-FS-0013",
         "r_std_fs_read_into",
         "RStdFsDeadline",
         "RStdFsTaskStartResult",
         "RStdFsMutableBytes"},
        {R_STANDARD_CALL_FS_WRITE_FROM,
         "std.fs",
         "write_from",
         "std.fs::file",
         NULL,
         false,
         "usize",
         "std.io::io_error",
         "R-SLIB-FS-0013",
         "r_std_fs_write_from",
         "RStdFsDeadline",
         "RStdFsTaskStartResult",
         "RStdFsConstBytes"},
        {R_STANDARD_CALL_FS_WRITE_ALL_FROM,
         "std.fs",
         "write_all_from",
         "std.fs::file",
         NULL,
         false,
         "void",
         "std.io::io_error",
         "R-SLIB-FS-0013",
         "r_std_fs_write_all_from",
         "RStdFsDeadline",
         "RStdFsTaskStartResult",
         "RStdFsConstBytes"},
        {R_STANDARD_CALL_FS_READ_AT_INTO,
         "std.fs",
         "read_at_into",
         "std.fs::file",
         "u64",
         true,
         "usize",
         "std.io::io_error",
         "R-SLIB-FS-0015",
         "r_std_fs_read_at_into",
         "RStdFsDeadline",
         "RStdFsTaskStartResult",
         "RStdFsMutableBytes"},
        {R_STANDARD_CALL_FS_WRITE_ALL_AT_FROM,
         "std.fs",
         "write_all_at_from",
         "std.fs::file",
         "u64",
         false,
         "void",
         "std.io::io_error",
         "R-SLIB-FS-0015",
         "r_std_fs_write_all_at_from",
         "RStdFsDeadline",
         "RStdFsTaskStartResult",
         "RStdFsConstBytes"},
        {R_STANDARD_CALL_NET_TCP_READ_INTO,
         "std.net",
         "tcp_read_into",
         "std.net::tcp_stream",
         NULL,
         true,
         "usize",
         "std.net::net_error",
         "R-SLIB-NET-0010",
         "r_std_net_tcp_read_into",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetMutableBytes"},
        {R_STANDARD_CALL_NET_TCP_WRITE_FROM,
         "std.net",
         "tcp_write_from",
         "std.net::tcp_stream",
         NULL,
         false,
         "usize",
         "std.net::net_error",
         "R-SLIB-NET-0010",
         "r_std_net_tcp_write_from",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetConstBytes"},
        {R_STANDARD_CALL_NET_TCP_WRITE_ALL_FROM,
         "std.net",
         "tcp_write_all_from",
         "std.net::tcp_stream",
         NULL,
         false,
         "void",
         "std.net::net_error",
         "R-SLIB-NET-0010",
         "r_std_net_tcp_write_all_from",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetConstBytes"},
        {R_STANDARD_CALL_NET_UDP_SEND_FROM,
         "std.net",
         "udp_send_from",
         "std.net::udp_socket",
         "std.net::socket_address",
         false,
         "void",
         "std.net::net_error",
         "R-SLIB-NET-0010",
         "r_std_net_udp_send_from",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetConstBytes"},
        {R_STANDARD_CALL_NET_UDP_RECEIVE_INTO,
         "std.net",
         "udp_receive_into",
         "std.net::udp_socket",
         NULL,
         true,
         "std.net::datagram",
         "std.net::net_error",
         "R-SLIB-NET-0010",
         "r_std_net_udp_receive_into",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetMutableBytes"},
        {R_STANDARD_CALL_NET_UNIX_READ_INTO,
         "std.net",
         "unix_read_into",
         "std.net::unix_stream",
         NULL,
         true,
         "usize",
         "std.net::net_error",
         "R-SLIB-NET-0015",
         "r_std_net_unix_read_into",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetMutableBytes"},
        {R_STANDARD_CALL_NET_UNIX_WRITE_FROM,
         "std.net",
         "unix_write_from",
         "std.net::unix_stream",
         NULL,
         false,
         "usize",
         "std.net::net_error",
         "R-SLIB-NET-0015",
         "r_std_net_unix_write_from",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetConstBytes"},
        {R_STANDARD_CALL_NET_UNIX_WRITE_ALL_FROM,
         "std.net",
         "unix_write_all_from",
         "std.net::unix_stream",
         NULL,
         false,
         "void",
         "std.net::net_error",
         "R-SLIB-NET-0015",
         "r_std_net_unix_write_all_from",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetConstBytes"},
        {R_STANDARD_CALL_NET_UNIX_SEND_FROM,
         "std.net",
         "unix_send_from",
         "std.net::unix_datagram",
         NULL,
         false,
         "void",
         "std.net::net_error",
         "R-SLIB-NET-0017",
         "r_std_net_unix_send_from",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetConstBytes"},
        {R_STANDARD_CALL_NET_UNIX_RECEIVE_INTO,
         "std.net",
         "unix_receive_into",
         "std.net::unix_datagram",
         NULL,
         true,
         "std.net::unix_message",
         "std.net::net_error",
         "R-SLIB-NET-0017",
         "r_std_net_unix_receive_into",
         "RStdNetDeadline",
         "RStdNetTaskStartResult",
         "RStdNetMutableBytes"},
    };
    size_t index;

    for (index = 0U; index < sizeof(descriptors) / sizeof(descriptors[0]); ++index) {
        if (descriptors[index].operation == operation) {
            return &descriptors[index];
        }
    }
    return NULL;
}

/* Argument positions: the view follows the optional extra argument; the deadline is last. */
static inline uint32_t
r_standard_scoped_view_index(const RStandardScopedOperationDescriptor *descriptor) {
    return descriptor->extra_type == NULL ? UINT32_C(1) : UINT32_C(2);
}

static inline uint32_t
r_standard_scoped_argument_count(const RStandardScopedOperationDescriptor *descriptor) {
    return r_standard_scoped_view_index(descriptor) + UINT32_C(2);
}

#endif
