#ifndef R_STANDARD_FS_ASYNC_H
#define R_STANDARD_FS_ASYNC_H

/* Compiler-only contracts for native filesystem task starts. */
typedef struct RStandardFsAsyncDescriptor {
    RStandardCallOperation operation;
    const char *name;
    const char *native_name;
    const char *result;
    bool throws_fs;
    uint32_t move_index;
    uint32_t argument_count;
    const char *arguments[5];
} RStandardFsAsyncDescriptor;

static inline const RStandardFsAsyncDescriptor *
r_standard_fs_async_descriptor(RStandardCallOperation operation) {
    static const RStandardFsAsyncDescriptor operations[] = {
        {R_STANDARD_CALL_FS_CLOSE_DIRECTORY,
         "close_directory",
         "r_std_fs_close_directory",
         "void",
         true,
         0U,
         2U,
         {"std.fs::directory", "deadline"}},
        {R_STANDARD_CALL_FS_CLOSE_FILE,
         "close_file",
         "r_std_fs_close_file",
         "void",
         true,
         0U,
         2U,
         {"std.fs::file", "deadline"}},
        {R_STANDARD_CALL_FS_CREATE_DIRECTORY,
         "create_directory",
         "r_std_fs_create_directory",
         "void",
         true,
         UINT32_MAX,
         3U,
         {"&std.fs::path", "bool", "deadline"}},
        {R_STANDARD_CALL_FS_FLUSH,
         "flush",
         "r_std_fs_flush",
         "void",
         true,
         UINT32_MAX,
         2U,
         {"&std.fs::file", "deadline"}},
        {R_STANDARD_CALL_FS_ITERATE,
         "iterate",
         "r_std_fs_iterate",
         "std.fs::directory_iter",
         true,
         UINT32_MAX,
         2U,
         {"&std.fs::directory", "deadline"}},
        {R_STANDARD_CALL_FS_METADATA,
         "metadata",
         "r_std_fs_metadata",
         "std.fs::metadata",
         true,
         UINT32_MAX,
         2U,
         {"&std.fs::path", "deadline"}},
        {R_STANDARD_CALL_FS_METADATA_BENEATH,
         "metadata_beneath",
         "r_std_fs_metadata_beneath",
         "std.fs::metadata",
         true,
         UINT32_MAX,
         3U,
         {"&std.fs::directory", "&std.fs::path", "deadline"}},
        {R_STANDARD_CALL_FS_NEXT,
         "next",
         "r_std_fs_next",
         "std.fs::directory_next_result",
         false,
         0U,
         2U,
         {"std.fs::directory_iter", "deadline"}},
        {R_STANDARD_CALL_FS_OPEN_DIRECTORY_BENEATH,
         "open_directory_beneath",
         "r_std_fs_open_directory_beneath",
         "std.fs::directory",
         true,
         UINT32_MAX,
         3U,
         {"&std.fs::directory", "&std.fs::path", "deadline"}},
        {R_STANDARD_CALL_FS_OPEN_FILE_BENEATH,
         "open_file_beneath",
         "r_std_fs_open_file_beneath",
         "std.fs::file",
         true,
         UINT32_MAX,
         4U,
         {"&std.fs::directory", "&std.fs::path", "std.fs::open_file_options", "deadline"}},
        {R_STANDARD_CALL_FS_READ,
         "read",
         "r_std_fs_read",
         "std.io::read_result",
         false,
         1U,
         3U,
         {"&std.fs::file", "bytes", "deadline"}},
        {R_STANDARD_CALL_FS_READ_FILE_BENEATH,
         "read_file_beneath",
         "r_std_fs_read_file_beneath",
         "bytes",
         true,
         UINT32_MAX,
         4U,
         {"&std.fs::directory", "&std.fs::path", "usize", "deadline"}},
        {R_STANDARD_CALL_FS_REMOVE_DIRECTORY_BENEATH,
         "remove_directory_beneath",
         "r_std_fs_remove_directory_beneath",
         "void",
         true,
         UINT32_MAX,
         3U,
         {"&std.fs::directory", "&std.fs::path", "deadline"}},
        {R_STANDARD_CALL_FS_REMOVE_FILE_BENEATH,
         "remove_file_beneath",
         "r_std_fs_remove_file_beneath",
         "void",
         true,
         UINT32_MAX,
         3U,
         {"&std.fs::directory", "&std.fs::path", "deadline"}},
        {R_STANDARD_CALL_FS_RENAME_BENEATH,
         "rename_beneath",
         "r_std_fs_rename_beneath",
         "void",
         true,
         UINT32_MAX,
         5U,
         {"&std.fs::directory",
          "&std.fs::path",
          "&std.fs::directory",
          "&std.fs::path",
          "deadline"}},
        {R_STANDARD_CALL_FS_SEEK,
         "seek",
         "r_std_fs_seek",
         "u64",
         true,
         UINT32_MAX,
         4U,
         {"&std.fs::file", "std.fs::seek_origin", "i64", "deadline"}},
        {R_STANDARD_CALL_FS_SYNC,
         "sync",
         "r_std_fs_sync",
         "void",
         true,
         UINT32_MAX,
         3U,
         {"&std.fs::file", "std.fs::sync_level", "deadline"}},
        {R_STANDARD_CALL_FS_READ_AT,
         "read_at",
         "r_std_fs_read_at",
         "std.io::read_result",
         false,
         2U,
         4U,
         {"&std.fs::file", "u64", "bytes", "deadline"}},
        {R_STANDARD_CALL_FS_WRITE_ALL_AT,
         "write_all_at",
         "r_std_fs_write_all_at",
         "std.io::write_all_result",
         false,
         2U,
         4U,
         {"&std.fs::file", "u64", "bytes", "deadline"}},
        {R_STANDARD_CALL_FS_TRY_LOCK,
         "try_lock",
         "r_std_fs_try_lock",
         "bool",
         true,
         UINT32_MAX,
         5U,
         {"&std.fs::file", "std.fs::lock_kind", "u64", "u64", "deadline"}},
        {R_STANDARD_CALL_FS_LOCK,
         "lock",
         "r_std_fs_lock",
         "void",
         true,
         UINT32_MAX,
         5U,
         {"&std.fs::file", "std.fs::lock_kind", "u64", "u64", "deadline"}},
        {R_STANDARD_CALL_FS_UNLOCK,
         "unlock",
         "r_std_fs_unlock",
         "void",
         true,
         UINT32_MAX,
         4U,
         {"&std.fs::file", "u64", "u64", "deadline"}},
        {R_STANDARD_CALL_FS_WRITE,
         "write",
         "r_std_fs_write",
         "std.io::write_result",
         false,
         1U,
         3U,
         {"&std.fs::file", "bytes", "deadline"}},
        {R_STANDARD_CALL_FS_WRITE_ALL,
         "write_all",
         "r_std_fs_write_all",
         "std.io::write_all_result",
         false,
         1U,
         3U,
         {"&std.fs::file", "bytes", "deadline"}},
        {R_STANDARD_CALL_FS_WRITE_FILE_ATOMIC_NO_REPLACE,
         "write_file_atomic_no_replace",
         "r_std_fs_write_file_atomic_no_replace",
         "std.fs::write_file_result",
         false,
         1U,
         3U,
         {"&std.fs::path", "bytes", "deadline"}},
    };
    size_t index;
    for (index = 0U; index < sizeof(operations) / sizeof(operations[0]); ++index) {
        if (operations[index].operation == operation) {
            return &operations[index];
        }
    }
    return NULL;
}

#endif
