#ifndef R_STANDARD_NET_OPERATIONS_H
#define R_STANDARD_NET_OPERATIONS_H

#include "frontend_internal.h"

typedef struct RStandardNetOperationDescriptor {
    const char *name;
    const char *result_type;
    const char *argument_types[4];
    const char *rule;
    uint32_t argument_count;
    uint32_t move_index;
    uint64_t borrow_mask;
    bool is_async;
    bool has_error;
} RStandardNetOperationDescriptor;

static inline const RStandardNetOperationDescriptor *
r_standard_net_operation(RStandardCallOperation operation) {
    static const RStandardNetOperationDescriptor descriptors[] = {
        {"tcp_listener_local_address",
         "std.net::socket_address",
         {"&std.net::tcp_listener", NULL, NULL, NULL},
         "R-SLIB-NET-0006",
         UINT32_C(1),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"tcp_peer_address",
         "std.net::socket_address",
         {"&std.net::tcp_stream", NULL, NULL, NULL},
         "R-SLIB-NET-0006",
         UINT32_C(1),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"udp_local_address",
         "std.net::socket_address",
         {"&std.net::udp_socket", NULL, NULL, NULL},
         "R-SLIB-NET-0007",
         UINT32_C(1),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"tcp_get_options",
         "std.net::tcp_options",
         {"&std.net::tcp_stream", NULL, NULL, NULL},
         "R-SLIB-NET-0012",
         UINT32_C(1),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"tcp_set_options",
         "void",
         {"&std.net::tcp_stream", "std.net::tcp_options", NULL, NULL},
         "R-SLIB-NET-0012",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"udp_get_options",
         "std.net::udp_options",
         {"&std.net::udp_socket", NULL, NULL, NULL},
         "R-SLIB-NET-0012",
         UINT32_C(1),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"udp_set_options",
         "void",
         {"&std.net::udp_socket", "std.net::udp_options", NULL, NULL},
         "R-SLIB-NET-0012",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"udp_join_multicast",
         "void",
         {"&std.net::udp_socket", "std.net::ip_address", "u32", NULL},
         "R-SLIB-NET-0013",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"udp_leave_multicast",
         "void",
         {"&std.net::udp_socket", "std.net::ip_address", "u32", NULL},
         "R-SLIB-NET-0013",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"unix_peer_credentials",
         "std.net::peer_credentials",
         {"&std.net::unix_stream", NULL, NULL, NULL},
         "R-SLIB-NET-0016",
         UINT32_C(1),
         UINT32_MAX,
         UINT64_C(1),
         false,
         true},
        {"resolve",
         "addresses",
         {"str", "u16", "std.net::family", "deadline"},
         "R-SLIB-NET-0003",
         UINT32_C(4),
         UINT32_MAX,
         UINT64_C(1),
         true,
         true},
        {"tcp_listen",
         "std.net::tcp_listener",
         {"std.net::socket_address", "std.net::listen_options", "deadline", NULL},
         "R-SLIB-NET-0004",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"tcp_accept",
         "std.net::tcp_connection",
         {"&std.net::tcp_listener", "deadline", NULL, NULL},
         "R-SLIB-NET-0004",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(1),
         true,
         true},
        {"tcp_connect",
         "std.net::tcp_stream",
         {"std.net::socket_address", "deadline", NULL, NULL},
         "R-SLIB-NET-0004",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"tcp_read",
         "std.net::tcp_read_result",
         {"&std.net::tcp_stream", "bytes", "deadline", NULL},
         "R-SLIB-NET-0005",
         UINT32_C(3),
         UINT32_C(1),
         UINT64_C(1),
         true,
         false},
        {"tcp_write",
         "std.net::tcp_write_result",
         {"&std.net::tcp_stream", "bytes", "deadline", NULL},
         "R-SLIB-NET-0005",
         UINT32_C(3),
         UINT32_C(1),
         UINT64_C(1),
         true,
         false},
        {"tcp_write_all",
         "std.net::tcp_write_all_result",
         {"&std.net::tcp_stream", "bytes", "deadline", NULL},
         "R-SLIB-NET-0005",
         UINT32_C(3),
         UINT32_C(1),
         UINT64_C(1),
         true,
         false},
        {"tcp_shutdown",
         "void",
         {"&std.net::tcp_stream", "std.net::shutdown_direction", "deadline", NULL},
         "R-SLIB-NET-0006",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(1),
         true,
         true},
        {"tcp_close",
         "void",
         {"std.net::tcp_stream", "deadline", NULL, NULL},
         "R-SLIB-NET-0006",
         UINT32_C(2),
         UINT32_C(0),
         UINT64_C(0),
         true,
         true},
        {"tcp_listener_close",
         "void",
         {"std.net::tcp_listener", "deadline", NULL, NULL},
         "R-SLIB-NET-0006",
         UINT32_C(2),
         UINT32_C(0),
         UINT64_C(0),
         true,
         true},
        {"udp_bind",
         "std.net::udp_socket",
         {"std.net::socket_address", "bool", "deadline", NULL},
         "R-SLIB-NET-0007",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"udp_send_to",
         "std.net::udp_send_result",
         {"&std.net::udp_socket", "std.net::socket_address", "bytes", "deadline"},
         "R-SLIB-NET-0008",
         UINT32_C(4),
         UINT32_C(2),
         UINT64_C(1),
         true,
         false},
        {"udp_receive_from",
         "std.net::udp_receive_result",
         {"&std.net::udp_socket", "bytes", "deadline", NULL},
         "R-SLIB-NET-0008",
         UINT32_C(3),
         UINT32_C(1),
         UINT64_C(1),
         true,
         false},
        {"udp_close",
         "void",
         {"std.net::udp_socket", "deadline", NULL, NULL},
         "R-SLIB-NET-0008",
         UINT32_C(2),
         UINT32_C(0),
         UINT64_C(0),
         true,
         true},
        {"unix_listen",
         "std.net::unix_listener",
         {"str", "u32", "bool", "deadline"},
         "R-SLIB-NET-0014",
         UINT32_C(4),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"unix_accept",
         "std.net::unix_stream",
         {"&std.net::unix_listener", "deadline", NULL, NULL},
         "R-SLIB-NET-0014",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(1),
         true,
         true},
        {"unix_connect",
         "std.net::unix_stream",
         {"str", "deadline", NULL, NULL},
         "R-SLIB-NET-0014",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"unix_shutdown",
         "void",
         {"&std.net::unix_stream", "std.net::shutdown_direction", "deadline", NULL},
         "R-SLIB-NET-0015",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(1),
         true,
         true},
        {"unix_close",
         "void",
         {"std.net::unix_stream", "deadline", NULL, NULL},
         "R-SLIB-NET-0015",
         UINT32_C(2),
         UINT32_C(0),
         UINT64_C(0),
         true,
         true},
        {"unix_listener_close",
         "void",
         {"std.net::unix_listener", "deadline", NULL, NULL},
         "R-SLIB-NET-0014",
         UINT32_C(2),
         UINT32_C(0),
         UINT64_C(0),
         true,
         true},
        {"unix_datagram_bind",
         "std.net::unix_datagram",
         {"str", "bool", "deadline", NULL},
         "R-SLIB-NET-0017",
         UINT32_C(3),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"unix_datagram_connect",
         "std.net::unix_datagram",
         {"str", "deadline", NULL, NULL},
         "R-SLIB-NET-0017",
         UINT32_C(2),
         UINT32_MAX,
         UINT64_C(0),
         true,
         true},
        {"unix_datagram_close",
         "void",
         {"std.net::unix_datagram", "deadline", NULL, NULL},
         "R-SLIB-NET-0017",
         UINT32_C(2),
         UINT32_C(0),
         UINT64_C(0),
         true,
         true},
    };
    if (operation < R_STANDARD_CALL_NET_TCP_LISTENER_LOCAL_ADDRESS ||
        operation > R_STANDARD_CALL_NET_UNIX_DATAGRAM_CLOSE) {
        return NULL;
    }
    return &descriptors[(uint32_t)operation -
                        (uint32_t)R_STANDARD_CALL_NET_TCP_LISTENER_LOCAL_ADDRESS];
}

static inline bool r_standard_net_is_async(RStandardCallOperation operation) {
    const RStandardNetOperationDescriptor *descriptor = r_standard_net_operation(operation);
    return descriptor != NULL && descriptor->is_async;
}

typedef struct RStandardNetOutcomeField {
    const char *name;
    const char *type;
    const char *native_member;
} RStandardNetOutcomeField;

typedef struct RStandardNetOutcomeVariant {
    const char *name;
    const char *payload_name;
    const char *native_tag;
    uint32_t field_count;
    RStandardNetOutcomeField fields[4];
} RStandardNetOutcomeVariant;

typedef struct RStandardNetOutcome {
    const char *name;
    const char *native_type;
    uint32_t variant_count;
    RStandardNetOutcomeVariant variants[3];
} RStandardNetOutcome;

static inline const RStandardNetOutcome *r_standard_net_outcome_at(size_t index) {
    static const RStandardNetOutcome outcomes[] = {
        {"std.net::tcp_read_result",
         "RStdNetTcpReadResult",
         3U,
         {
             {"read",
              "std.net::tcp_read_result::read",
              "R_STD_NET_TCP_READ_RESULT_READ",
              2U,
              {
                  {"buffer", "bytes", "buffer"},
                  {"count", "usize", "count"},
              }},
             {"end",
              NULL,
              "R_STD_NET_TCP_READ_RESULT_END",
              0U,
              {
                  {NULL, NULL, NULL},
              }},
             {"failed",
              "std.net::tcp_read_result::failed",
              "R_STD_NET_TCP_READ_RESULT_FAILED",
              3U,
              {
                  {"error", "std.net::net_error", "error"},
                  {"count", "usize", "count"},
                  {"buffer", "bytes", "buffer"},
              }},
         }},
        {"std.net::tcp_write_result",
         "RStdNetTcpWriteResult",
         2U,
         {
             {"written",
              "std.net::tcp_write_result::written",
              "R_STD_NET_TCP_WRITE_RESULT_WRITTEN",
              2U,
              {
                  {"buffer", "bytes", "buffer"},
                  {"count", "usize", "written"},
              }},
             {"failed",
              "std.net::tcp_write_result::failed",
              "R_STD_NET_TCP_WRITE_RESULT_FAILED",
              3U,
              {
                  {"error", "std.net::net_error", "error"},
                  {"written", "usize", "written"},
                  {"buffer", "bytes", "buffer"},
              }},
         }},
        {"std.net::tcp_write_all_result",
         "RStdNetTcpWriteAllResult",
         2U,
         {
             {"written",
              NULL,
              "R_STD_NET_TCP_WRITE_ALL_RESULT_WRITTEN",
              0U,
              {
                  {NULL, NULL, NULL},
              }},
             {"failed",
              "std.net::tcp_write_all_result::failed",
              "R_STD_NET_TCP_WRITE_ALL_RESULT_FAILED",
              3U,
              {
                  {"error", "std.net::net_error", "error"},
                  {"written", "usize", "written"},
                  {"buffer", "bytes", "buffer"},
              }},
         }},
        {"std.net::udp_send_result",
         "RStdNetUdpSendResult",
         2U,
         {
             {"sent",
              NULL,
              "R_STD_NET_UDP_SEND_RESULT_SENT",
              0U,
              {
                  {NULL, NULL, NULL},
              }},
             {"failed",
              "std.net::udp_send_result::failed",
              "R_STD_NET_UDP_SEND_RESULT_FAILED",
              2U,
              {
                  {"error", "std.net::net_error", "error"},
                  {"buffer", "bytes", "buffer"},
              }},
         }},
        {"std.net::udp_receive_result",
         "RStdNetUdpReceiveResult",
         2U,
         {
             {"received",
              "std.net::udp_receive_result::received",
              "R_STD_NET_UDP_RECEIVE_RESULT_RECEIVED",
              4U,
              {
                  {"buffer", "bytes", "buffer"},
                  {"count", "usize", "count"},
                  {"peer", "std.net::socket_address", "peer"},
                  {"truncated", "bool", "truncated"},
              }},
             {"failed",
              "std.net::udp_receive_result::failed",
              "R_STD_NET_UDP_RECEIVE_RESULT_FAILED",
              2U,
              {
                  {"error", "std.net::net_error", "error"},
                  {"buffer", "bytes", "buffer"},
              }},
         }},
    };
    return index < sizeof(outcomes) / sizeof(outcomes[0]) ? &outcomes[index] : NULL;
}

#endif
