/* Generated by re2c 4.5.1 */
/* Generated output is committed in lexer_generated.c. */
#include "frontend_internal.h"

static RAsciiLexeme r_ascii_lexeme(RAsciiLexemeKind kind,
                                   RTokenKind token_kind,
                                   const uint8_t *start,
                                   const uint8_t *end) {
    RAsciiLexeme result;
    result.kind = kind;
    result.token_kind = token_kind;
    result.length = (size_t)(end - start);
    return result;
}

RAsciiLexeme r_lexer_scan_ascii(const uint8_t *cursor) {
    const uint8_t *token_start = cursor;
    const uint8_t *YYCURSOR = cursor;


{
	uint8_t yych;
	yych = *YYCURSOR;
	switch (yych) {
		case 0x00:
		case 0x01:
		case 0x02:
		case 0x03:
		case 0x04:
		case 0x05:
		case 0x06:
		case 0x07:
		case 0x08:
		case 0x0E:
		case 0x0F:
		case 0x10:
		case 0x11:
		case 0x12:
		case 0x13:
		case 0x14:
		case 0x15:
		case 0x16:
		case 0x17:
		case 0x18:
		case 0x19:
		case 0x1A:
		case 0x1B:
		case 0x1C:
		case 0x1D:
		case 0x1E:
		case 0x1F:
		case '#':
		case '$':
		case '\\':
		case '`':
		case 0x7F: goto yy1;
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy2;
		case '!': goto yy4;
		case '"': goto yy6;
		case '%': goto yy7;
		case '&': goto yy9;
		case '\'': goto yy11;
		case '(': goto yy12;
		case ')': goto yy13;
		case '*': goto yy14;
		case '+': goto yy16;
		case ',': goto yy18;
		case '-': goto yy19;
		case '.': goto yy21;
		case '/': goto yy23;
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9': goto yy25;
		case ':': goto yy26;
		case ';': goto yy28;
		case '<': goto yy29;
		case '=': goto yy31;
		case '>': goto yy33;
		case '?': goto yy35;
		case '@': goto yy36;
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy37;
		case '[': goto yy39;
		case ']': goto yy40;
		case '^': goto yy41;
		case '{': goto yy43;
		case '|': goto yy44;
		case '}': goto yy46;
		case '~': goto yy47;
		default: goto yy48;
	}
yy1:
	++YYCURSOR;
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_UNKNOWN, R_TOKEN_INVALID,
                                  token_start, YYCURSOR);
        }
yy2:
	yych = *++YYCURSOR;
	switch (yych) {
		case '\t':
		case '\n':
		case '\v':
		case '\f':
		case '\r':
		case ' ': goto yy2;
		default: goto yy3;
	}
yy3:
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_WHITESPACE, R_TOKEN_WHITESPACE,
                                  token_start, YYCURSOR);
        }
yy4:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy49;
		default: goto yy5;
	}
yy5:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_BANG, token_start, YYCURSOR); }
yy6:
	++YYCURSOR;
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_STRING_START, R_TOKEN_STRING_LITERAL,
                                  token_start, YYCURSOR);
        }
yy7:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy50;
		default: goto yy8;
	}
yy8:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PERCENT, token_start, YYCURSOR); }
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
		case '&': goto yy51;
		case '=': goto yy52;
		default: goto yy10;
	}
yy10:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_AMP, token_start, YYCURSOR); }
yy11:
	++YYCURSOR;
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_CHARACTER_START, R_TOKEN_CHARACTER_LITERAL,
                                  token_start, YYCURSOR);
        }
yy12:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LPAREN, token_start, YYCURSOR); }
yy13:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_RPAREN, token_start, YYCURSOR); }
yy14:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy53;
		default: goto yy15;
	}
yy15:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_STAR, token_start, YYCURSOR); }
yy16:
	yych = *++YYCURSOR;
	switch (yych) {
		case '+': goto yy54;
		case '=': goto yy55;
		default: goto yy17;
	}
yy17:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PLUS, token_start, YYCURSOR); }
yy18:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_COMMA, token_start, YYCURSOR); }
yy19:
	yych = *++YYCURSOR;
	switch (yych) {
		case '-': goto yy56;
		case '=': goto yy57;
		case '>': goto yy58;
		default: goto yy20;
	}
yy20:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_MINUS, token_start, YYCURSOR); }
yy21:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy59;
		default: goto yy22;
	}
yy22:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_DOT, token_start, YYCURSOR); }
yy23:
	yych = *++YYCURSOR;
	switch (yych) {
		case '*': goto yy61;
		case '/': goto yy62;
		case '=': goto yy64;
		default: goto yy24;
	}
yy24:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_SLASH, token_start, YYCURSOR); }
yy25:
	++YYCURSOR;
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_NUMBER_START, R_TOKEN_INVALID,
                                  token_start, YYCURSOR);
        }
yy26:
	yych = *++YYCURSOR;
	switch (yych) {
		case ':': goto yy65;
		default: goto yy27;
	}
yy27:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_COLON, token_start, YYCURSOR); }
yy28:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_SEMICOLON, token_start, YYCURSOR); }
yy29:
	yych = *++YYCURSOR;
	switch (yych) {
		case '<': goto yy66;
		case '=': goto yy68;
		default: goto yy30;
	}
yy30:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LESS, token_start, YYCURSOR); }
yy31:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy69;
		default: goto yy32;
	}
yy32:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_EQUAL, token_start, YYCURSOR); }
yy33:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy70;
		case '>': goto yy71;
		default: goto yy34;
	}
yy34:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_GREATER, token_start, YYCURSOR); }
yy35:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_QUESTION, token_start, YYCURSOR); }
yy36:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_AT, token_start, YYCURSOR); }
yy37:
	yych = *++YYCURSOR;
	switch (yych) {
		case '0':
		case '1':
		case '2':
		case '3':
		case '4':
		case '5':
		case '6':
		case '7':
		case '8':
		case '9':
		case 'A':
		case 'B':
		case 'C':
		case 'D':
		case 'E':
		case 'F':
		case 'G':
		case 'H':
		case 'I':
		case 'J':
		case 'K':
		case 'L':
		case 'M':
		case 'N':
		case 'O':
		case 'P':
		case 'Q':
		case 'R':
		case 'S':
		case 'T':
		case 'U':
		case 'V':
		case 'W':
		case 'X':
		case 'Y':
		case 'Z':
		case '_':
		case 'a':
		case 'b':
		case 'c':
		case 'd':
		case 'e':
		case 'f':
		case 'g':
		case 'h':
		case 'i':
		case 'j':
		case 'k':
		case 'l':
		case 'm':
		case 'n':
		case 'o':
		case 'p':
		case 'q':
		case 'r':
		case 's':
		case 't':
		case 'u':
		case 'v':
		case 'w':
		case 'x':
		case 'y':
		case 'z': goto yy37;
		default: goto yy38;
	}
yy38:
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_IDENTIFIER, R_TOKEN_IDENTIFIER,
                                  token_start, YYCURSOR);
        }
yy39:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LBRACKET, token_start, YYCURSOR); }
yy40:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_RBRACKET, token_start, YYCURSOR); }
yy41:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy73;
		default: goto yy42;
	}
yy42:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_CARET, token_start, YYCURSOR); }
yy43:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LBRACE, token_start, YYCURSOR); }
yy44:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy74;
		case '|': goto yy75;
		default: goto yy45;
	}
yy45:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PIPE, token_start, YYCURSOR); }
yy46:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_RBRACE, token_start, YYCURSOR); }
yy47:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_TILDE, token_start, YYCURSOR); }
yy48:
	++YYCURSOR;
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_NON_ASCII, R_TOKEN_INVALID,
                                  token_start, YYCURSOR);
        }
yy49:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_BANG_EQUAL, token_start, YYCURSOR); }
yy50:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PERCENT_EQUAL, token_start, YYCURSOR); }
yy51:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_AMP_AMP, token_start, YYCURSOR); }
yy52:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_AMP_EQUAL, token_start, YYCURSOR); }
yy53:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_STAR_EQUAL, token_start, YYCURSOR); }
yy54:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PLUS_PLUS, token_start, YYCURSOR); }
yy55:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PLUS_EQUAL, token_start, YYCURSOR); }
yy56:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_MINUS_MINUS, token_start, YYCURSOR); }
yy57:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_MINUS_EQUAL, token_start, YYCURSOR); }
yy58:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_ARROW, token_start, YYCURSOR); }
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
		case '.': goto yy76;
		default: goto yy60;
	}
yy60:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_DOT_DOT, token_start, YYCURSOR); }
yy61:
	++YYCURSOR;
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_BLOCK_COMMENT_START, R_TOKEN_BLOCK_COMMENT,
                                  token_start, YYCURSOR);
        }
yy62:
	yych = *++YYCURSOR;
	switch (yych) {
		case 0x00:
		case '\n':
		case '\r': goto yy63;
		default: goto yy62;
	}
yy63:
	{
            return r_ascii_lexeme(R_ASCII_LEXEME_LINE_COMMENT, R_TOKEN_LINE_COMMENT,
                                  token_start, YYCURSOR);
        }
yy64:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_SLASH_EQUAL, token_start, YYCURSOR); }
yy65:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_COLON_COLON, token_start, YYCURSOR); }
yy66:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy77;
		default: goto yy67;
	}
yy67:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LESS_LESS, token_start, YYCURSOR); }
yy68:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LESS_EQUAL, token_start, YYCURSOR); }
yy69:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_EQUAL_EQUAL, token_start, YYCURSOR); }
yy70:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_GREATER_EQUAL, token_start, YYCURSOR); }
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
		case '=': goto yy78;
		default: goto yy72;
	}
yy72:
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_GREATER_GREATER, token_start, YYCURSOR); }
yy73:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_CARET_EQUAL, token_start, YYCURSOR); }
yy74:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PIPE_EQUAL, token_start, YYCURSOR); }
yy75:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_PIPE_PIPE, token_start, YYCURSOR); }
yy76:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_ELLIPSIS, token_start, YYCURSOR); }
yy77:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_LESS_LESS_EQUAL, token_start, YYCURSOR); }
yy78:
	++YYCURSOR;
	{ return r_ascii_lexeme(R_ASCII_LEXEME_PUNCTUATOR, R_TOKEN_GREATER_GREATER_EQUAL, token_start, YYCURSOR); }
}

}
