if(NOT DEFINED OUTPUT_EXE)
    message(FATAL_ERROR "missing filesystem test executable path")
endif()
set(R_FS_COMPLETE_ROOT "${OUTPUT_EXE}.workspace")
file(REMOVE_RECURSE "${R_FS_COMPLETE_ROOT}")
file(MAKE_DIRECTORY "${R_FS_COMPLETE_ROOT}")
set(PROGRAM_ARGUMENTS "${R_FS_COMPLETE_ROOT}")
include("${CMAKE_CURRENT_LIST_DIR}/check_codegen_program.cmake")
file(GLOB R_FS_COMPLETE_LEFTOVERS "${R_FS_COMPLETE_ROOT}/*")
if(R_FS_COMPLETE_LEFTOVERS)
    message(FATAL_ERROR "filesystem example did not remove its files: ${R_FS_COMPLETE_LEFTOVERS}")
endif()
file(REMOVE_RECURSE "${R_FS_COMPLETE_ROOT}")
