if(NOT DEFINED R_FRONT_EXECUTABLE OR
   NOT DEFINED CLANG_FORMAT OR CLANG_FORMAT STREQUAL "" OR
   NOT DEFINED FORMAT_STYLE OR
   NOT DEFINED OUTPUT_C)
    message(FATAL_ERROR "missing generated C17 format test input")
endif()
if((NOT DEFINED SOURCE_1 OR SOURCE_1 STREQUAL "") AND
   (NOT DEFINED MODULE_MAP OR MODULE_MAP STREQUAL "" OR
    NOT DEFINED ENTRY OR ENTRY STREQUAL ""))
    message(FATAL_ERROR "generated C17 format test requires sources or a module-map entry")
endif()

execute_process(
    COMMAND "${CLANG_FORMAT}" --version
    RESULT_VARIABLE R_FORMAT_VERSION_RESULT
    OUTPUT_VARIABLE R_FORMAT_VERSION_OUTPUT
    ERROR_VARIABLE R_FORMAT_VERSION_ERROR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
if(NOT R_FORMAT_VERSION_RESULT EQUAL 0)
    message(FATAL_ERROR
        "clang-format --version failed (${R_FORMAT_VERSION_RESULT}): "
        "${R_FORMAT_VERSION_OUTPUT}${R_FORMAT_VERSION_ERROR}")
endif()
string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" R_FORMAT_VERSION
    "${R_FORMAT_VERSION_OUTPUT}")
if(NOT R_FORMAT_VERSION STREQUAL "22.1.8")
    message(FATAL_ERROR
        "generated C17 format test requires clang-format 22.1.8, found: "
        "${R_FORMAT_VERSION_OUTPUT}")
endif()

set(R_FRONTEND_ARGUMENTS --emit=c17)
if(DEFINED MODULE_MAP AND NOT MODULE_MAP STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS --module-map "${MODULE_MAP}")
endif()
if(DEFINED ENTRY AND NOT ENTRY STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS --entry "${ENTRY}")
endif()
if(DEFINED LIBRARY_MAP AND NOT LIBRARY_MAP STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS --library-map "${LIBRARY_MAP}")
endif()
if(DEFINED PROFILE AND NOT PROFILE STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS --profile "${PROFILE}")
endif()
if(DEFINED TARGET_MANIFEST AND NOT TARGET_MANIFEST STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS --target-manifest "${TARGET_MANIFEST}")
endif()
if(DEFINED LINK_MANIFEST AND NOT LINK_MANIFEST STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS --link-manifest "${LINK_MANIFEST}")
endif()
# P4.4-4: a module of R tests is translated in test mode, as its program test does.
if(TEST_MODE)
    list(APPEND R_FRONTEND_ARGUMENTS --test)
endif()
if(DEFINED SOURCE_1 AND NOT SOURCE_1 STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS "${SOURCE_1}")
endif()
if(DEFINED SOURCE_2 AND NOT SOURCE_2 STREQUAL "")
    list(APPEND R_FRONTEND_ARGUMENTS "${SOURCE_2}")
endif()
if(DEFINED ABI_INVENTORY AND ABI_INVENTORY)
    set(R_ABI_INCLUDE_FLAGS)
    foreach(R_ABI_DIR IN LISTS HEADER_INCLUDE_DIRS)
        list(APPEND R_ABI_INCLUDE_FLAGS "-I${R_ABI_DIR}")
    endforeach()
    include("${CMAKE_CURRENT_LIST_DIR}/abi_record_support.cmake")
    r_abi_generate_record(
        FRONT "${R_FRONT_EXECUTABLE}"
        PYTHON "${PYTHON_EXECUTABLE}"
        TOOL "${ABI_RECORD_TOOL}"
        CC "${C_COMPILER}"
        OUTPUT_PREFIX "${OUTPUT_C}"
        ARGUMENTS_VARIABLE R_FRONTEND_ARGUMENTS
        INCLUDE_FLAGS ${R_ABI_INCLUDE_FLAGS})
endif()

execute_process(
    COMMAND "${R_FRONT_EXECUTABLE}" ${R_FRONTEND_ARGUMENTS}
    RESULT_VARIABLE R_EMIT_RESULT
    OUTPUT_FILE "${OUTPUT_C}"
    ERROR_VARIABLE R_EMIT_ERROR
)
if(NOT R_EMIT_RESULT EQUAL 0)
    message(FATAL_ERROR
        "r-front --emit=c17 failed (${R_EMIT_RESULT}): ${R_EMIT_ERROR}")
endif()

execute_process(
    COMMAND "${CLANG_FORMAT}"
        --dry-run
        --Werror
        "--style=file:${FORMAT_STYLE}"
        "${OUTPUT_C}"
    RESULT_VARIABLE R_FORMAT_RESULT
    OUTPUT_VARIABLE R_FORMAT_OUTPUT
    ERROR_VARIABLE R_FORMAT_ERROR
)
if(NOT R_FORMAT_RESULT EQUAL 0)
    message(FATAL_ERROR
        "generated C17 is not clang-format clean (${R_FORMAT_RESULT}):\n"
        "${R_FORMAT_OUTPUT}${R_FORMAT_ERROR}")
endif()
