// Generated by tools/generate_numeric_example.py.
module example.numbers.type_c_wchar;

import example.numbers.operation::{Operation};
import example.calculator.common::{Usage};

protected std.string::string format_value(c_wchar value, u32 radix)
    throws std.format::format_error {
    std.format::builder builder = std.format::create();
    u32 output_radix = radix == 0u32 ? 10u32 : radix;
    builder.append(value, output_radix);
    std.string::string text = (move builder).finish();
    return move text;
}

std.string::string evaluate(Operation operation, str first, str second, u32 radix)
    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {
    if (operation == Operation::convert) {
        f64 input = std.convert::parse_f64(first);
        c_wchar value = std.convert::checked_c_wchar(input);
        std.string::string text = format_value(value, radix);
        return move text;
    }
    if (operation == Operation::c_convert) {
        f64 input = std.convert::parse_f64(first);
        c_wchar value = std.c::checked_c_wchar(input);
        std.string::string text = format_value(value, radix);
        return move text;
    }
    c_wchar left = std.convert::parse_c_wchar(first, radix);
    if (operation == Operation::parse) {
        std.string::string text = format_value(left, radix);
        return move text;
    }
    throw Usage { .message = "operation requires an R integer type" };
}
