// Generated by tools/generate_numeric_example.py.
module example.numbers.dispatch;
import example.numbers.operation::{Operation};
import example.calculator.common::{Usage};
import std.text;
import example.numbers.type_i8;
import example.numbers.type_u8;
import example.numbers.type_i16;
import example.numbers.type_u16;
import example.numbers.type_i32;
import example.numbers.type_u32;
import example.numbers.type_i64;
import example.numbers.type_u64;
import example.numbers.type_isize;
import example.numbers.type_usize;
import example.numbers.type_c_char;
import example.numbers.type_c_schar;
import example.numbers.type_c_uchar;
import example.numbers.type_c_short;
import example.numbers.type_c_ushort;
import example.numbers.type_c_int;
import example.numbers.type_c_uint;
import example.numbers.type_c_long;
import example.numbers.type_c_ulong;
import example.numbers.type_c_llong;
import example.numbers.type_c_ullong;
import example.numbers.type_c_bool;
import example.numbers.type_c_wchar;
import example.numbers.type_c_wint;
import example.numbers.type_c_int8;
import example.numbers.type_c_uint8;
import example.numbers.type_c_int16;
import example.numbers.type_c_uint16;
import example.numbers.type_c_int32;
import example.numbers.type_c_uint32;
import example.numbers.type_c_int64;
import example.numbers.type_c_uint64;
import example.numbers.type_c_intptr;
import example.numbers.type_c_uintptr;
import example.numbers.type_c_intmax;
import example.numbers.type_c_uintmax;
import example.numbers.type_c_size;
import example.numbers.type_c_ptrdiff;
import example.numbers.type_f32;
import example.numbers.type_f64;
import example.numbers.type_c_float;
import example.numbers.type_c_double;
import example.numbers.type_c_long_double;

std.string::string evaluate(Operation operation, str kind, str first, str second, str third, u32 radix)
    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {
    bool choose_i8 = std.text::equal_ignore_ascii_case(kind, "i8");
    if (choose_i8 == true) {
        std.string::string text = example.numbers.type_i8::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_u8 = std.text::equal_ignore_ascii_case(kind, "u8");
    if (choose_u8 == true) {
        std.string::string text = example.numbers.type_u8::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_i16 = std.text::equal_ignore_ascii_case(kind, "i16");
    if (choose_i16 == true) {
        std.string::string text = example.numbers.type_i16::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_u16 = std.text::equal_ignore_ascii_case(kind, "u16");
    if (choose_u16 == true) {
        std.string::string text = example.numbers.type_u16::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_i32 = std.text::equal_ignore_ascii_case(kind, "i32");
    if (choose_i32 == true) {
        std.string::string text = example.numbers.type_i32::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_u32 = std.text::equal_ignore_ascii_case(kind, "u32");
    if (choose_u32 == true) {
        std.string::string text = example.numbers.type_u32::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_i64 = std.text::equal_ignore_ascii_case(kind, "i64");
    if (choose_i64 == true) {
        std.string::string text = example.numbers.type_i64::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_u64 = std.text::equal_ignore_ascii_case(kind, "u64");
    if (choose_u64 == true) {
        std.string::string text = example.numbers.type_u64::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_isize = std.text::equal_ignore_ascii_case(kind, "isize");
    if (choose_isize == true) {
        std.string::string text = example.numbers.type_isize::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_usize = std.text::equal_ignore_ascii_case(kind, "usize");
    if (choose_usize == true) {
        std.string::string text = example.numbers.type_usize::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_char = std.text::equal_ignore_ascii_case(kind, "c_char");
    if (choose_c_char == true) {
        std.string::string text = example.numbers.type_c_char::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_schar = std.text::equal_ignore_ascii_case(kind, "c_schar");
    if (choose_c_schar == true) {
        std.string::string text = example.numbers.type_c_schar::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uchar = std.text::equal_ignore_ascii_case(kind, "c_uchar");
    if (choose_c_uchar == true) {
        std.string::string text = example.numbers.type_c_uchar::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_short = std.text::equal_ignore_ascii_case(kind, "c_short");
    if (choose_c_short == true) {
        std.string::string text = example.numbers.type_c_short::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_ushort = std.text::equal_ignore_ascii_case(kind, "c_ushort");
    if (choose_c_ushort == true) {
        std.string::string text = example.numbers.type_c_ushort::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_int = std.text::equal_ignore_ascii_case(kind, "c_int");
    if (choose_c_int == true) {
        std.string::string text = example.numbers.type_c_int::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uint = std.text::equal_ignore_ascii_case(kind, "c_uint");
    if (choose_c_uint == true) {
        std.string::string text = example.numbers.type_c_uint::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_long = std.text::equal_ignore_ascii_case(kind, "c_long");
    if (choose_c_long == true) {
        std.string::string text = example.numbers.type_c_long::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_ulong = std.text::equal_ignore_ascii_case(kind, "c_ulong");
    if (choose_c_ulong == true) {
        std.string::string text = example.numbers.type_c_ulong::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_llong = std.text::equal_ignore_ascii_case(kind, "c_llong");
    if (choose_c_llong == true) {
        std.string::string text = example.numbers.type_c_llong::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_ullong = std.text::equal_ignore_ascii_case(kind, "c_ullong");
    if (choose_c_ullong == true) {
        std.string::string text = example.numbers.type_c_ullong::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_bool = std.text::equal_ignore_ascii_case(kind, "c_bool");
    if (choose_c_bool == true) {
        std.string::string text = example.numbers.type_c_bool::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_wchar = std.text::equal_ignore_ascii_case(kind, "c_wchar");
    if (choose_c_wchar == true) {
        std.string::string text = example.numbers.type_c_wchar::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_wint = std.text::equal_ignore_ascii_case(kind, "c_wint");
    if (choose_c_wint == true) {
        std.string::string text = example.numbers.type_c_wint::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_int8 = std.text::equal_ignore_ascii_case(kind, "c_int8");
    if (choose_c_int8 == true) {
        std.string::string text = example.numbers.type_c_int8::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uint8 = std.text::equal_ignore_ascii_case(kind, "c_uint8");
    if (choose_c_uint8 == true) {
        std.string::string text = example.numbers.type_c_uint8::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_int16 = std.text::equal_ignore_ascii_case(kind, "c_int16");
    if (choose_c_int16 == true) {
        std.string::string text = example.numbers.type_c_int16::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uint16 = std.text::equal_ignore_ascii_case(kind, "c_uint16");
    if (choose_c_uint16 == true) {
        std.string::string text = example.numbers.type_c_uint16::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_int32 = std.text::equal_ignore_ascii_case(kind, "c_int32");
    if (choose_c_int32 == true) {
        std.string::string text = example.numbers.type_c_int32::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uint32 = std.text::equal_ignore_ascii_case(kind, "c_uint32");
    if (choose_c_uint32 == true) {
        std.string::string text = example.numbers.type_c_uint32::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_int64 = std.text::equal_ignore_ascii_case(kind, "c_int64");
    if (choose_c_int64 == true) {
        std.string::string text = example.numbers.type_c_int64::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uint64 = std.text::equal_ignore_ascii_case(kind, "c_uint64");
    if (choose_c_uint64 == true) {
        std.string::string text = example.numbers.type_c_uint64::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_intptr = std.text::equal_ignore_ascii_case(kind, "c_intptr");
    if (choose_c_intptr == true) {
        std.string::string text = example.numbers.type_c_intptr::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uintptr = std.text::equal_ignore_ascii_case(kind, "c_uintptr");
    if (choose_c_uintptr == true) {
        std.string::string text = example.numbers.type_c_uintptr::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_intmax = std.text::equal_ignore_ascii_case(kind, "c_intmax");
    if (choose_c_intmax == true) {
        std.string::string text = example.numbers.type_c_intmax::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_uintmax = std.text::equal_ignore_ascii_case(kind, "c_uintmax");
    if (choose_c_uintmax == true) {
        std.string::string text = example.numbers.type_c_uintmax::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_size = std.text::equal_ignore_ascii_case(kind, "c_size");
    if (choose_c_size == true) {
        std.string::string text = example.numbers.type_c_size::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_ptrdiff = std.text::equal_ignore_ascii_case(kind, "c_ptrdiff");
    if (choose_c_ptrdiff == true) {
        std.string::string text = example.numbers.type_c_ptrdiff::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_f32 = std.text::equal_ignore_ascii_case(kind, "f32");
    if (choose_f32 == true) {
        std.string::string text = example.numbers.type_f32::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_f64 = std.text::equal_ignore_ascii_case(kind, "f64");
    if (choose_f64 == true) {
        std.string::string text = example.numbers.type_f64::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_float = std.text::equal_ignore_ascii_case(kind, "c_float");
    if (choose_c_float == true) {
        std.string::string text = example.numbers.type_c_float::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_double = std.text::equal_ignore_ascii_case(kind, "c_double");
    if (choose_c_double == true) {
        std.string::string text = example.numbers.type_c_double::evaluate(operation, first, second, third, radix);
        return move text;
    }
    bool choose_c_long_double = std.text::equal_ignore_ascii_case(kind, "c_long_double");
    if (choose_c_long_double == true) {
        std.string::string text = example.numbers.type_c_long_double::evaluate(operation, first, second, third, radix);
        return move text;
    }
    throw Usage { .message = "unknown numeric type" };
}
