// Generated by tools/generate_numeric_example.py.
module example.numbers.type_i32;

import example.numbers.operation::{Operation};
import example.calculator.common::{Usage};

protected std.string::string format_value(i32 value, u32 radix)
    throws std.format::format_error {
    std.format::builder builder = std.format::create();
    u32 output_radix = radix == 0u32 ? 10u32 : radix;
    builder.append(value, output_radix);
    std.string::string text = (move builder).finish();
    return move text;
}

std.string::string evaluate(Operation operation, str first, str second, str third, u32 radix)
    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {
    if (operation == Operation::convert) {
        f64 input = std.convert::parse_f64(first);
        i32 value = std.convert::checked_i32(input);
        std.string::string text = format_value(value, radix);
        return move text;
    }
    if (operation == Operation::limits) {
        i32 minimum = core::min_i32;
        i32 maximum = core::max_i32;
        std.string::string low = format_value(minimum, radix);
        std.string::string high = format_value(maximum, radix);
        std.string::string text = f"{low} {high}";
        return move text;
    }
    i32 left = std.convert::parse_i32(first, radix);
    if (operation == Operation::parse) {
        std.string::string text = format_value(left, radix);
        return move text;
    }
    switch (operation) {
    case Operation::leading_zeros:
        u32 count = core::leading_zeros(left);
        std.string::string text = f"{count}";
        return move text;
    case Operation::trailing_zeros:
        u32 count = core::trailing_zeros(left);
        std.string::string text = f"{count}";
        return move text;
    case Operation::count_ones:
        u32 count = core::count_ones(left);
        std.string::string text = f"{count}";
        return move text;
    case Operation::swap_bytes:
        i32 value = core::swap_bytes(left);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::rotate_left:
        u32 count = std.convert::parse_u32(second, 10u32);
        i32 value = core::rotate_left(left, count);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::rotate_right:
        u32 count = std.convert::parse_u32(second, 10u32);
        i32 value = core::rotate_right(left, count);
        std.string::string text = format_value(value, radix);
        return move text;
    default: break;
    }
    i32 right = std.convert::parse_i32(second, radix);
    switch (operation) {
    case Operation::checked_add:
        o<i32> result = core::checked_add(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::checked_sub:
        o<i32> result = core::checked_sub(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::checked_mul:
        o<i32> result = core::checked_mul(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::wrapping_add:
        i32 value = core::wrapping_add(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::wrapping_sub:
        i32 value = core::wrapping_sub(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::wrapping_mul:
        i32 value = core::wrapping_mul(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_add:
        i32 value = core::saturating_add(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_sub:
        i32 value = core::saturating_sub(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_mul:
        i32 value = core::saturating_mul(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    default: throw Usage { .message = "unsupported integer operation" };
    }
    throw Usage { .message = "operation requires an R integer type" };
}
