// Generated by tools/generate_numeric_example.py.
module example.numbers.type_isize;

import example.numbers.operation::{Operation};
import example.calculator.common::{Usage};

protected std.string::string format_value(isize value, u32 radix)
    throws std.format::format_error {
    std.format::builder builder = std.format::create();
    u32 output_radix = radix == 0u32 ? 10u32 : radix;
    builder.append(value, output_radix);
    std.string::string text = (move builder).finish();
    return move text;
}

std.string::string evaluate(Operation operation, str first, str second, u32 radix)
    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {
    if (operation == Operation::convert) {
        f64 input = std.convert::parse_f64(first);
        isize value = std.convert::checked_isize(input);
        std.string::string text = format_value(value, radix);
        return move text;
    }
    if (operation == Operation::limits) {
        isize minimum = core::min_isize;
        isize maximum = core::max_isize;
        std.string::string low = format_value(minimum, radix);
        std.string::string high = format_value(maximum, radix);
        std.string::string text = f"{low} {high}";
        return move text;
    }
    isize left = std.convert::parse_isize(first, radix);
    if (operation == Operation::parse) {
        std.string::string text = format_value(left, radix);
        return move text;
    }
    isize right = std.convert::parse_isize(second, radix);
    switch (operation) {
    case Operation::checked_add:
        o<isize> result = core::checked_add(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::checked_sub:
        o<isize> result = core::checked_sub(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::checked_mul:
        o<isize> result = core::checked_mul(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::wrapping_add:
        isize value = core::wrapping_add(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::wrapping_sub:
        isize value = core::wrapping_sub(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::wrapping_mul:
        isize value = core::wrapping_mul(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_add:
        isize value = core::saturating_add(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_sub:
        isize value = core::saturating_sub(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_mul:
        isize value = core::saturating_mul(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    default: throw Usage { .message = "unsupported integer operation" };
    }
    throw Usage { .message = "operation requires an R integer type" };
}
