// Generated by tools/generate_numeric_example.py.
module example.numbers.operation;

enum Operation {
    parse,
    convert,
    c_convert,
    limits,
    checked_add,
    checked_sub,
    checked_mul,
    wrapping_add,
    wrapping_sub,
    wrapping_mul,
    saturating_add,
    saturating_sub,
    saturating_mul,
    leading_zeros,
    trailing_zeros,
    count_ones,
    swap_bytes,
    rotate_left,
    rotate_right,
    widening_mul,
    carrying_add,
    borrowing_sub,
    narrowing_div,
};
