// Generated by tools/generate_numeric_example.py.
module example.numbers.operation;

enum Operation {
    parse,
    convert,
    c_convert,
    limits,
    checked_add,
    checked_sub,
    checked_mul,
    wrapping_add,
    wrapping_sub,
    wrapping_mul,
    saturating_add,
    saturating_sub,
    saturating_mul,
};
