// Generated by tools/generate_numeric_example.py.
module example.numbers.type_u8;

import example.numbers.operation::{Operation};
import example.calculator.common::{Usage};

protected std.string::string format_value(u8 value, u32 radix)
    throws std.format::format_error {
    std.format::builder builder = std.format::create();
    u32 output_radix = radix == 0u32 ? 10u32 : radix;
    builder.append(value, output_radix);
    std.string::string text = (move builder).finish();
    return move text;
}

std.string::string evaluate(Operation operation, str first, str second, str third, u32 radix)
    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {
    if (operation == Operation::convert) {
        f64 input = std.convert::parse_f64(first);
        u8 value = std.convert::checked_u8(input);
        std.string::string text = format_value(value, radix);
        return move text;
    }
    if (operation == Operation::limits) {
        u8 minimum = core::min_u8;
        u8 maximum = core::max_u8;
        std.string::string low = format_value(minimum, radix);
        std.string::string high = format_value(maximum, radix);
        std.string::string text = f"{low} {high}";
        return move text;
    }
    u8 left = std.convert::parse_u8(first, radix);
    if (operation == Operation::parse) {
        std.string::string text = format_value(left, radix);
        return move text;
    }
    switch (operation) {
    case Operation::leading_zeros:
        u32 count = core::leading_zeros(left);
        std.string::string text = f"{count}";
        return move text;
    case Operation::trailing_zeros:
        u32 count = core::trailing_zeros(left);
        std.string::string text = f"{count}";
        return move text;
    case Operation::count_ones:
        u32 count = core::count_ones(left);
        std.string::string text = f"{count}";
        return move text;
    case Operation::swap_bytes:
        u8 value = core::swap_bytes(left);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::rotate_left:
        u32 count = std.convert::parse_u32(second, 10u32);
        u8 value = core::rotate_left(left, count);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::rotate_right:
        u32 count = std.convert::parse_u32(second, 10u32);
        u8 value = core::rotate_right(left, count);
        std.string::string text = format_value(value, radix);
        return move text;
    default: break;
    }
    u8 right = std.convert::parse_u8(second, radix);
    switch (operation) {
    case Operation::checked_add:
        o<u8> result = core::checked_add(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::checked_sub:
        o<u8> result = core::checked_sub(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::checked_mul:
        o<u8> result = core::checked_mul(left, right);
        switch (result) {
        case variant o::some(value):
            std.string::string text = format_value(*value, radix);
            return move text;
        case variant o::none:
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        break;
    case Operation::wrapping_add:
        u8 value = core::wrapping_add(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::wrapping_sub:
        u8 value = core::wrapping_sub(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::wrapping_mul:
        u8 value = core::wrapping_mul(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_add:
        u8 value = core::saturating_add(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_sub:
        u8 value = core::saturating_sub(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::saturating_mul:
        u8 value = core::saturating_mul(left, right);
        std.string::string text = format_value(value, radix);
        return move text;
    case Operation::widening_mul:
        auto (low, high) = core::widening_mul(left, right);
        std.string::string low_text = format_value(low, radix);
        std.string::string high_text = format_value(high, radix);
        std.string::string text = f"{low_text} {high_text}";
        return move text;
    case Operation::carrying_add:
        u8 extra = std.convert::parse_u8(third, radix);
        auto (value, carry) = core::carrying_add(left, right, extra != 0u8);
        std.string::string value_text = format_value(value, radix);
        std.string::string text = f"{value_text} {carry}";
        return move text;
    case Operation::borrowing_sub:
        u8 extra = std.convert::parse_u8(third, radix);
        auto (value, borrow) = core::borrowing_sub(left, right, extra != 0u8);
        std.string::string value_text = format_value(value, radix);
        std.string::string text = f"{value_text} {borrow}";
        return move text;
    case Operation::narrowing_div:
        u8 divisor = std.convert::parse_u8(third, radix);
        bool fits = left < divisor;
        if (fits == false) {
            right as void;
            std.string::string text = std.string::from_str("overflow");
            return move text;
        }
        auto (quotient, remainder) = core::narrowing_div(left, right, divisor);
        std.string::string quotient_text = format_value(quotient, radix);
        std.string::string remainder_text = format_value(remainder, radix);
        std.string::string text = f"{quotient_text} {remainder_text}";
        return move text;
    default: throw Usage { .message = "unsupported integer operation" };
    }
    throw Usage { .message = "operation requires an R integer type" };
}
