// Generated by tools/generate_calculator.py. See README.md for CLI examples.
module example.calculator.number_c_float;

import example.calculator.operations::{Operation};
import example.calculator.common::{Usage, require_operands};

std.string::string evaluate(Operation operation, str... operands)
    throws Usage, std.convert::parse_error, std.math::math_error, std.alloc::alloc_error {
    switch (operation) {
    case Operation::abs:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::abs(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::acos:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::acos(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::acosh:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::acosh(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::asin:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::asin(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::asinh:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::asinh(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::atan2:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::atan2(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::atan:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::atan(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::atanh:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::atanh(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::cbrt:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::cbrt(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::ceil:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::ceil(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::compose_binary:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        i32 operand1 = std.convert::parse_i32(operands[1], 10u32);
        c_float value = std.math::compose_binary(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::copy_sign:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::copy_sign(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::cos:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::cos(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::cosh:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::cosh(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::erf:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::erf(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::erfc:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::erfc(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::exp2:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::exp2(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::exp:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::exp(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::expm1:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::expm1(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::floor:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::floor(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::gamma:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::gamma(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::hypot:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::hypot(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::is_finite:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        bool value = std.math::is_finite(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::is_infinite:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        bool value = std.math::is_infinite(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::is_nan:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        bool value = std.math::is_nan(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::is_normal:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        bool value = std.math::is_normal(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::log10:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::log10(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::log1p:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::log1p(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::log2:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::log2(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::log:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::log(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::log_gamma:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::log_gamma(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::max:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::max(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::min:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::min(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::next_after:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::next_after(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::pow:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::pow(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::remainder:
        require_operands(operands, 2usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float operand1 = std.convert::parse_c_float(operands[1]);
        c_float value = std.math::remainder(operand0, operand1);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::round:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::round(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::sign_bit:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        bool value = std.math::sign_bit(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::sin:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::sin(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::sinh:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::sinh(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::split_binary:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        std.math::binary_parts_c_float value = std.math::split_binary(operand0);
        std.string::string text = f"{value.fraction} {value.exponent}\n";
        return move text;
    case Operation::split_fraction:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        std.math::fraction_parts_c_float value = std.math::split_fraction(operand0);
        std.string::string text = f"{value.whole} {value.fraction}\n";
        return move text;
    case Operation::sqrt:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::sqrt(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::tan:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::tan(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::tanh:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::tanh(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::trunc:
        require_operands(operands, 1usize);
        c_float operand0 = std.convert::parse_c_float(operands[0]);
        c_float value = std.math::trunc(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    default:
        throw Usage { .message = "operation does not support this number type" };
    }
}
