// Generated by tools/generate_calculator.py. See README.md for CLI examples.
module example.calculator.number_complex_f32;

import example.calculator.operations::{Operation};
import example.calculator.common::{Usage, require_operands};

std.string::string evaluate(Operation operation, str... operands)
    throws Usage, std.convert::parse_error, std.math::math_error, std.alloc::alloc_error {
    switch (operation) {
    case Operation::add:
        require_operands(operands, 4usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 real1 = std.convert::parse_f32(operands[2]);
        f32 imag1 = std.convert::parse_f32(operands[3]);
        std.math::complex_f32 operand1 = { .real = real1, .imag = imag1 };
        std.math::complex_f32 value = std.math::add(operand0, operand1);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::conjugate:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::conjugate(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::cos:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::cos(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::cosh:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::cosh(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::div:
        require_operands(operands, 4usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 real1 = std.convert::parse_f32(operands[2]);
        f32 imag1 = std.convert::parse_f32(operands[3]);
        std.math::complex_f32 operand1 = { .real = real1, .imag = imag1 };
        std.math::complex_f32 value = std.math::div(operand0, operand1);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::exp:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::exp(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::log:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::log(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::magnitude:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 value = std.math::magnitude(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::mul:
        require_operands(operands, 4usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 real1 = std.convert::parse_f32(operands[2]);
        f32 imag1 = std.convert::parse_f32(operands[3]);
        std.math::complex_f32 operand1 = { .real = real1, .imag = imag1 };
        std.math::complex_f32 value = std.math::mul(operand0, operand1);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::phase:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 value = std.math::phase(operand0);
        std.string::string text = f"{value}\n";
        return move text;
    case Operation::pow:
        require_operands(operands, 4usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 real1 = std.convert::parse_f32(operands[2]);
        f32 imag1 = std.convert::parse_f32(operands[3]);
        std.math::complex_f32 operand1 = { .real = real1, .imag = imag1 };
        std.math::complex_f32 value = std.math::pow(operand0, operand1);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::sin:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::sin(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::sinh:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::sinh(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::sqrt:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::sqrt(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::sub:
        require_operands(operands, 4usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        f32 real1 = std.convert::parse_f32(operands[2]);
        f32 imag1 = std.convert::parse_f32(operands[3]);
        std.math::complex_f32 operand1 = { .real = real1, .imag = imag1 };
        std.math::complex_f32 value = std.math::sub(operand0, operand1);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::tan:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::tan(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    case Operation::tanh:
        require_operands(operands, 2usize);
        f32 real0 = std.convert::parse_f32(operands[0]);
        f32 imag0 = std.convert::parse_f32(operands[1]);
        std.math::complex_f32 operand0 = { .real = real0, .imag = imag0 };
        std.math::complex_f32 value = std.math::tanh(operand0);
        std.string::string text = f"{value.real} {value.imag}\n";
        return move text;
    default:
        throw Usage { .message = "operation does not support this number type" };
    }
}
