#ifndef R_RUNTIME_FREESTANDING_H
#define R_RUNTIME_FREESTANDING_H

#include "r_runtime_core.h"

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Environment contract of the freestanding profile (Core R-CONF-0005, Annex G.3). The environment
 * that embeds a freestanding R program supplies the panic handler and the stack bounds of every
 * thread that enters R code. The freestanding runtime allocates nothing, performs no I/O and
 * creates no threads.
 */

/* Supplied by the environment: receives every panic and never returns. */
_Noreturn void r_runtime_environment_panic(RRuntimePanicCategory category, RRuntimeSourceSpan span);

/*
 * Adopts [low, high) as the current thread's stack before its first entry into R code. The
 * runtime leaves R_RUNTIME_STACK_PROTECTED_LOW_BYTES above low untouched. Returns whether the
 * range is usable from the current stack position; a rejected range leaves no bounds installed.
 */
_Bool r_runtime_freestanding_stack_adopt(uintptr_t low, uintptr_t high);

/* Forgets the adopted bounds of the current thread; later entries report stack exhaustion. */
void r_runtime_freestanding_stack_release(void);

/*
 * Runs the destruction entry installed by the generated program for the thread-local objects of
 * the current thread. The environment calls it once when a thread leaves R code for the last time.
 */
void r_runtime_freestanding_thread_exit(void);

/*
 * Generated by the compiler for a freestanding program that defines an R main: performs the
 * entry stack preflight, initializes the static objects, runs main, drops the static objects and
 * returns the R status. The environment adopts the stack bounds and installs the panic handler
 * before calling it. Every @callback function is a further entry from C.
 */
int32_t r_freestanding_main(void);

#ifdef __cplusplus
}
#endif

#endif
