/* Generated by the R 0.1 reference frontend. */
#include "r_core.h"
#include "r_runtime_0_1.h"
#include "r_runtime_target_abi.h"
#include "r_std_alloc.h"
#include "r_std_async.h"
#include "r_std_bits.h"
#include "r_std_bytes.h"
#include "r_std_c.h"
#include "r_std_convert.h"
#include "r_std_env.h"
#include "r_std_error.h"
#include "r_std_error_types.h"
#include "r_std_format.h"
#include "r_std_fs.h"
#include "r_std_io.h"
#include "r_std_math.h"
#include "r_std_net.h"
#include "r_std_process.h"
#include "r_std_string.h"
#include "r_std_sync.h"
#include "r_std_thread.h"
#include "r_std_time.h"

#include <float.h>
#include <limits.h>
#include <stddef.h>
#include <stdint.h>

#if defined(R_STACK_USAGE_MEASUREMENT)
#define R_STACK_FRAME(name) ((size_t)0)
#define R_STACK_ENTRY(name) ((size_t)0)
#elif defined(R_GENERATED_STACK_USAGE_H)
#define R_STACK_FRAME(name) R_STACK_FRAME_##name
#define R_STACK_ENTRY(name) R_STACK_ENTRY_##name
#else
#error "R generated C17 requires a measured stack-usage header"
#define R_STACK_FRAME(name) ((size_t)0)
#define R_STACK_ENTRY(name) ((size_t)0)
#endif

_Static_assert(CHAR_BIT == 8, "R requires 8-bit bytes");
_Static_assert(INT8_MAX == INT8_C(127), "R i8 requires an exact 8-bit representation");
_Static_assert(UINT8_MAX == UINT8_C(255), "R u8 requires an exact 8-bit representation");
_Static_assert(INT16_MAX == INT16_C(32767), "R i16 requires an exact 16-bit representation");
_Static_assert(UINT16_MAX == UINT16_C(65535), "R u16 requires an exact 16-bit representation");
_Static_assert(INT32_MAX == INT32_C(2147483647), "R i32 requires an exact 32-bit representation");
_Static_assert(UINT32_MAX == UINT32_C(4294967295), "R u32 requires an exact 32-bit representation");
_Static_assert(INT64_MAX == INT64_C(9223372036854775807),
               "R i64 requires an exact 64-bit representation");
_Static_assert(UINT64_MAX == UINT64_C(18446744073709551615),
               "R u64 requires an exact 64-bit representation");
_Static_assert(PTRDIFF_MAX == INT64_MAX, "arm64-apple-darwin isize requires 64 bits");
_Static_assert(SIZE_MAX == UINT64_MAX, "arm64-apple-darwin usize requires 64 bits");
_Static_assert(sizeof(float) == 4 && FLT_RADIX == 2 && FLT_MANT_DIG == 24 && FLT_MAX_EXP == 128,
               "R f32 requires IEC 60559 binary32");
_Static_assert(sizeof(double) == 8 && FLT_RADIX == 2 && DBL_MANT_DIG == 53 && DBL_MAX_EXP == 1024,
               "R f64 requires IEC 60559 binary64");

typedef RRuntimeTask *r_task;

typedef struct r_d00000001 r_d00000001;

struct r_d00000001 {
    uint32_t r_tag;
    union {
        int32_t r_ok;
        RCoreUtf8Error r_error_00000001;
        RStdAllocError r_error_00000002;
        RStdAsyncStartError r_error_00000003;
        RStdBitsReadError r_error_00000004;
        RStdBytesError r_error_00000005;
        RStdCRuntimeError r_error_00000006;
        RStdCStringError r_error_00000007;
        RStdConvertParseError r_error_00000008;
        RStdConvertRangeError r_error_00000009;
        RStdEnvError r_error_00000010;
        RStdError r_error_00000011;
        RStdFormatError r_error_00000012;
        RStdFsError r_error_00000013;
        RStdFsPathError r_error_00000014;
        RStdIoError r_error_00000015;
        RStdMathError r_error_00000016;
        RStdNetAddressError r_error_00000017;
        RStdNetError r_error_00000018;
        RStdProcessError r_error_00000019;
        RStdStringBoundaryError r_error_00000020;
        RStdStringError r_error_00000021;
        RStdSyncBarrierError r_error_00000022;
        RStdThreadError r_error_00000023;
        RStdTimeDurationError r_error_00000024;
        RStdTimeError r_error_00000025;
    } r_payload;
};

void r_f00000001(r_d00000001 *);

void r_f00000001(r_d00000001 *r_effect_out) {
    int32_t r_t00000001 = INT32_C(0);
    r_effect_out->r_payload.r_ok = r_t00000001;
    r_effect_out->r_tag = UINT32_C(0);
    return;
    r_runtime_panic(R_RUNTIME_PANIC_CONTRACT_VIOLATION,
                    (RRuntimeSourceSpan){UINT32_C(1), UINT32_C(24), UINT32_C(52)});
}

int main(int argc, char *argv[]) {
    RRuntimeStartResult r_start;
    int32_t r_result;
    r_d00000001 r_outcome = {0};
    if (!r_runtime_stack_initialize_current_thread()) {
        r_runtime_panic(R_RUNTIME_PANIC_STACK_EXHAUSTION,
                        (RRuntimeSourceSpan){UINT32_C(1), UINT32_C(24), UINT32_C(52)});
    }
    r_runtime_stack_require(0U, (RRuntimeSourceSpan){UINT32_C(1), UINT32_C(24), UINT32_C(52)});
    r_start = r_runtime_hosted_start(argc, argv);
    if (!r_start.started) {
        return r_start.process_status;
    }
    r_runtime_stack_require(R_STACK_ENTRY(r_f00000001),
                            (RRuntimeSourceSpan){UINT32_C(1), UINT32_C(24), UINT32_C(52)});
    r_f00000001(&r_outcome);
    if (r_outcome.r_tag == UINT32_C(0)) {
        r_result = r_outcome.r_payload.r_ok;
        if (r_result < 0 || r_result > 111) {
            static const char diagnostic[] = "R main error: invalid_main_status\n";
            r_runtime_emergency_write(diagnostic, sizeof(diagnostic) - 1U);
            r_result = 124;
        }
    } else {
        RStdError r_error;
        RStdStringView r_name;
        const char *r_domain;
        size_t r_domain_length;
        switch (r_outcome.r_tag) {
        case UINT32_C(1): /* core::utf8_error */
            r_error.domain = R_STD_ERROR_DOMAIN_STRING;
            r_error.code = UINT32_C(0);
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(2): /* std.alloc::alloc_error */
            r_error.domain = R_STD_ERROR_DOMAIN_ALLOCATION;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000002;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(3): /* std.async::start_error */
            r_error.domain = R_STD_ERROR_DOMAIN_ASYNC_RUNTIME;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000003;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(4): /* std.bits::read_error */
            r_error.domain = R_STD_ERROR_DOMAIN_BYTES;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000004.code;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(5): /* std.bytes::bytes_error */
            r_error.domain = R_STD_ERROR_DOMAIN_BYTES;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000005;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(6): /* std.c::runtime_error */
            r_error.domain = R_STD_ERROR_DOMAIN_C_ABI;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000006;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(7): /* std.c::string_error */
            r_error.domain = R_STD_ERROR_DOMAIN_C_ABI;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000007.kind;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(8): /* std.convert::parse_error */
            r_error.domain = R_STD_ERROR_DOMAIN_CONVERSION;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000008.code;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(9): /* std.convert::range_error */
            r_error.domain = R_STD_ERROR_DOMAIN_CONVERSION;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000009;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(10): /* std.env::env_error */
            r_error.domain = R_STD_ERROR_DOMAIN_ENVIRONMENT;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000010.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000010.native_code;
            break;
        case UINT32_C(11): /* std.error::error */
            r_error = r_outcome.r_payload.r_error_00000011;
            break;
        case UINT32_C(12): /* std.format::format_error */
            r_error.domain = R_STD_ERROR_DOMAIN_FORMAT;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000012.kind;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(13): /* std.fs::fs_error */
            r_error.domain = R_STD_ERROR_DOMAIN_FILESYSTEM;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000013.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000013.native_code;
            break;
        case UINT32_C(14): /* std.fs::path_error */
            r_error.domain = R_STD_ERROR_DOMAIN_FILESYSTEM;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000014.kind;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(15): /* std.io::io_error */
            r_error.domain = R_STD_ERROR_DOMAIN_IO;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000015.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000015.native_code;
            break;
        case UINT32_C(16): /* std.math::math_error */
            r_error.domain = R_STD_ERROR_DOMAIN_MATH;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000016.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000016.native_code;
            break;
        case UINT32_C(17): /* std.net::address_error */
            r_error.domain = R_STD_ERROR_DOMAIN_NETWORK;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000017.code;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(18): /* std.net::net_error */
            r_error.domain = R_STD_ERROR_DOMAIN_NETWORK;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000018.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000018.native_code;
            break;
        case UINT32_C(19): /* std.process::process_error */
            r_error.domain = R_STD_ERROR_DOMAIN_PROCESS;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000019.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000019.native_code;
            break;
        case UINT32_C(20): /* std.string::boundary_error */
            r_error.domain = R_STD_ERROR_DOMAIN_STRING;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000020;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(21): /* std.string::string_error */
            r_error.domain = R_STD_ERROR_DOMAIN_STRING;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000021.kind;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(22): /* std.sync::barrier_error */
            r_error.domain = R_STD_ERROR_DOMAIN_THREADING;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000022;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(23): /* std.thread::thread_error */
            r_error.domain = R_STD_ERROR_DOMAIN_THREADING;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000023;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(24): /* std.time::duration_error */
            r_error.domain = R_STD_ERROR_DOMAIN_TIME;
            r_error.code = UINT32_C(256) + (uint32_t)r_outcome.r_payload.r_error_00000024;
            r_error.native_code = INT64_C(0);
            break;
        case UINT32_C(25): /* std.time::time_error */
            r_error.domain = R_STD_ERROR_DOMAIN_TIME;
            r_error.code = UINT32_C(0) + (uint32_t)r_outcome.r_payload.r_error_00000025.code;
            r_error.native_code = r_outcome.r_payload.r_error_00000025.native_code;
            break;
        default: /* Impossible for a well-formed generated error carrier. */
            r_runtime_panic(R_RUNTIME_PANIC_CONTRACT_VIOLATION,
                            (RRuntimeSourceSpan){UINT32_C(1), UINT32_C(24), UINT32_C(52)});
        }
        switch (r_error.domain) {
        case R_STD_ERROR_DOMAIN_ALLOCATION:
            r_domain = "allocation";
            r_domain_length = sizeof("allocation") - 1U;
            r_result = 112;
            break;
        case R_STD_ERROR_DOMAIN_ASYNC_RUNTIME:
            r_domain = "async_runtime";
            r_domain_length = sizeof("async_runtime") - 1U;
            r_result = 116;
            break;
        case R_STD_ERROR_DOMAIN_BYTES:
            r_domain = "bytes";
            r_domain_length = sizeof("bytes") - 1U;
            r_result = 117;
            break;
        case R_STD_ERROR_DOMAIN_STRING:
            r_domain = "string";
            r_domain_length = sizeof("string") - 1U;
            r_result = 117;
            break;
        case R_STD_ERROR_DOMAIN_CONVERSION:
            r_domain = "conversion";
            r_domain_length = sizeof("conversion") - 1U;
            r_result = 115;
            break;
        case R_STD_ERROR_DOMAIN_FORMAT:
            r_domain = "format";
            r_domain_length = sizeof("format") - 1U;
            r_result = 115;
            break;
        case R_STD_ERROR_DOMAIN_MATH:
            r_domain = "math";
            r_domain_length = sizeof("math") - 1U;
            r_result = 117;
            break;
        case R_STD_ERROR_DOMAIN_TIME:
            r_domain = "time";
            r_domain_length = sizeof("time") - 1U;
            r_result = 117;
            break;
        case R_STD_ERROR_DOMAIN_ENVIRONMENT:
            r_domain = "environment";
            r_domain_length = sizeof("environment") - 1U;
            r_result = 117;
            break;
        case R_STD_ERROR_DOMAIN_IO:
            r_domain = "io";
            r_domain_length = sizeof("io") - 1U;
            r_result = 113;
            break;
        case R_STD_ERROR_DOMAIN_FILESYSTEM:
            r_domain = "filesystem";
            r_domain_length = sizeof("filesystem") - 1U;
            r_result = 113;
            break;
        case R_STD_ERROR_DOMAIN_NETWORK:
            r_domain = "network";
            r_domain_length = sizeof("network") - 1U;
            r_result = 114;
            break;
        case R_STD_ERROR_DOMAIN_PROCESS:
            r_domain = "process";
            r_domain_length = sizeof("process") - 1U;
            r_result = 117;
            break;
        case R_STD_ERROR_DOMAIN_THREADING:
            r_domain = "threading";
            r_domain_length = sizeof("threading") - 1U;
            r_result = 116;
            break;
        case R_STD_ERROR_DOMAIN_C_ABI:
            r_domain = "c_abi";
            r_domain_length = sizeof("c_abi") - 1U;
            r_result = 117;
            break;
        default: /* Invalid enum representation. */
            r_runtime_panic(R_RUNTIME_PANIC_CONTRACT_VIOLATION,
                            (RRuntimeSourceSpan){UINT32_C(1), UINT32_C(24), UINT32_C(52)});
        }
        r_name = r_std_error_name(r_error);
        r_runtime_report_main_error(r_domain,
                                    r_domain_length,
                                    r_name.data,
                                    r_name.length,
                                    r_error.code,
                                    r_error.native_code);
    }
    /* All admitted payloads are Copy: consuming them has no drop side effect. */
    r_outcome.r_tag = UINT32_MAX;
    r_runtime_hosted_drain();
    r_runtime_hosted_drain();
    return r_runtime_hosted_finish(r_result);
}
