(mir version=1 core_revision="0.1.0-draft.105"
  (function name="test.codegen.value_types::character_literals" visibility=protected return=(struct "test.codegen.value_types"::"character_literal_set") state=definition
    (block bb0
      (local place=%local0 name="value" type=(struct "test.codegen.value_types"::"character_literal_set"))
      (%v0 = constant type=char value=65)
      (%v1 = constant type=char value=233)
      (%v2 = constant type=char value=128578)
      (%v3 = constant type=char value=92)
      (%v4 = constant type=char value=34)
      (%v5 = constant type=char value=39)
      (%v6 = constant type=char value=10)
      (%v7 = constant type=char value=13)
      (%v8 = constant type=char value=9)
      (%v9 = constant type=char value=0)
      (%v10 = constant type=char value=127)
      (%v11 = constant type=char value=128640)
      (%v12 = constant type=char value=1114111)
      (%v13 = aggregate type=(struct "test.codegen.value_types"::"character_literal_set") default=false fields=((2 %v0) (3 %v1) (4 %v2) (5 %v3) (6 %v4) (7 %v5) (8 %v6) (9 %v7) (10 %v8) (11 %v9) (12 %v10) (13 %v11) (14 %v12)))
      (store place=%local0 value=%v13)
      (%v14 = load place=%local0 type=(struct "test.codegen.value_types"::"character_literal_set"))
      (return value=%v14)
    )
  )
  (function name="test.codegen.value_types::checked_value" visibility=protected return=i32 state=definition
    (block bb0
      (parameter place=%arg0 name="fail" type=bool)
      (%v0 = load place=%arg0 type=bool)
      (%v1 = constant type=bool value=1)
      (%v2 = binary op="==" left=%v0 right=%v1 type=bool)
      (branch condition=%v2 then=bb1 else=bb2)
    )
    (block bb1
      (%v3 = constant type=i32 value=9)
      (%v4 = aggregate type=(struct "test.codegen.value_types"::"issue") default=false fields=((15 %v3)))
      (throw value=%v4 error=(struct "test.codegen.value_types"::"issue") propagate_tag=1)
    )
    (block bb2
      (%v5 = constant type=i32 value=4)
      (return value=%v5)
    )
  )
  (function name="test.codegen.value_types::contextual_scalar_literals" visibility=exported return=(struct "test.codegen.value_types"::"scalar_integers") state=definition
    (block bb0
      (local place=%local0 name="value" type=(struct "test.codegen.value_types"::"scalar_integers"))
      (%v0 = constant type=i8 value=128)
      (%v1 = constant type=i16 value=32768)
      (%v2 = constant type=i32 value=2147483648)
      (%v3 = constant type=i64 value=9223372036854775808)
      (%v4 = constant type=isize value=9223372036854775808)
      (%v5 = constant type=u8 value=255)
      (%v6 = constant type=u16 value=65535)
      (%v7 = constant type=u32 value=4294967295)
      (%v8 = constant type=u64 value=18446744073709551615)
      (%v9 = constant type=usize value=18446744073709551615)
      (%v10 = aggregate type=(struct "test.codegen.value_types"::"scalar_integers") default=false fields=((31 %v0) (32 %v1) (33 %v2) (34 %v3) (35 %v4) (36 %v5) (37 %v6) (38 %v7) (39 %v8) (40 %v9)))
      (store place=%local0 value=%v10)
      (%v11 = load place=%local0 type=(struct "test.codegen.value_types"::"scalar_integers"))
      (return value=%v11)
    )
  )
  (function name="test.codegen.value_types::default_scalar_values" visibility=exported return=(struct "test.codegen.value_types"::"scalar_defaults") state=definition
    (block bb0
      (local place=%local0 name="value" type=(struct "test.codegen.value_types"::"scalar_defaults"))
      (%v0 = constant type=bool value=0)
      (%v1 = constant type=i8 value=0)
      (%v2 = constant type=i16 value=0)
      (%v3 = constant type=i32 value=0)
      (%v4 = constant type=i64 value=0)
      (%v5 = constant type=isize value=0)
      (%v6 = constant type=u8 value=0)
      (%v7 = constant type=u16 value=0)
      (%v8 = constant type=u32 value=0)
      (%v9 = constant type=u64 value=0)
      (%v10 = constant type=usize value=0)
      (%v11 = constant type=f32 value=0)
      (%v12 = constant type=f64 value=0)
      (%v13 = constant type=char value=0)
      (%v14 = array type=(fixed_array u16 2) length=2 elements=())
      (%v15 = aggregate type=(struct "test.codegen.value_types"::"scalar_defaults") default=false fields=((16 %v0) (17 %v1) (18 %v2) (19 %v3) (20 %v4) (21 %v5) (22 %v6) (23 %v7) (24 %v8) (25 %v9) (26 %v10) (27 %v11) (28 %v12) (29 %v13) (30 %v14)))
      (store place=%local0 value=%v15)
      (%v16 = load place=%local0 type=(struct "test.codegen.value_types"::"scalar_defaults"))
      (return value=%v16)
    )
  )
  (function name="test.codegen.value_types::echo_bool" visibility=exported return=bool state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=bool)
      (local place=%local0 name="value" type=bool)
      (%v0 = load place=%arg0 type=bool)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=bool)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_char" visibility=exported return=char state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=char)
      (local place=%local0 name="value" type=char)
      (%v0 = load place=%arg0 type=char)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=char)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_f32" visibility=exported return=f32 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=f32)
      (local place=%local0 name="value" type=f32)
      (%v0 = load place=%arg0 type=f32)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=f32)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_f64" visibility=exported return=f64 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=f64)
      (local place=%local0 name="value" type=f64)
      (%v0 = load place=%arg0 type=f64)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=f64)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_i16" visibility=exported return=i16 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=i16)
      (local place=%local0 name="value" type=i16)
      (%v0 = load place=%arg0 type=i16)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=i16)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_i32" visibility=exported return=i32 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=i32)
      (local place=%local0 name="value" type=i32)
      (%v0 = load place=%arg0 type=i32)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=i32)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_i64" visibility=exported return=i64 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=i64)
      (local place=%local0 name="value" type=i64)
      (%v0 = load place=%arg0 type=i64)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=i64)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_i8" visibility=exported return=i8 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=i8)
      (local place=%local0 name="value" type=i8)
      (%v0 = load place=%arg0 type=i8)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=i8)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_isize" visibility=exported return=isize state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=isize)
      (local place=%local0 name="value" type=isize)
      (%v0 = load place=%arg0 type=isize)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=isize)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_scalar_option" visibility=exported return=(option i64) state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=(option i64))
      (local place=%local0 name="value" type=(option i64))
      (%v0 = load place=%arg0 type=(option i64))
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=(option i64))
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_scalar_result" visibility=exported return=(option u16) state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=(option u16))
      (local place=%local0 name="value" type=(option u16))
      (%v0 = load place=%arg0 type=(option u16))
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=(option u16))
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_scalar_tree" visibility=exported return=(struct "test.codegen.value_types"::"scalar_tree") state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=(struct "test.codegen.value_types"::"scalar_tree"))
      (local place=%local0 name="value" type=(struct "test.codegen.value_types"::"scalar_tree"))
      (%v0 = load place=%arg0 type=(struct "test.codegen.value_types"::"scalar_tree"))
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=(struct "test.codegen.value_types"::"scalar_tree"))
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_u16" visibility=exported return=u16 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=u16)
      (local place=%local0 name="value" type=u16)
      (%v0 = load place=%arg0 type=u16)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=u16)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_u32" visibility=exported return=u32 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=u32)
      (local place=%local0 name="value" type=u32)
      (%v0 = load place=%arg0 type=u32)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=u32)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_u64" visibility=exported return=u64 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=u64)
      (local place=%local0 name="value" type=u64)
      (%v0 = load place=%arg0 type=u64)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=u64)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_u8" visibility=exported return=u8 state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=u8)
      (local place=%local0 name="value" type=u8)
      (%v0 = load place=%arg0 type=u8)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=u8)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::echo_usize" visibility=exported return=usize state=definition
    (block bb0
      (parameter place=%arg0 name="input" type=usize)
      (local place=%local0 name="value" type=usize)
      (%v0 = load place=%arg0 type=usize)
      (store place=%local0 value=%v0)
      (%v1 = load place=%local0 type=usize)
      (return value=%v1)
    )
  )
  (function name="test.codegen.value_types::main" visibility=exported return=i32 state=definition
    (block bb0
      (local place=%local0 name="characters" type=(struct "test.codegen.value_types"::"character_literal_set"))
      (%v0 = constant type=char value=65)
      (%v1 = constant type=char value=233)
      (%v2 = constant type=char value=128578)
      (%v3 = constant type=char value=92)
      (%v4 = constant type=char value=34)
      (%v5 = constant type=char value=39)
      (%v6 = constant type=char value=10)
      (%v7 = constant type=char value=13)
      (%v8 = constant type=char value=9)
      (%v9 = constant type=char value=0)
      (%v10 = constant type=char value=127)
      (%v11 = constant type=char value=128640)
      (%v12 = constant type=char value=1114111)
      (%v13 = aggregate type=(struct "test.codegen.value_types"::"character_literal_set") default=false fields=((2 %v0) (3 %v1) (4 %v2) (5 %v3) (6 %v4) (7 %v5) (8 %v6) (9 %v7) (10 %v8) (11 %v9) (12 %v10) (13 %v11) (14 %v12)))
      (store place=%local0 value=%v13)
      (%v14 = load place=%local0 type=(struct "test.codegen.value_types"::"character_literal_set"))
      (discard value=%v14)
      (local place=%local1 name="values" type=(fixed_array i32 3))
      (%v15 = constant type=i32 value=1)
      (%v16 = constant type=i32 value=2)
      (%v17 = array type=(fixed_array i32 3) length=3 elements=(%v15 %v16))
      (store place=%local1 value=%v17)
      (local place=%local2 name="mutable_values" type=(slice i32) borrow_origin=%local1)
      (%v18 = slice base=%local1 length=3 type=(slice i32) borrow_origin=%local1)
      (store place=%local2 value=%v18 borrow_origin=%local1)
      (%v19 = constant type=usize value=1)
      (%v20 = index base=%local2 index=%v19 bound=dynamic checked=true readonly=false type=i32 borrow_origin=%local1)
      (%v21 = load place=%local2 type=i32 projection=%v20)
      (%v22 = constant type=i32 value=3)
      (%v23 = binary op="+" left=%v21 right=%v22 type=i32)
      (store place=%local2 value=%v23 projection=%v20)
      (local place=%local3 name="first" type=i32)
      (%v24 = constant type=usize value=0)
      (%v25 = index base=%local1 index=%v24 bound=3 checked=true readonly=false type=i32)
      (%v26 = load place=%local1 type=i32 projection=%v25)
      (store place=%local3 value=%v26)
      (local place=%local4 name="view" type=(const_slice i32) borrow_origin=%local1)
      (%v27 = slice base=%local1 length=3 type=(const_slice i32) borrow_origin=%local1)
      (store place=%local4 value=%v27 borrow_origin=%local1)
      (local place=%local5 name="selected" type=i32)
      (%v28 = load place=%local4 type=(const_slice i32) borrow_origin=%local1)
      (%v29 = constant type=u32 value=1)
      (%v30 = call callee="test.codegen.value_types::read_at" arguments=(%v28 %v29) call_bounded_borrows=(arg0) type=i32)
      (store place=%local5 value=%v30)
      (%v31 = load place=%local5 type=i32)
      (discard value=%v31)
      (local place=%local6 name="option_result" type=(option i32))
      (%v32 = load place=%local5 type=i32)
      (%v33 = constant type=i32 value=5)
      (%v34 = binary op="==" left=%v32 right=%v33 type=bool)
      (%v35 = call callee="test.codegen.value_types::propagate_option" arguments=(%v34) type=(option i32))
      (store place=%local6 value=%v35)
      (local place=%local7 name="option_value" type=i32)
      (%v36 = constant type=i32 value=0)
      (store place=%local7 value=%v36)
      (%v37 = load place=%local6 type=(option i32))
      (%v38 = variant_tag value=%v37 type=u32)
      (%v39 = constant type=u32 value=0)
      (%v40 = binary op="==" left=%v38 right=%v39 type=bool)
      (branch condition=%v40 then=bb4 else=bb3)
    )
    (block bb1
      (local place=%local12 name="failure" type=(struct "test.codegen.value_types"::"TestAssertionFailed"))
      (%v86 = effect_payload tag=0 type=(struct "test.codegen.value_types"::"TestAssertionFailed"))
      (store place=%local12 value=%v86)
      (%v87 = field base=%local12 member=1 type=i32)
      (%v88 = load place=%local12 type=i32 projection=%v87)
      (return value=%v88)
    )
    (block bb2
      (unreachable)
    )
    (block bb3
      (local place=%local8 name="value" type=(const_borrow i32) borrow_origin=%local6)
      (%v41 = variant_payload value=%v37 tag=1 type=(const_borrow i32) borrow_origin=%local6)
      (store place=%local8 value=%v41 borrow_origin=%local6)
      (%v42 = deref pointer=%local8 shared=true type=i32 borrow_origin=%local6)
      (%v43 = load place=%local8 type=i32 projection=%v42 borrow_origin=%local6)
      (store place=%local7 value=%v43)
      (jump target=bb5)
    )
    (block bb4
      (%v44 = constant type=i32 value=1)
      (%v45 = unary op="-" operand=%v44 type=i32)
      (store place=%local7 value=%v45)
      (jump target=bb5)
    )
    (block bb5
      (local place=%local9 name="explicit_ok" type=i32)
      (%v46 = load place=%local5 type=i32)
      (%v47 = constant type=i32 value=5)
      (%v48 = binary op="!=" left=%v46 right=%v47 type=bool)
      (%v49 = call callee="test.codegen.value_types::checked_value" arguments=(%v48) type=(carrier i32 (effects (struct "test.codegen.value_types"::"issue"))))
      (%v50 = effect_tag carrier=%v49 type=(carrier i32 (effects (struct "test.codegen.value_types"::"issue"))))
      (%v51 = constant type=u32 value=1)
      (%v52 = binary op="==" left=%v50 right=%v51 type=bool)
      (branch condition=%v52 then=bb8 else=bb9)
    )
    (block bb6
      (local place=%local11 name="error" type=(struct "test.codegen.value_types"::"issue"))
      (%v83 = effect_payload tag=0 type=(struct "test.codegen.value_types"::"issue"))
      (store place=%local11 value=%v83)
      (%v84 = field base=%local11 member=15 type=i32)
      (%v85 = load place=%local11 type=i32 projection=%v84)
      (return value=%v85)
    )
    (block bb7
      (unreachable)
    )
    (block bb8
      (%v53 = effect_payload carrier=%v49 tag=1 type=(struct "test.codegen.value_types"::"issue"))
      (throw value=%v53 error=(struct "test.codegen.value_types"::"issue") catch=bb6)
    )
    (block bb9
      (%v54 = effect_payload carrier=%v49 tag=0 type=i32)
      (store place=%local9 value=%v54)
      (%v55 = load place=%local9 type=i32)
      (%v56 = constant type=i32 value=4)
      (%v57 = binary op="!=" left=%v55 right=%v56 type=bool)
      (branch condition=%v57 then=bb10 else=bb11)
    )
    (block bb10
      (%v58 = constant type=i32 value=2)
      (%v59 = aggregate type=(struct "test.codegen.value_types"::"TestAssertionFailed") default=false fields=((1 %v58)))
      (throw value=%v59 error=(struct "test.codegen.value_types"::"TestAssertionFailed") catch=bb1)
    )
    (block bb11
      (local place=%local10 name="value" type=i32)
      (%v60 = load place=%local5 type=i32)
      (%v61 = constant type=i32 value=5)
      (%v62 = binary op="!=" left=%v60 right=%v61 type=bool)
      (%v63 = call callee="test.codegen.value_types::propagate_result" arguments=(%v62) type=(carrier i32 (effects (struct "test.codegen.value_types"::"issue"))))
      (%v64 = effect_tag carrier=%v63 type=(carrier i32 (effects (struct "test.codegen.value_types"::"issue"))))
      (%v65 = constant type=u32 value=1)
      (%v66 = binary op="==" left=%v64 right=%v65 type=bool)
      (branch condition=%v66 then=bb12 else=bb13)
    )
    (block bb12
      (%v67 = effect_payload carrier=%v63 tag=1 type=(struct "test.codegen.value_types"::"issue"))
      (throw value=%v67 error=(struct "test.codegen.value_types"::"issue") catch=bb6)
    )
    (block bb13
      (%v68 = effect_payload carrier=%v63 tag=0 type=i32)
      (store place=%local10 value=%v68)
      (%v69 = load place=%local5 type=i32)
      (%v70 = constant type=i32 value=5)
      (%v71 = binary op="==" left=%v69 right=%v70 type=bool)
      (branch condition=%v71 then=bb14 else=bb15)
    )
    (block bb14
      (%v72 = load place=%local3 type=i32)
      (%v73 = constant type=i32 value=1)
      (%v74 = binary op="==" left=%v72 right=%v73 type=bool)
      (branch condition=%v74 then=bb16 else=bb17)
    )
    (block bb15
      (%v81 = constant type=i32 value=1)
      (%v82 = aggregate type=(struct "test.codegen.value_types"::"TestAssertionFailed") default=false fields=((1 %v81)))
      (throw value=%v82 error=(struct "test.codegen.value_types"::"TestAssertionFailed") catch=bb1)
    )
    (block bb16
      (%v75 = load place=%local7 type=i32)
      (%v76 = constant type=i32 value=7)
      (%v77 = binary op="==" left=%v75 right=%v76 type=bool)
      (branch condition=%v77 then=bb18 else=bb19)
    )
    (block bb17
      (jump target=bb15)
    )
    (block bb18
      (%v78 = load place=%local10 type=i32)
      (%v79 = constant type=i32 value=4)
      (%v80 = binary op="-" left=%v78 right=%v79 type=i32)
      (return value=%v80)
    )
    (block bb19
      (jump target=bb17)
    )
  )
  (function name="test.codegen.value_types::maybe_value" visibility=protected return=(option i32) state=definition
    (block bb0
      (parameter place=%arg0 name="present" type=bool)
      (%v0 = load place=%arg0 type=bool)
      (%v1 = constant type=bool value=1)
      (%v2 = binary op="==" left=%v0 right=%v1 type=bool)
      (branch condition=%v2 then=bb1 else=bb2)
    )
    (block bb1
      (local place=%local0 name="value" type=(option i32))
      (%v3 = constant type=i32 value=7)
      (%v4 = variant type=(option i32) tag=1 payload=%v3)
      (store place=%local0 value=%v4)
      (%v5 = load place=%local0 type=(option i32))
      (return value=%v5)
    )
    (block bb2
      (local place=%local1 name="absent" type=(option i32))
      (%v6 = variant type=(option i32) tag=0)
      (store place=%local1 value=%v6)
      (%v7 = load place=%local1 type=(option i32))
      (return value=%v7)
    )
  )
  (function name="test.codegen.value_types::named_error" visibility=protected return=i32 state=definition
    (block bb0
      (local place=%local0 name="error" type=(struct "test.codegen.value_types"::"issue"))
      (%v0 = constant type=i32 value=12)
      (%v1 = aggregate type=(struct "test.codegen.value_types"::"issue") default=false fields=((15 %v0)))
      (store place=%local0 value=%v1)
      (%v2 = load place=%local0 type=(struct "test.codegen.value_types"::"issue"))
      (throw value=%v2 error=(struct "test.codegen.value_types"::"issue") propagate_tag=1)
    )
  )
  (function name="test.codegen.value_types::propagate_option" visibility=protected return=(option i32) state=definition
    (block bb0
      (parameter place=%arg0 name="present" type=bool)
      (local place=%local0 name="candidate" type=(option i32))
      (%v0 = load place=%arg0 type=bool)
      (%v1 = call callee="test.codegen.value_types::maybe_value" arguments=(%v0) type=(option i32))
      (store place=%local0 value=%v1)
      (%v2 = load place=%local0 type=(option i32))
      (%v3 = variant_tag value=%v2 type=u32)
      (%v4 = constant type=u32 value=0)
      (%v5 = binary op="==" left=%v3 right=%v4 type=bool)
      (branch condition=%v5 then=bb2 else=bb1)
    )
    (block bb1
      (local place=%local1 name="value" type=(const_borrow i32) borrow_origin=%local0)
      (%v6 = variant_payload value=%v2 tag=1 type=(const_borrow i32) borrow_origin=%local0)
      (store place=%local1 value=%v6 borrow_origin=%local0)
      (local place=%local2 name="success" type=(option i32))
      (%v7 = deref pointer=%local1 shared=true type=i32 borrow_origin=%local0)
      (%v8 = load place=%local1 type=i32 projection=%v7 borrow_origin=%local0)
      (%v9 = variant type=(option i32) tag=1 payload=%v8)
      (store place=%local2 value=%v9)
      (%v10 = load place=%local2 type=(option i32))
      (return value=%v10)
    )
    (block bb2
      (local place=%local3 name="absent" type=(option i32))
      (%v11 = variant type=(option i32) tag=0)
      (store place=%local3 value=%v11)
      (%v12 = load place=%local3 type=(option i32))
      (return value=%v12)
    )
    (block bb3
      (unreachable)
    )
  )
  (function name="test.codegen.value_types::propagate_result" visibility=protected return=i32 state=definition
    (block bb0
      (parameter place=%arg0 name="fail" type=bool)
      (%v0 = load place=%arg0 type=bool)
      (%v1 = call callee="test.codegen.value_types::void_status" arguments=(%v0) type=(carrier void (effects (struct "test.codegen.value_types"::"issue"))))
      (%v2 = effect_tag carrier=%v1 type=(carrier void (effects (struct "test.codegen.value_types"::"issue"))))
      (%v3 = constant type=u32 value=1)
      (%v4 = binary op="==" left=%v2 right=%v3 type=bool)
      (branch condition=%v4 then=bb1 else=bb2)
    )
    (block bb1
      (%v5 = effect_payload carrier=%v1 tag=1 type=(struct "test.codegen.value_types"::"issue"))
      (throw value=%v5 error=(struct "test.codegen.value_types"::"issue") propagate_tag=1)
    )
    (block bb2
      (local place=%local0 name="value" type=i32)
      (%v6 = load place=%arg0 type=bool)
      (%v7 = call callee="test.codegen.value_types::checked_value" arguments=(%v6) type=(carrier i32 (effects (struct "test.codegen.value_types"::"issue"))))
      (%v8 = effect_tag carrier=%v7 type=(carrier i32 (effects (struct "test.codegen.value_types"::"issue"))))
      (%v9 = constant type=u32 value=1)
      (%v10 = binary op="==" left=%v8 right=%v9 type=bool)
      (branch condition=%v10 then=bb3 else=bb4)
    )
    (block bb3
      (%v11 = effect_payload carrier=%v7 tag=1 type=(struct "test.codegen.value_types"::"issue"))
      (throw value=%v11 error=(struct "test.codegen.value_types"::"issue") propagate_tag=1)
    )
    (block bb4
      (%v12 = effect_payload carrier=%v7 tag=0 type=i32)
      (store place=%local0 value=%v12)
      (%v13 = load place=%local0 type=i32)
      (return value=%v13)
    )
  )
  (function name="test.codegen.value_types::read_at" visibility=protected return=i32 state=definition
    (block bb0
      (parameter place=%arg0 name="values" type=(const_slice i32))
      (parameter place=%arg1 name="index" type=u32)
      (%v0 = load place=%arg1 type=u32)
      (%v1 = cast operand=%v0 type=usize implicit borrow_origin=%arg1)
      (%v2 = index base=%arg0 index=%v1 bound=dynamic checked=true readonly=true type=i32)
      (%v3 = load place=%arg0 type=i32 projection=%v2)
      (return value=%v3)
    )
  )
  (function name="test.codegen.value_types::suffixed_scalar_literals" visibility=exported return=(struct "test.codegen.value_types"::"scalar_integers") state=definition
    (block bb0
      (local place=%local0 name="value" type=(struct "test.codegen.value_types"::"scalar_integers"))
      (%v0 = constant type=i8 value=128)
      (%v1 = constant type=i16 value=32768)
      (%v2 = constant type=i32 value=2147483648)
      (%v3 = constant type=i64 value=9223372036854775808)
      (%v4 = constant type=isize value=9223372036854775808)
      (%v5 = constant type=u8 value=255)
      (%v6 = constant type=u16 value=65535)
      (%v7 = constant type=u32 value=4294967295)
      (%v8 = constant type=u64 value=18446744073709551615)
      (%v9 = constant type=usize value=18446744073709551615)
      (%v10 = aggregate type=(struct "test.codegen.value_types"::"scalar_integers") default=false fields=((31 %v0) (32 %v1) (33 %v2) (34 %v3) (35 %v4) (36 %v5) (37 %v6) (38 %v7) (39 %v8) (40 %v9)))
      (store place=%local0 value=%v10)
      (%v11 = load place=%local0 type=(struct "test.codegen.value_types"::"scalar_integers"))
      (return value=%v11)
    )
  )
  (function name="test.codegen.value_types::void_status" visibility=protected return=void state=definition
    (block bb0
      (parameter place=%arg0 name="fail" type=bool)
      (%v0 = load place=%arg0 type=bool)
      (%v1 = constant type=bool value=1)
      (%v2 = binary op="==" left=%v0 right=%v1 type=bool)
      (branch condition=%v2 then=bb1 else=bb2)
    )
    (block bb1
      (%v3 = constant type=i32 value=13)
      (%v4 = aggregate type=(struct "test.codegen.value_types"::"issue") default=false fields=((15 %v3)))
      (throw value=%v4 error=(struct "test.codegen.value_types"::"issue") propagate_tag=1)
    )
    (block bb2
      (return)
    )
  )
)
