// Generated by tools/generate_standard_math_operations.py.
module audit.std_math_all_operations;

c_double probe_000(c_double value0) {
    return std.math::abs_c_double(value0);
}

c_float probe_001(c_float value0) {
    return std.math::abs_c_float(value0);
}

c_long_double probe_002(c_long_double value0) {
    return std.math::abs_c_long_double(value0);
}

f32 probe_003(f32 value0) {
    return std.math::abs_f32(value0);
}

f64 probe_004(f64 value0) {
    return std.math::abs_f64(value0);
}

c_double probe_005(c_double value0) throws std.math::math_error {
    return std.math::acos_c_double(value0);
}

c_float probe_006(c_float value0) throws std.math::math_error {
    return std.math::acos_c_float(value0);
}

c_long_double probe_007(c_long_double value0) throws std.math::math_error {
    return std.math::acos_c_long_double(value0);
}

f32 probe_008(f32 value0) throws std.math::math_error {
    return std.math::acos_f32(value0);
}

f64 probe_009(f64 value0) throws std.math::math_error {
    return std.math::acos_f64(value0);
}

c_double probe_010(c_double value0) throws std.math::math_error {
    return std.math::acosh_c_double(value0);
}

c_float probe_011(c_float value0) throws std.math::math_error {
    return std.math::acosh_c_float(value0);
}

c_long_double probe_012(c_long_double value0) throws std.math::math_error {
    return std.math::acosh_c_long_double(value0);
}

f32 probe_013(f32 value0) throws std.math::math_error {
    return std.math::acosh_f32(value0);
}

f64 probe_014(f64 value0) throws std.math::math_error {
    return std.math::acosh_f64(value0);
}

std.math::complex_f32 probe_015(std.math::complex_f32 value0, std.math::complex_f32 value1) {
    return std.math::add_complex_f32(value0, value1);
}

std.math::complex_f64 probe_016(std.math::complex_f64 value0, std.math::complex_f64 value1) {
    return std.math::add_complex_f64(value0, value1);
}

std.error::error probe_017(std.math::math_error value0) {
    return std.math::as_error(value0);
}

c_double probe_018(c_double value0) throws std.math::math_error {
    return std.math::asin_c_double(value0);
}

c_float probe_019(c_float value0) throws std.math::math_error {
    return std.math::asin_c_float(value0);
}

c_long_double probe_020(c_long_double value0) throws std.math::math_error {
    return std.math::asin_c_long_double(value0);
}

f32 probe_021(f32 value0) throws std.math::math_error {
    return std.math::asin_f32(value0);
}

f64 probe_022(f64 value0) throws std.math::math_error {
    return std.math::asin_f64(value0);
}

c_double probe_023(c_double value0) throws std.math::math_error {
    return std.math::asinh_c_double(value0);
}

c_float probe_024(c_float value0) throws std.math::math_error {
    return std.math::asinh_c_float(value0);
}

c_long_double probe_025(c_long_double value0) throws std.math::math_error {
    return std.math::asinh_c_long_double(value0);
}

f32 probe_026(f32 value0) throws std.math::math_error {
    return std.math::asinh_f32(value0);
}

f64 probe_027(f64 value0) throws std.math::math_error {
    return std.math::asinh_f64(value0);
}

c_double probe_028(c_double value0, c_double value1) throws std.math::math_error {
    return std.math::atan2_c_double(value0, value1);
}

c_float probe_029(c_float value0, c_float value1) throws std.math::math_error {
    return std.math::atan2_c_float(value0, value1);
}

c_long_double probe_030(c_long_double value0, c_long_double value1) throws std.math::math_error {
    return std.math::atan2_c_long_double(value0, value1);
}

f32 probe_031(f32 value0, f32 value1) throws std.math::math_error {
    return std.math::atan2_f32(value0, value1);
}

f64 probe_032(f64 value0, f64 value1) throws std.math::math_error {
    return std.math::atan2_f64(value0, value1);
}

c_double probe_033(c_double value0) throws std.math::math_error {
    return std.math::atan_c_double(value0);
}

c_float probe_034(c_float value0) throws std.math::math_error {
    return std.math::atan_c_float(value0);
}

c_long_double probe_035(c_long_double value0) throws std.math::math_error {
    return std.math::atan_c_long_double(value0);
}

f32 probe_036(f32 value0) throws std.math::math_error {
    return std.math::atan_f32(value0);
}

f64 probe_037(f64 value0) throws std.math::math_error {
    return std.math::atan_f64(value0);
}

c_double probe_038(c_double value0) throws std.math::math_error {
    return std.math::atanh_c_double(value0);
}

c_float probe_039(c_float value0) throws std.math::math_error {
    return std.math::atanh_c_float(value0);
}

c_long_double probe_040(c_long_double value0) throws std.math::math_error {
    return std.math::atanh_c_long_double(value0);
}

f32 probe_041(f32 value0) throws std.math::math_error {
    return std.math::atanh_f32(value0);
}

f64 probe_042(f64 value0) throws std.math::math_error {
    return std.math::atanh_f64(value0);
}

c_double probe_043(c_double value0) throws std.math::math_error {
    return std.math::cbrt_c_double(value0);
}

c_float probe_044(c_float value0) throws std.math::math_error {
    return std.math::cbrt_c_float(value0);
}

c_long_double probe_045(c_long_double value0) throws std.math::math_error {
    return std.math::cbrt_c_long_double(value0);
}

f32 probe_046(f32 value0) throws std.math::math_error {
    return std.math::cbrt_f32(value0);
}

f64 probe_047(f64 value0) throws std.math::math_error {
    return std.math::cbrt_f64(value0);
}

c_double probe_048(c_double value0) {
    return std.math::ceil_c_double(value0);
}

c_float probe_049(c_float value0) {
    return std.math::ceil_c_float(value0);
}

c_long_double probe_050(c_long_double value0) {
    return std.math::ceil_c_long_double(value0);
}

f32 probe_051(f32 value0) {
    return std.math::ceil_f32(value0);
}

f64 probe_052(f64 value0) {
    return std.math::ceil_f64(value0);
}

c_double probe_053(c_double value0, i32 value1) throws std.math::math_error {
    return std.math::compose_binary_c_double(value0, value1);
}

c_float probe_054(c_float value0, i32 value1) throws std.math::math_error {
    return std.math::compose_binary_c_float(value0, value1);
}

c_long_double probe_055(c_long_double value0, i32 value1) throws std.math::math_error {
    return std.math::compose_binary_c_long_double(value0, value1);
}

f32 probe_056(f32 value0, i32 value1) throws std.math::math_error {
    return std.math::compose_binary_f32(value0, value1);
}

f64 probe_057(f64 value0, i32 value1) throws std.math::math_error {
    return std.math::compose_binary_f64(value0, value1);
}

std.math::complex_f32 probe_058(std.math::complex_f32 value0) {
    return std.math::conjugate_complex_f32(value0);
}

std.math::complex_f64 probe_059(std.math::complex_f64 value0) {
    return std.math::conjugate_complex_f64(value0);
}

c_double probe_060(c_double value0, c_double value1) {
    return std.math::copy_sign_c_double(value0, value1);
}

c_float probe_061(c_float value0, c_float value1) {
    return std.math::copy_sign_c_float(value0, value1);
}

c_long_double probe_062(c_long_double value0, c_long_double value1) {
    return std.math::copy_sign_c_long_double(value0, value1);
}

f32 probe_063(f32 value0, f32 value1) {
    return std.math::copy_sign_f32(value0, value1);
}

f64 probe_064(f64 value0, f64 value1) {
    return std.math::copy_sign_f64(value0, value1);
}

c_double probe_065(c_double value0) throws std.math::math_error {
    return std.math::cos_c_double(value0);
}

c_float probe_066(c_float value0) throws std.math::math_error {
    return std.math::cos_c_float(value0);
}

c_long_double probe_067(c_long_double value0) throws std.math::math_error {
    return std.math::cos_c_long_double(value0);
}

std.math::complex_f32 probe_068(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::cos_complex_f32(value0);
}

std.math::complex_f64 probe_069(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::cos_complex_f64(value0);
}

f32 probe_070(f32 value0) throws std.math::math_error {
    return std.math::cos_f32(value0);
}

f64 probe_071(f64 value0) throws std.math::math_error {
    return std.math::cos_f64(value0);
}

c_double probe_072(c_double value0) throws std.math::math_error {
    return std.math::cosh_c_double(value0);
}

c_float probe_073(c_float value0) throws std.math::math_error {
    return std.math::cosh_c_float(value0);
}

c_long_double probe_074(c_long_double value0) throws std.math::math_error {
    return std.math::cosh_c_long_double(value0);
}

std.math::complex_f32 probe_075(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::cosh_complex_f32(value0);
}

std.math::complex_f64 probe_076(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::cosh_complex_f64(value0);
}

f32 probe_077(f32 value0) throws std.math::math_error {
    return std.math::cosh_f32(value0);
}

f64 probe_078(f64 value0) throws std.math::math_error {
    return std.math::cosh_f64(value0);
}

std.math::complex_f32 probe_079(std.math::complex_f32 value0, std.math::complex_f32 value1) throws std.math::math_error {
    return std.math::div_complex_f32(value0, value1);
}

std.math::complex_f64 probe_080(std.math::complex_f64 value0, std.math::complex_f64 value1) throws std.math::math_error {
    return std.math::div_complex_f64(value0, value1);
}

c_double probe_081(c_double value0) throws std.math::math_error {
    return std.math::erf_c_double(value0);
}

c_float probe_082(c_float value0) throws std.math::math_error {
    return std.math::erf_c_float(value0);
}

c_long_double probe_083(c_long_double value0) throws std.math::math_error {
    return std.math::erf_c_long_double(value0);
}

f32 probe_084(f32 value0) throws std.math::math_error {
    return std.math::erf_f32(value0);
}

f64 probe_085(f64 value0) throws std.math::math_error {
    return std.math::erf_f64(value0);
}

c_double probe_086(c_double value0) throws std.math::math_error {
    return std.math::erfc_c_double(value0);
}

c_float probe_087(c_float value0) throws std.math::math_error {
    return std.math::erfc_c_float(value0);
}

c_long_double probe_088(c_long_double value0) throws std.math::math_error {
    return std.math::erfc_c_long_double(value0);
}

f32 probe_089(f32 value0) throws std.math::math_error {
    return std.math::erfc_f32(value0);
}

f64 probe_090(f64 value0) throws std.math::math_error {
    return std.math::erfc_f64(value0);
}

c_double probe_091(c_double value0) throws std.math::math_error {
    return std.math::exp2_c_double(value0);
}

c_float probe_092(c_float value0) throws std.math::math_error {
    return std.math::exp2_c_float(value0);
}

c_long_double probe_093(c_long_double value0) throws std.math::math_error {
    return std.math::exp2_c_long_double(value0);
}

f32 probe_094(f32 value0) throws std.math::math_error {
    return std.math::exp2_f32(value0);
}

f64 probe_095(f64 value0) throws std.math::math_error {
    return std.math::exp2_f64(value0);
}

c_double probe_096(c_double value0) throws std.math::math_error {
    return std.math::exp_c_double(value0);
}

c_float probe_097(c_float value0) throws std.math::math_error {
    return std.math::exp_c_float(value0);
}

c_long_double probe_098(c_long_double value0) throws std.math::math_error {
    return std.math::exp_c_long_double(value0);
}

std.math::complex_f32 probe_099(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::exp_complex_f32(value0);
}

std.math::complex_f64 probe_100(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::exp_complex_f64(value0);
}

f32 probe_101(f32 value0) throws std.math::math_error {
    return std.math::exp_f32(value0);
}

f64 probe_102(f64 value0) throws std.math::math_error {
    return std.math::exp_f64(value0);
}

c_double probe_103(c_double value0) throws std.math::math_error {
    return std.math::expm1_c_double(value0);
}

c_float probe_104(c_float value0) throws std.math::math_error {
    return std.math::expm1_c_float(value0);
}

c_long_double probe_105(c_long_double value0) throws std.math::math_error {
    return std.math::expm1_c_long_double(value0);
}

f32 probe_106(f32 value0) throws std.math::math_error {
    return std.math::expm1_f32(value0);
}

f64 probe_107(f64 value0) throws std.math::math_error {
    return std.math::expm1_f64(value0);
}

c_double probe_108(c_double value0) {
    return std.math::floor_c_double(value0);
}

c_float probe_109(c_float value0) {
    return std.math::floor_c_float(value0);
}

c_long_double probe_110(c_long_double value0) {
    return std.math::floor_c_long_double(value0);
}

f32 probe_111(f32 value0) {
    return std.math::floor_f32(value0);
}

f64 probe_112(f64 value0) {
    return std.math::floor_f64(value0);
}

c_double probe_113(c_double value0) throws std.math::math_error {
    return std.math::gamma_c_double(value0);
}

c_float probe_114(c_float value0) throws std.math::math_error {
    return std.math::gamma_c_float(value0);
}

c_long_double probe_115(c_long_double value0) throws std.math::math_error {
    return std.math::gamma_c_long_double(value0);
}

f32 probe_116(f32 value0) throws std.math::math_error {
    return std.math::gamma_f32(value0);
}

f64 probe_117(f64 value0) throws std.math::math_error {
    return std.math::gamma_f64(value0);
}

c_double probe_118(c_double value0, c_double value1) throws std.math::math_error {
    return std.math::hypot_c_double(value0, value1);
}

c_float probe_119(c_float value0, c_float value1) throws std.math::math_error {
    return std.math::hypot_c_float(value0, value1);
}

c_long_double probe_120(c_long_double value0, c_long_double value1) throws std.math::math_error {
    return std.math::hypot_c_long_double(value0, value1);
}

f32 probe_121(f32 value0, f32 value1) throws std.math::math_error {
    return std.math::hypot_f32(value0, value1);
}

f64 probe_122(f64 value0, f64 value1) throws std.math::math_error {
    return std.math::hypot_f64(value0, value1);
}

bool probe_123(c_double value0) {
    return std.math::is_finite_c_double(value0);
}

bool probe_124(c_float value0) {
    return std.math::is_finite_c_float(value0);
}

bool probe_125(c_long_double value0) {
    return std.math::is_finite_c_long_double(value0);
}

bool probe_126(f32 value0) {
    return std.math::is_finite_f32(value0);
}

bool probe_127(f64 value0) {
    return std.math::is_finite_f64(value0);
}

bool probe_128(c_double value0) {
    return std.math::is_infinite_c_double(value0);
}

bool probe_129(c_float value0) {
    return std.math::is_infinite_c_float(value0);
}

bool probe_130(c_long_double value0) {
    return std.math::is_infinite_c_long_double(value0);
}

bool probe_131(f32 value0) {
    return std.math::is_infinite_f32(value0);
}

bool probe_132(f64 value0) {
    return std.math::is_infinite_f64(value0);
}

bool probe_133(c_double value0) {
    return std.math::is_nan_c_double(value0);
}

bool probe_134(c_float value0) {
    return std.math::is_nan_c_float(value0);
}

bool probe_135(c_long_double value0) {
    return std.math::is_nan_c_long_double(value0);
}

bool probe_136(f32 value0) {
    return std.math::is_nan_f32(value0);
}

bool probe_137(f64 value0) {
    return std.math::is_nan_f64(value0);
}

bool probe_138(c_double value0) {
    return std.math::is_normal_c_double(value0);
}

bool probe_139(c_float value0) {
    return std.math::is_normal_c_float(value0);
}

bool probe_140(c_long_double value0) {
    return std.math::is_normal_c_long_double(value0);
}

bool probe_141(f32 value0) {
    return std.math::is_normal_f32(value0);
}

bool probe_142(f64 value0) {
    return std.math::is_normal_f64(value0);
}

c_double probe_143(c_double value0) throws std.math::math_error {
    return std.math::log10_c_double(value0);
}

c_float probe_144(c_float value0) throws std.math::math_error {
    return std.math::log10_c_float(value0);
}

c_long_double probe_145(c_long_double value0) throws std.math::math_error {
    return std.math::log10_c_long_double(value0);
}

f32 probe_146(f32 value0) throws std.math::math_error {
    return std.math::log10_f32(value0);
}

f64 probe_147(f64 value0) throws std.math::math_error {
    return std.math::log10_f64(value0);
}

c_double probe_148(c_double value0) throws std.math::math_error {
    return std.math::log1p_c_double(value0);
}

c_float probe_149(c_float value0) throws std.math::math_error {
    return std.math::log1p_c_float(value0);
}

c_long_double probe_150(c_long_double value0) throws std.math::math_error {
    return std.math::log1p_c_long_double(value0);
}

f32 probe_151(f32 value0) throws std.math::math_error {
    return std.math::log1p_f32(value0);
}

f64 probe_152(f64 value0) throws std.math::math_error {
    return std.math::log1p_f64(value0);
}

c_double probe_153(c_double value0) throws std.math::math_error {
    return std.math::log2_c_double(value0);
}

c_float probe_154(c_float value0) throws std.math::math_error {
    return std.math::log2_c_float(value0);
}

c_long_double probe_155(c_long_double value0) throws std.math::math_error {
    return std.math::log2_c_long_double(value0);
}

f32 probe_156(f32 value0) throws std.math::math_error {
    return std.math::log2_f32(value0);
}

f64 probe_157(f64 value0) throws std.math::math_error {
    return std.math::log2_f64(value0);
}

c_double probe_158(c_double value0) throws std.math::math_error {
    return std.math::log_c_double(value0);
}

c_float probe_159(c_float value0) throws std.math::math_error {
    return std.math::log_c_float(value0);
}

c_long_double probe_160(c_long_double value0) throws std.math::math_error {
    return std.math::log_c_long_double(value0);
}

std.math::complex_f32 probe_161(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::log_complex_f32(value0);
}

std.math::complex_f64 probe_162(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::log_complex_f64(value0);
}

f32 probe_163(f32 value0) throws std.math::math_error {
    return std.math::log_f32(value0);
}

f64 probe_164(f64 value0) throws std.math::math_error {
    return std.math::log_f64(value0);
}

c_double probe_165(c_double value0) throws std.math::math_error {
    return std.math::log_gamma_c_double(value0);
}

c_float probe_166(c_float value0) throws std.math::math_error {
    return std.math::log_gamma_c_float(value0);
}

c_long_double probe_167(c_long_double value0) throws std.math::math_error {
    return std.math::log_gamma_c_long_double(value0);
}

f32 probe_168(f32 value0) throws std.math::math_error {
    return std.math::log_gamma_f32(value0);
}

f64 probe_169(f64 value0) throws std.math::math_error {
    return std.math::log_gamma_f64(value0);
}

f32 probe_170(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::magnitude_complex_f32(value0);
}

f64 probe_171(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::magnitude_complex_f64(value0);
}

c_double probe_172(c_double value0, c_double value1) {
    return std.math::max_c_double(value0, value1);
}

c_float probe_173(c_float value0, c_float value1) {
    return std.math::max_c_float(value0, value1);
}

c_long_double probe_174(c_long_double value0, c_long_double value1) {
    return std.math::max_c_long_double(value0, value1);
}

f32 probe_175(f32 value0, f32 value1) {
    return std.math::max_f32(value0, value1);
}

f64 probe_176(f64 value0, f64 value1) {
    return std.math::max_f64(value0, value1);
}

c_double probe_177(c_double value0, c_double value1) {
    return std.math::min_c_double(value0, value1);
}

c_float probe_178(c_float value0, c_float value1) {
    return std.math::min_c_float(value0, value1);
}

c_long_double probe_179(c_long_double value0, c_long_double value1) {
    return std.math::min_c_long_double(value0, value1);
}

f32 probe_180(f32 value0, f32 value1) {
    return std.math::min_f32(value0, value1);
}

f64 probe_181(f64 value0, f64 value1) {
    return std.math::min_f64(value0, value1);
}

std.math::complex_f32 probe_182(std.math::complex_f32 value0, std.math::complex_f32 value1) {
    return std.math::mul_complex_f32(value0, value1);
}

std.math::complex_f64 probe_183(std.math::complex_f64 value0, std.math::complex_f64 value1) {
    return std.math::mul_complex_f64(value0, value1);
}

c_double probe_184(c_double value0, c_double value1) {
    return std.math::next_after_c_double(value0, value1);
}

c_float probe_185(c_float value0, c_float value1) {
    return std.math::next_after_c_float(value0, value1);
}

c_long_double probe_186(c_long_double value0, c_long_double value1) {
    return std.math::next_after_c_long_double(value0, value1);
}

f32 probe_187(f32 value0, f32 value1) {
    return std.math::next_after_f32(value0, value1);
}

f64 probe_188(f64 value0, f64 value1) {
    return std.math::next_after_f64(value0, value1);
}

f32 probe_189(std.math::complex_f32 value0) {
    return std.math::phase_complex_f32(value0);
}

f64 probe_190(std.math::complex_f64 value0) {
    return std.math::phase_complex_f64(value0);
}

c_double probe_191(c_double value0, c_double value1) throws std.math::math_error {
    return std.math::pow_c_double(value0, value1);
}

c_float probe_192(c_float value0, c_float value1) throws std.math::math_error {
    return std.math::pow_c_float(value0, value1);
}

c_long_double probe_193(c_long_double value0, c_long_double value1) throws std.math::math_error {
    return std.math::pow_c_long_double(value0, value1);
}

std.math::complex_f32 probe_194(std.math::complex_f32 value0, std.math::complex_f32 value1) throws std.math::math_error {
    return std.math::pow_complex_f32(value0, value1);
}

std.math::complex_f64 probe_195(std.math::complex_f64 value0, std.math::complex_f64 value1) throws std.math::math_error {
    return std.math::pow_complex_f64(value0, value1);
}

f32 probe_196(f32 value0, f32 value1) throws std.math::math_error {
    return std.math::pow_f32(value0, value1);
}

f64 probe_197(f64 value0, f64 value1) throws std.math::math_error {
    return std.math::pow_f64(value0, value1);
}

c_double probe_198(c_double value0, c_double value1) throws std.math::math_error {
    return std.math::remainder_c_double(value0, value1);
}

c_float probe_199(c_float value0, c_float value1) throws std.math::math_error {
    return std.math::remainder_c_float(value0, value1);
}

c_long_double probe_200(c_long_double value0, c_long_double value1) throws std.math::math_error {
    return std.math::remainder_c_long_double(value0, value1);
}

f32 probe_201(f32 value0, f32 value1) throws std.math::math_error {
    return std.math::remainder_f32(value0, value1);
}

f64 probe_202(f64 value0, f64 value1) throws std.math::math_error {
    return std.math::remainder_f64(value0, value1);
}

c_double probe_203(c_double value0) {
    return std.math::round_c_double(value0);
}

c_float probe_204(c_float value0) {
    return std.math::round_c_float(value0);
}

c_long_double probe_205(c_long_double value0) {
    return std.math::round_c_long_double(value0);
}

f32 probe_206(f32 value0) {
    return std.math::round_f32(value0);
}

f64 probe_207(f64 value0) {
    return std.math::round_f64(value0);
}

bool probe_208(c_double value0) {
    return std.math::sign_bit_c_double(value0);
}

bool probe_209(c_float value0) {
    return std.math::sign_bit_c_float(value0);
}

bool probe_210(c_long_double value0) {
    return std.math::sign_bit_c_long_double(value0);
}

bool probe_211(f32 value0) {
    return std.math::sign_bit_f32(value0);
}

bool probe_212(f64 value0) {
    return std.math::sign_bit_f64(value0);
}

c_double probe_213(c_double value0) throws std.math::math_error {
    return std.math::sin_c_double(value0);
}

c_float probe_214(c_float value0) throws std.math::math_error {
    return std.math::sin_c_float(value0);
}

c_long_double probe_215(c_long_double value0) throws std.math::math_error {
    return std.math::sin_c_long_double(value0);
}

std.math::complex_f32 probe_216(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::sin_complex_f32(value0);
}

std.math::complex_f64 probe_217(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::sin_complex_f64(value0);
}

f32 probe_218(f32 value0) throws std.math::math_error {
    return std.math::sin_f32(value0);
}

f64 probe_219(f64 value0) throws std.math::math_error {
    return std.math::sin_f64(value0);
}

c_double probe_220(c_double value0) throws std.math::math_error {
    return std.math::sinh_c_double(value0);
}

c_float probe_221(c_float value0) throws std.math::math_error {
    return std.math::sinh_c_float(value0);
}

c_long_double probe_222(c_long_double value0) throws std.math::math_error {
    return std.math::sinh_c_long_double(value0);
}

std.math::complex_f32 probe_223(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::sinh_complex_f32(value0);
}

std.math::complex_f64 probe_224(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::sinh_complex_f64(value0);
}

f32 probe_225(f32 value0) throws std.math::math_error {
    return std.math::sinh_f32(value0);
}

f64 probe_226(f64 value0) throws std.math::math_error {
    return std.math::sinh_f64(value0);
}

std.math::binary_parts_c_double probe_227(c_double value0) {
    return std.math::split_binary_c_double(value0);
}

std.math::binary_parts_c_float probe_228(c_float value0) {
    return std.math::split_binary_c_float(value0);
}

std.math::binary_parts_c_long_double probe_229(c_long_double value0) {
    return std.math::split_binary_c_long_double(value0);
}

std.math::binary_parts_f32 probe_230(f32 value0) {
    return std.math::split_binary_f32(value0);
}

std.math::binary_parts_f64 probe_231(f64 value0) {
    return std.math::split_binary_f64(value0);
}

std.math::fraction_parts_c_double probe_232(c_double value0) {
    return std.math::split_fraction_c_double(value0);
}

std.math::fraction_parts_c_float probe_233(c_float value0) {
    return std.math::split_fraction_c_float(value0);
}

std.math::fraction_parts_c_long_double probe_234(c_long_double value0) {
    return std.math::split_fraction_c_long_double(value0);
}

std.math::fraction_parts_f32 probe_235(f32 value0) {
    return std.math::split_fraction_f32(value0);
}

std.math::fraction_parts_f64 probe_236(f64 value0) {
    return std.math::split_fraction_f64(value0);
}

c_double probe_237(c_double value0) throws std.math::math_error {
    return std.math::sqrt_c_double(value0);
}

c_float probe_238(c_float value0) throws std.math::math_error {
    return std.math::sqrt_c_float(value0);
}

c_long_double probe_239(c_long_double value0) throws std.math::math_error {
    return std.math::sqrt_c_long_double(value0);
}

std.math::complex_f32 probe_240(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::sqrt_complex_f32(value0);
}

std.math::complex_f64 probe_241(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::sqrt_complex_f64(value0);
}

f32 probe_242(f32 value0) throws std.math::math_error {
    return std.math::sqrt_f32(value0);
}

f64 probe_243(f64 value0) throws std.math::math_error {
    return std.math::sqrt_f64(value0);
}

std.math::complex_f32 probe_244(std.math::complex_f32 value0, std.math::complex_f32 value1) {
    return std.math::sub_complex_f32(value0, value1);
}

std.math::complex_f64 probe_245(std.math::complex_f64 value0, std.math::complex_f64 value1) {
    return std.math::sub_complex_f64(value0, value1);
}

c_double probe_246(c_double value0) throws std.math::math_error {
    return std.math::tan_c_double(value0);
}

c_float probe_247(c_float value0) throws std.math::math_error {
    return std.math::tan_c_float(value0);
}

c_long_double probe_248(c_long_double value0) throws std.math::math_error {
    return std.math::tan_c_long_double(value0);
}

std.math::complex_f32 probe_249(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::tan_complex_f32(value0);
}

std.math::complex_f64 probe_250(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::tan_complex_f64(value0);
}

f32 probe_251(f32 value0) throws std.math::math_error {
    return std.math::tan_f32(value0);
}

f64 probe_252(f64 value0) throws std.math::math_error {
    return std.math::tan_f64(value0);
}

c_double probe_253(c_double value0) throws std.math::math_error {
    return std.math::tanh_c_double(value0);
}

c_float probe_254(c_float value0) throws std.math::math_error {
    return std.math::tanh_c_float(value0);
}

c_long_double probe_255(c_long_double value0) throws std.math::math_error {
    return std.math::tanh_c_long_double(value0);
}

std.math::complex_f32 probe_256(std.math::complex_f32 value0) throws std.math::math_error {
    return std.math::tanh_complex_f32(value0);
}

std.math::complex_f64 probe_257(std.math::complex_f64 value0) throws std.math::math_error {
    return std.math::tanh_complex_f64(value0);
}

f32 probe_258(f32 value0) throws std.math::math_error {
    return std.math::tanh_f32(value0);
}

f64 probe_259(f64 value0) throws std.math::math_error {
    return std.math::tanh_f64(value0);
}

c_double probe_260(c_double value0) {
    return std.math::trunc_c_double(value0);
}

c_float probe_261(c_float value0) {
    return std.math::trunc_c_float(value0);
}

c_long_double probe_262(c_long_double value0) {
    return std.math::trunc_c_long_double(value0);
}

f32 probe_263(f32 value0) {
    return std.math::trunc_f32(value0);
}

f64 probe_264(f64 value0) {
    return std.math::trunc_f64(value0);
}

i32 main() {
    return 0;
}
