/* Generated by tools/generate_runtime_surface.py; do not edit. */
/* The static inline functions of the runtime and library headers as external
   functions the LLVM backend can call (B4 of the LLVM transition). */

#include "r_core.h"
#include "r_runtime_0_1.h"
#include "r_runtime_arc.h"
#include "r_runtime_array.h"
#include "r_runtime_dict.h"
#include "r_runtime_drop.h"
#include "r_runtime_list.h"
#include "r_runtime_own.h"
#include "r_runtime_rc.h"
#include "r_runtime_target_abi.h"
#include "r_std_alloc.h"
#include "r_std_arc.h"
#include "r_std_array.h"
#include "r_std_async.h"
#include "r_std_bits.h"
#include "r_std_bytes.h"
#include "r_std_c.h"
#include "r_std_convert.h"
#include "r_std_dict.h"
#include "r_std_env.h"
#include "r_std_error.h"
#include "r_std_error_types.h"
#include "r_std_format.h"
#include "r_std_fs.h"
#include "r_std_hash.h"
#include "r_std_io.h"
#include "r_std_json.h"
#include "r_std_json_reader.h"
#include "r_std_list.h"
#include "r_std_math.h"
#include "r_std_net.h"
#include "r_std_process.h"
#include "r_std_random.h"
#include "r_std_rc.h"
#include "r_std_secret.h"
#include "r_std_signal.h"
#include "r_std_string.h"
#include "r_std_sync.h"
#include "r_std_test.h"
#include "r_std_thread.h"
#include "r_std_time.h"
#include "r_std_utf8.h"

bool r_shim_r_runtime_unwinding(void);
void r_shim_r_std_arc_try_unwrap_result_destroy(RStdArcTryUnwrapResult * a0);
void r_shim_r_std_async_broadcast_destroy(RStdAsyncBroadcast * a0);
void r_shim_r_std_async_broadcast_move_initialize(RStdAsyncBroadcast * a0, RStdAsyncBroadcast * a1);
void r_shim_r_std_async_broadcast_receiver_destroy(RStdAsyncBroadcastReceiver * a0);
void r_shim_r_std_async_broadcast_receiver_move_initialize(RStdAsyncBroadcastReceiver * a0, RStdAsyncBroadcastReceiver * a1);
void r_shim_r_std_async_mutex_destroy(RStdAsyncMutex * a0);
void r_shim_r_std_async_mutex_guard_destroy(RStdAsyncMutexGuard * a0);
void r_shim_r_std_async_mutex_guard_move_initialize(RStdAsyncMutexGuard * a0, RStdAsyncMutexGuard * a1);
void r_shim_r_std_async_mutex_move_initialize(RStdAsyncMutex * a0, RStdAsyncMutex * a1);
void r_shim_r_std_async_notify_destroy(RStdAsyncNotify * a0);
void r_shim_r_std_async_notify_move_initialize(RStdAsyncNotify * a0, RStdAsyncNotify * a1);
void r_shim_r_std_async_rw_lock_destroy(RStdAsyncRwLock * a0);
void r_shim_r_std_async_rw_lock_move_initialize(RStdAsyncRwLock * a0, RStdAsyncRwLock * a1);
void r_shim_r_std_async_rw_read_guard_destroy(RStdAsyncRwReadGuard * a0);
void r_shim_r_std_async_rw_read_guard_move_initialize(RStdAsyncRwReadGuard * a0, RStdAsyncRwReadGuard * a1);
void r_shim_r_std_async_rw_write_guard_destroy(RStdAsyncRwWriteGuard * a0);
void r_shim_r_std_async_rw_write_guard_move_initialize(RStdAsyncRwWriteGuard * a0, RStdAsyncRwWriteGuard * a1);
void r_shim_r_std_async_semaphore_destroy(RStdAsyncSemaphore * a0);
void r_shim_r_std_async_semaphore_move_initialize(RStdAsyncSemaphore * a0, RStdAsyncSemaphore * a1);
void r_shim_r_std_async_semaphore_permit_destroy(RStdAsyncSemaphorePermit * a0);
void r_shim_r_std_async_semaphore_permit_move_initialize(RStdAsyncSemaphorePermit * a0, RStdAsyncSemaphorePermit * a1);
void r_shim_r_std_c_handle_destroy(RStdCHandle * a0);
void r_shim_r_std_c_handle_move_initialize(RStdCHandle * a0, RStdCHandle * a1);
void r_shim_r_std_c_string_destroy(RStdCString * a0);
void r_shim_r_std_c_string_move_initialize(RStdCString * a0, RStdCString * a1);
void r_shim_r_std_c_thread_attachment_destroy(RStdCThreadAttachment * a0);
void r_shim_r_std_c_thread_attachment_move_initialize(RStdCThreadAttachment * a0, RStdCThreadAttachment * a1);
void r_shim_r_std_format_builder_destroy(RStdFormatBuilder * a0);
void r_shim_r_std_format_builder_move_initialize(RStdFormatBuilder * a0, RStdFormatBuilder * a1);
void r_shim_r_std_fs_directory_destroy(RStdFsDirectory * a0);
void r_shim_r_std_fs_directory_entry_destroy(RStdFsDirectoryEntry * a0);
void r_shim_r_std_fs_directory_entry_move_initialize(RStdFsDirectoryEntry * a0, RStdFsDirectoryEntry * a1);
void r_shim_r_std_fs_directory_iter_destroy(RStdFsDirectoryIter * a0);
void r_shim_r_std_fs_directory_iter_move_initialize(RStdFsDirectoryIter * a0, RStdFsDirectoryIter * a1);
void r_shim_r_std_fs_directory_move_initialize(RStdFsDirectory * a0, RStdFsDirectory * a1);
void r_shim_r_std_fs_directory_next_result_destroy(RStdFsDirectoryNextResult * a0);
void r_shim_r_std_fs_directory_next_result_move_initialize(RStdFsDirectoryNextResult * a0, RStdFsDirectoryNextResult * a1);
void r_shim_r_std_fs_file_destroy(RStdFsFile * a0);
void r_shim_r_std_fs_file_move_initialize(RStdFsFile * a0, RStdFsFile * a1);
void r_shim_r_std_fs_path_destroy(RStdFsPath * a0);
void r_shim_r_std_fs_path_move_initialize(RStdFsPath * a0, RStdFsPath * a1);
void r_shim_r_std_fs_write_file_result_destroy(RStdFsWriteFileResult * a0);
void r_shim_r_std_fs_write_file_result_move_initialize(RStdFsWriteFileResult * a0, RStdFsWriteFileResult * a1);
void r_shim_r_std_io_input_destroy(RStdIoInput * a0);
void r_shim_r_std_io_input_move_initialize(RStdIoInput * a0, RStdIoInput * a1);
void r_shim_r_std_io_output_destroy(RStdIoOutput * a0);
void r_shim_r_std_io_output_move_initialize(RStdIoOutput * a0, RStdIoOutput * a1);
void r_shim_r_std_io_read_result_destroy(RStdIoReadResult * a0);
void r_shim_r_std_io_read_result_move_initialize(RStdIoReadResult * a0, RStdIoReadResult * a1);
void r_shim_r_std_io_shared_write_result_destroy(RStdIoSharedWriteResult * a0);
void r_shim_r_std_io_shared_write_result_move_initialize(RStdIoSharedWriteResult * a0, RStdIoSharedWriteResult * a1);
void r_shim_r_std_io_write_all_result_destroy(RStdIoWriteAllResult * a0);
void r_shim_r_std_io_write_all_result_move_initialize(RStdIoWriteAllResult * a0, RStdIoWriteAllResult * a1);
void r_shim_r_std_io_write_result_destroy(RStdIoWriteResult * a0);
void r_shim_r_std_io_write_result_move_initialize(RStdIoWriteResult * a0, RStdIoWriteResult * a1);
void r_shim_r_std_json_decoder_destroy(RStdJsonDecoder * a0);
void r_shim_r_std_json_decoder_move_initialize(RStdJsonDecoder * a0, RStdJsonDecoder * a1);
void r_shim_r_std_json_detached_destroy(RStdJsonDetached * a0);
void r_shim_r_std_json_detached_move_initialize(RStdJsonDetached * a0, RStdJsonDetached * a1);
void r_shim_r_std_json_error_destroy(RStdJsonError * a0);
void r_shim_r_std_json_error_move_initialize(RStdJsonError * a0, RStdJsonError * a1);
void r_shim_r_std_json_number_destroy(RStdJsonNumber * a0);
void r_shim_r_std_json_number_move_initialize(RStdJsonNumber * a0, RStdJsonNumber * a1);
void r_shim_r_std_json_reader_destroy(RStdJsonReader * a0);
void r_shim_r_std_json_reader_move_initialize(RStdJsonReader * a0, RStdJsonReader * a1);
void r_shim_r_std_json_value_destroy(RStdJsonValue * a0);
void r_shim_r_std_json_value_move_initialize(RStdJsonValue * a0, RStdJsonValue * a1);
void r_shim_r_std_net_tcp_connection_destroy(RStdNetTcpConnection * a0);
void r_shim_r_std_net_tcp_connection_move_initialize(RStdNetTcpConnection * a0, RStdNetTcpConnection * a1);
void r_shim_r_std_net_tcp_listener_destroy(RStdNetTcpListener * a0);
void r_shim_r_std_net_tcp_listener_move_initialize(RStdNetTcpListener * a0, RStdNetTcpListener * a1);
void r_shim_r_std_net_tcp_read_result_destroy(RStdNetTcpReadResult * a0);
void r_shim_r_std_net_tcp_read_result_move_initialize(RStdNetTcpReadResult * a0, RStdNetTcpReadResult * a1);
void r_shim_r_std_net_tcp_stream_destroy(RStdNetTcpStream * a0);
void r_shim_r_std_net_tcp_stream_move_initialize(RStdNetTcpStream * a0, RStdNetTcpStream * a1);
void r_shim_r_std_net_tcp_write_all_result_destroy(RStdNetTcpWriteAllResult * a0);
void r_shim_r_std_net_tcp_write_all_result_move_initialize(RStdNetTcpWriteAllResult * a0, RStdNetTcpWriteAllResult * a1);
void r_shim_r_std_net_tcp_write_result_destroy(RStdNetTcpWriteResult * a0);
void r_shim_r_std_net_tcp_write_result_move_initialize(RStdNetTcpWriteResult * a0, RStdNetTcpWriteResult * a1);
void r_shim_r_std_net_udp_receive_result_destroy(RStdNetUdpReceiveResult * a0);
void r_shim_r_std_net_udp_receive_result_move_initialize(RStdNetUdpReceiveResult * a0, RStdNetUdpReceiveResult * a1);
void r_shim_r_std_net_udp_send_result_destroy(RStdNetUdpSendResult * a0);
void r_shim_r_std_net_udp_send_result_move_initialize(RStdNetUdpSendResult * a0, RStdNetUdpSendResult * a1);
void r_shim_r_std_net_udp_socket_destroy(RStdNetUdpSocket * a0);
void r_shim_r_std_net_udp_socket_move_initialize(RStdNetUdpSocket * a0, RStdNetUdpSocket * a1);
void r_shim_r_std_net_unix_datagram_destroy(RStdNetUnixDatagram * a0);
void r_shim_r_std_net_unix_datagram_move_initialize(RStdNetUnixDatagram * a0, RStdNetUnixDatagram * a1);
void r_shim_r_std_net_unix_listener_destroy(RStdNetUnixListener * a0);
void r_shim_r_std_net_unix_listener_move_initialize(RStdNetUnixListener * a0, RStdNetUnixListener * a1);
void r_shim_r_std_net_unix_stream_destroy(RStdNetUnixStream * a0);
void r_shim_r_std_net_unix_stream_move_initialize(RStdNetUnixStream * a0, RStdNetUnixStream * a1);
void r_shim_r_std_process_child_destroy(RStdProcessChild * a0);
void r_shim_r_std_process_child_move_initialize(RStdProcessChild * a0, RStdProcessChild * a1);
void r_shim_r_std_process_command_destroy(RStdProcessCommand * a0);
void r_shim_r_std_process_command_move_initialize(RStdProcessCommand * a0, RStdProcessCommand * a1);
void r_shim_r_std_process_spawn_result_destroy(RStdProcessSpawnResult * a0);
void r_shim_r_std_process_spawn_result_move_initialize(RStdProcessSpawnResult * a0, RStdProcessSpawnResult * a1);
void r_shim_r_std_process_wait_result_destroy(RStdProcessWaitResult * a0);
void r_shim_r_std_process_wait_result_move_initialize(RStdProcessWaitResult * a0, RStdProcessWaitResult * a1);
void r_shim_r_std_rc_try_unwrap_result_destroy(RStdRcTryUnwrapResult * a0);
void r_shim_r_std_secret_buffer_destroy(RStdSecretBuffer * a0);
void r_shim_r_std_secret_buffer_move_initialize(RStdSecretBuffer * a0, RStdSecretBuffer * a1);
void r_shim_r_std_secret_erase(void * a0, size_t a1);
void r_shim_r_std_signal_listener_destroy(RStdSignalListener * a0);
void r_shim_r_std_signal_listener_move_initialize(RStdSignalListener * a0, RStdSignalListener * a1);
void r_shim_r_std_string_destroy(RStdString * a0);
void r_shim_r_std_string_from_bytes_result_destroy(RStdStringFromBytesResult * a0);
void r_shim_r_std_string_from_bytes_result_move_initialize(RStdStringFromBytesResult * a0, RStdStringFromBytesResult * a1);
void r_shim_r_std_string_move_initialize(RStdString * a0, RStdString * a1);
void r_shim_r_std_sync_barrier_destroy(RStdSyncBarrier * a0);
void r_shim_r_std_sync_barrier_move_initialize(RStdSyncBarrier * a0, RStdSyncBarrier * a1);
void r_shim_r_std_sync_channel_destroy(RStdSyncChannel * a0);
void r_shim_r_std_sync_channel_move_initialize(RStdSyncChannel * a0, RStdSyncChannel * a1);
void r_shim_r_std_sync_condvar_destroy(RStdSyncCondvar * a0);
void r_shim_r_std_sync_condvar_move_initialize(RStdSyncCondvar * a0, RStdSyncCondvar * a1);
void r_shim_r_std_sync_lock_result_destroy(RStdSyncLockResult * a0);
void r_shim_r_std_sync_mutex_destroy(RStdSyncMutex * a0);
void r_shim_r_std_sync_mutex_guard_destroy(RStdSyncMutexGuard * a0);
void r_shim_r_std_sync_once_destroy(RStdSyncOnce * a0);
void r_shim_r_std_sync_once_lock_destroy(RStdSyncOnceLock * a0);
void r_shim_r_std_sync_once_move_initialize(RStdSyncOnce * a0, RStdSyncOnce * a1);
void r_shim_r_std_sync_permit_destroy(RStdSyncPermit * a0);
void r_shim_r_std_sync_permit_move_initialize(RStdSyncPermit * a0, RStdSyncPermit * a1);
void r_shim_r_std_sync_read_lock_result_destroy(RStdSyncReadLockResult * a0);
void r_shim_r_std_sync_receiver_destroy(RStdSyncReceiver * a0);
void r_shim_r_std_sync_receiver_move_initialize(RStdSyncReceiver * a0, RStdSyncReceiver * a1);
void r_shim_r_std_sync_rw_lock_destroy(RStdSyncRwLock * a0);
void r_shim_r_std_sync_rw_read_guard_destroy(RStdSyncRwReadGuard * a0);
void r_shim_r_std_sync_rw_write_guard_destroy(RStdSyncRwWriteGuard * a0);
void r_shim_r_std_sync_sender_destroy(RStdSyncSender * a0);
void r_shim_r_std_sync_sender_move_initialize(RStdSyncSender * a0, RStdSyncSender * a1);
void r_shim_r_std_sync_sync_channel_destroy(RStdSyncSyncChannel * a0);
void r_shim_r_std_sync_sync_channel_move_initialize(RStdSyncSyncChannel * a0, RStdSyncSyncChannel * a1);
void r_shim_r_std_sync_sync_sender_destroy(RStdSyncSyncSender * a0);
void r_shim_r_std_sync_sync_sender_move_initialize(RStdSyncSyncSender * a0, RStdSyncSyncSender * a1);
void r_shim_r_std_sync_try_lock_result_destroy(RStdSyncTryLockResult * a0);
void r_shim_r_std_sync_try_read_lock_result_destroy(RStdSyncTryReadLockResult * a0);
void r_shim_r_std_sync_try_write_lock_result_destroy(RStdSyncTryWriteLockResult * a0);
void r_shim_r_std_sync_write_lock_result_destroy(RStdSyncWriteLockResult * a0);
void r_shim_r_std_thread_join_handle_destroy(RStdThreadJoinHandle * a0);
void r_shim_r_std_thread_join_result_destroy(RStdThreadJoinResult * a0);
void r_shim_r_std_thread_panic_report_destroy(RStdThreadPanicReport * a0);
void r_shim_r_std_thread_panic_report_move_initialize(RStdThreadPanicReport * a0, RStdThreadPanicReport * a1);
void r_shim_r_std_thread_scoped_join_handle_destroy(RStdThreadScopedJoinHandle * a0);
void r_shim_r_std_thread_thread_destroy(RStdThread * a0);
void r_shim_r_std_thread_thread_move_initialize(RStdThread * a0, RStdThread * a1);

bool r_shim_r_runtime_unwinding(void) {
    return r_runtime_unwinding();
}

void r_shim_r_std_arc_try_unwrap_result_destroy(RStdArcTryUnwrapResult * a0) {
    r_std_arc_try_unwrap_result_destroy(a0);
}

void r_shim_r_std_async_broadcast_destroy(RStdAsyncBroadcast * a0) {
    r_std_async_broadcast_destroy(a0);
}

void r_shim_r_std_async_broadcast_move_initialize(RStdAsyncBroadcast * a0, RStdAsyncBroadcast * a1) {
    r_std_async_broadcast_move_initialize(a0, a1);
}

void r_shim_r_std_async_broadcast_receiver_destroy(RStdAsyncBroadcastReceiver * a0) {
    r_std_async_broadcast_receiver_destroy(a0);
}

void r_shim_r_std_async_broadcast_receiver_move_initialize(RStdAsyncBroadcastReceiver * a0, RStdAsyncBroadcastReceiver * a1) {
    r_std_async_broadcast_receiver_move_initialize(a0, a1);
}

void r_shim_r_std_async_mutex_destroy(RStdAsyncMutex * a0) {
    r_std_async_mutex_destroy(a0);
}

void r_shim_r_std_async_mutex_guard_destroy(RStdAsyncMutexGuard * a0) {
    r_std_async_mutex_guard_destroy(a0);
}

void r_shim_r_std_async_mutex_guard_move_initialize(RStdAsyncMutexGuard * a0, RStdAsyncMutexGuard * a1) {
    r_std_async_mutex_guard_move_initialize(a0, a1);
}

void r_shim_r_std_async_mutex_move_initialize(RStdAsyncMutex * a0, RStdAsyncMutex * a1) {
    r_std_async_mutex_move_initialize(a0, a1);
}

void r_shim_r_std_async_notify_destroy(RStdAsyncNotify * a0) {
    r_std_async_notify_destroy(a0);
}

void r_shim_r_std_async_notify_move_initialize(RStdAsyncNotify * a0, RStdAsyncNotify * a1) {
    r_std_async_notify_move_initialize(a0, a1);
}

void r_shim_r_std_async_rw_lock_destroy(RStdAsyncRwLock * a0) {
    r_std_async_rw_lock_destroy(a0);
}

void r_shim_r_std_async_rw_lock_move_initialize(RStdAsyncRwLock * a0, RStdAsyncRwLock * a1) {
    r_std_async_rw_lock_move_initialize(a0, a1);
}

void r_shim_r_std_async_rw_read_guard_destroy(RStdAsyncRwReadGuard * a0) {
    r_std_async_rw_read_guard_destroy(a0);
}

void r_shim_r_std_async_rw_read_guard_move_initialize(RStdAsyncRwReadGuard * a0, RStdAsyncRwReadGuard * a1) {
    r_std_async_rw_read_guard_move_initialize(a0, a1);
}

void r_shim_r_std_async_rw_write_guard_destroy(RStdAsyncRwWriteGuard * a0) {
    r_std_async_rw_write_guard_destroy(a0);
}

void r_shim_r_std_async_rw_write_guard_move_initialize(RStdAsyncRwWriteGuard * a0, RStdAsyncRwWriteGuard * a1) {
    r_std_async_rw_write_guard_move_initialize(a0, a1);
}

void r_shim_r_std_async_semaphore_destroy(RStdAsyncSemaphore * a0) {
    r_std_async_semaphore_destroy(a0);
}

void r_shim_r_std_async_semaphore_move_initialize(RStdAsyncSemaphore * a0, RStdAsyncSemaphore * a1) {
    r_std_async_semaphore_move_initialize(a0, a1);
}

void r_shim_r_std_async_semaphore_permit_destroy(RStdAsyncSemaphorePermit * a0) {
    r_std_async_semaphore_permit_destroy(a0);
}

void r_shim_r_std_async_semaphore_permit_move_initialize(RStdAsyncSemaphorePermit * a0, RStdAsyncSemaphorePermit * a1) {
    r_std_async_semaphore_permit_move_initialize(a0, a1);
}

void r_shim_r_std_c_handle_destroy(RStdCHandle * a0) {
    r_std_c_handle_destroy(a0);
}

void r_shim_r_std_c_handle_move_initialize(RStdCHandle * a0, RStdCHandle * a1) {
    r_std_c_handle_move_initialize(a0, a1);
}

void r_shim_r_std_c_string_destroy(RStdCString * a0) {
    r_std_c_string_destroy(a0);
}

void r_shim_r_std_c_string_move_initialize(RStdCString * a0, RStdCString * a1) {
    r_std_c_string_move_initialize(a0, a1);
}

void r_shim_r_std_c_thread_attachment_destroy(RStdCThreadAttachment * a0) {
    r_std_c_thread_attachment_destroy(a0);
}

void r_shim_r_std_c_thread_attachment_move_initialize(RStdCThreadAttachment * a0, RStdCThreadAttachment * a1) {
    r_std_c_thread_attachment_move_initialize(a0, a1);
}

void r_shim_r_std_format_builder_destroy(RStdFormatBuilder * a0) {
    r_std_format_builder_destroy(a0);
}

void r_shim_r_std_format_builder_move_initialize(RStdFormatBuilder * a0, RStdFormatBuilder * a1) {
    r_std_format_builder_move_initialize(a0, a1);
}

void r_shim_r_std_fs_directory_destroy(RStdFsDirectory * a0) {
    r_std_fs_directory_destroy(a0);
}

void r_shim_r_std_fs_directory_entry_destroy(RStdFsDirectoryEntry * a0) {
    r_std_fs_directory_entry_destroy(a0);
}

void r_shim_r_std_fs_directory_entry_move_initialize(RStdFsDirectoryEntry * a0, RStdFsDirectoryEntry * a1) {
    r_std_fs_directory_entry_move_initialize(a0, a1);
}

void r_shim_r_std_fs_directory_iter_destroy(RStdFsDirectoryIter * a0) {
    r_std_fs_directory_iter_destroy(a0);
}

void r_shim_r_std_fs_directory_iter_move_initialize(RStdFsDirectoryIter * a0, RStdFsDirectoryIter * a1) {
    r_std_fs_directory_iter_move_initialize(a0, a1);
}

void r_shim_r_std_fs_directory_move_initialize(RStdFsDirectory * a0, RStdFsDirectory * a1) {
    r_std_fs_directory_move_initialize(a0, a1);
}

void r_shim_r_std_fs_directory_next_result_destroy(RStdFsDirectoryNextResult * a0) {
    r_std_fs_directory_next_result_destroy(a0);
}

void r_shim_r_std_fs_directory_next_result_move_initialize(RStdFsDirectoryNextResult * a0, RStdFsDirectoryNextResult * a1) {
    r_std_fs_directory_next_result_move_initialize(a0, a1);
}

void r_shim_r_std_fs_file_destroy(RStdFsFile * a0) {
    r_std_fs_file_destroy(a0);
}

void r_shim_r_std_fs_file_move_initialize(RStdFsFile * a0, RStdFsFile * a1) {
    r_std_fs_file_move_initialize(a0, a1);
}

void r_shim_r_std_fs_path_destroy(RStdFsPath * a0) {
    r_std_fs_path_destroy(a0);
}

void r_shim_r_std_fs_path_move_initialize(RStdFsPath * a0, RStdFsPath * a1) {
    r_std_fs_path_move_initialize(a0, a1);
}

void r_shim_r_std_fs_write_file_result_destroy(RStdFsWriteFileResult * a0) {
    r_std_fs_write_file_result_destroy(a0);
}

void r_shim_r_std_fs_write_file_result_move_initialize(RStdFsWriteFileResult * a0, RStdFsWriteFileResult * a1) {
    r_std_fs_write_file_result_move_initialize(a0, a1);
}

void r_shim_r_std_io_input_destroy(RStdIoInput * a0) {
    r_std_io_input_destroy(a0);
}

void r_shim_r_std_io_input_move_initialize(RStdIoInput * a0, RStdIoInput * a1) {
    r_std_io_input_move_initialize(a0, a1);
}

void r_shim_r_std_io_output_destroy(RStdIoOutput * a0) {
    r_std_io_output_destroy(a0);
}

void r_shim_r_std_io_output_move_initialize(RStdIoOutput * a0, RStdIoOutput * a1) {
    r_std_io_output_move_initialize(a0, a1);
}

void r_shim_r_std_io_read_result_destroy(RStdIoReadResult * a0) {
    r_std_io_read_result_destroy(a0);
}

void r_shim_r_std_io_read_result_move_initialize(RStdIoReadResult * a0, RStdIoReadResult * a1) {
    r_std_io_read_result_move_initialize(a0, a1);
}

void r_shim_r_std_io_shared_write_result_destroy(RStdIoSharedWriteResult * a0) {
    r_std_io_shared_write_result_destroy(a0);
}

void r_shim_r_std_io_shared_write_result_move_initialize(RStdIoSharedWriteResult * a0, RStdIoSharedWriteResult * a1) {
    r_std_io_shared_write_result_move_initialize(a0, a1);
}

void r_shim_r_std_io_write_all_result_destroy(RStdIoWriteAllResult * a0) {
    r_std_io_write_all_result_destroy(a0);
}

void r_shim_r_std_io_write_all_result_move_initialize(RStdIoWriteAllResult * a0, RStdIoWriteAllResult * a1) {
    r_std_io_write_all_result_move_initialize(a0, a1);
}

void r_shim_r_std_io_write_result_destroy(RStdIoWriteResult * a0) {
    r_std_io_write_result_destroy(a0);
}

void r_shim_r_std_io_write_result_move_initialize(RStdIoWriteResult * a0, RStdIoWriteResult * a1) {
    r_std_io_write_result_move_initialize(a0, a1);
}

void r_shim_r_std_json_decoder_destroy(RStdJsonDecoder * a0) {
    r_std_json_decoder_destroy(a0);
}

void r_shim_r_std_json_decoder_move_initialize(RStdJsonDecoder * a0, RStdJsonDecoder * a1) {
    r_std_json_decoder_move_initialize(a0, a1);
}

void r_shim_r_std_json_detached_destroy(RStdJsonDetached * a0) {
    r_std_json_detached_destroy(a0);
}

void r_shim_r_std_json_detached_move_initialize(RStdJsonDetached * a0, RStdJsonDetached * a1) {
    r_std_json_detached_move_initialize(a0, a1);
}

void r_shim_r_std_json_error_destroy(RStdJsonError * a0) {
    r_std_json_error_destroy(a0);
}

void r_shim_r_std_json_error_move_initialize(RStdJsonError * a0, RStdJsonError * a1) {
    r_std_json_error_move_initialize(a0, a1);
}

void r_shim_r_std_json_number_destroy(RStdJsonNumber * a0) {
    r_std_json_number_destroy(a0);
}

void r_shim_r_std_json_number_move_initialize(RStdJsonNumber * a0, RStdJsonNumber * a1) {
    r_std_json_number_move_initialize(a0, a1);
}

void r_shim_r_std_json_reader_destroy(RStdJsonReader * a0) {
    r_std_json_reader_destroy(a0);
}

void r_shim_r_std_json_reader_move_initialize(RStdJsonReader * a0, RStdJsonReader * a1) {
    r_std_json_reader_move_initialize(a0, a1);
}

void r_shim_r_std_json_value_destroy(RStdJsonValue * a0) {
    r_std_json_value_destroy(a0);
}

void r_shim_r_std_json_value_move_initialize(RStdJsonValue * a0, RStdJsonValue * a1) {
    r_std_json_value_move_initialize(a0, a1);
}

void r_shim_r_std_net_tcp_connection_destroy(RStdNetTcpConnection * a0) {
    r_std_net_tcp_connection_destroy(a0);
}

void r_shim_r_std_net_tcp_connection_move_initialize(RStdNetTcpConnection * a0, RStdNetTcpConnection * a1) {
    r_std_net_tcp_connection_move_initialize(a0, a1);
}

void r_shim_r_std_net_tcp_listener_destroy(RStdNetTcpListener * a0) {
    r_std_net_tcp_listener_destroy(a0);
}

void r_shim_r_std_net_tcp_listener_move_initialize(RStdNetTcpListener * a0, RStdNetTcpListener * a1) {
    r_std_net_tcp_listener_move_initialize(a0, a1);
}

void r_shim_r_std_net_tcp_read_result_destroy(RStdNetTcpReadResult * a0) {
    r_std_net_tcp_read_result_destroy(a0);
}

void r_shim_r_std_net_tcp_read_result_move_initialize(RStdNetTcpReadResult * a0, RStdNetTcpReadResult * a1) {
    r_std_net_tcp_read_result_move_initialize(a0, a1);
}

void r_shim_r_std_net_tcp_stream_destroy(RStdNetTcpStream * a0) {
    r_std_net_tcp_stream_destroy(a0);
}

void r_shim_r_std_net_tcp_stream_move_initialize(RStdNetTcpStream * a0, RStdNetTcpStream * a1) {
    r_std_net_tcp_stream_move_initialize(a0, a1);
}

void r_shim_r_std_net_tcp_write_all_result_destroy(RStdNetTcpWriteAllResult * a0) {
    r_std_net_tcp_write_all_result_destroy(a0);
}

void r_shim_r_std_net_tcp_write_all_result_move_initialize(RStdNetTcpWriteAllResult * a0, RStdNetTcpWriteAllResult * a1) {
    r_std_net_tcp_write_all_result_move_initialize(a0, a1);
}

void r_shim_r_std_net_tcp_write_result_destroy(RStdNetTcpWriteResult * a0) {
    r_std_net_tcp_write_result_destroy(a0);
}

void r_shim_r_std_net_tcp_write_result_move_initialize(RStdNetTcpWriteResult * a0, RStdNetTcpWriteResult * a1) {
    r_std_net_tcp_write_result_move_initialize(a0, a1);
}

void r_shim_r_std_net_udp_receive_result_destroy(RStdNetUdpReceiveResult * a0) {
    r_std_net_udp_receive_result_destroy(a0);
}

void r_shim_r_std_net_udp_receive_result_move_initialize(RStdNetUdpReceiveResult * a0, RStdNetUdpReceiveResult * a1) {
    r_std_net_udp_receive_result_move_initialize(a0, a1);
}

void r_shim_r_std_net_udp_send_result_destroy(RStdNetUdpSendResult * a0) {
    r_std_net_udp_send_result_destroy(a0);
}

void r_shim_r_std_net_udp_send_result_move_initialize(RStdNetUdpSendResult * a0, RStdNetUdpSendResult * a1) {
    r_std_net_udp_send_result_move_initialize(a0, a1);
}

void r_shim_r_std_net_udp_socket_destroy(RStdNetUdpSocket * a0) {
    r_std_net_udp_socket_destroy(a0);
}

void r_shim_r_std_net_udp_socket_move_initialize(RStdNetUdpSocket * a0, RStdNetUdpSocket * a1) {
    r_std_net_udp_socket_move_initialize(a0, a1);
}

void r_shim_r_std_net_unix_datagram_destroy(RStdNetUnixDatagram * a0) {
    r_std_net_unix_datagram_destroy(a0);
}

void r_shim_r_std_net_unix_datagram_move_initialize(RStdNetUnixDatagram * a0, RStdNetUnixDatagram * a1) {
    r_std_net_unix_datagram_move_initialize(a0, a1);
}

void r_shim_r_std_net_unix_listener_destroy(RStdNetUnixListener * a0) {
    r_std_net_unix_listener_destroy(a0);
}

void r_shim_r_std_net_unix_listener_move_initialize(RStdNetUnixListener * a0, RStdNetUnixListener * a1) {
    r_std_net_unix_listener_move_initialize(a0, a1);
}

void r_shim_r_std_net_unix_stream_destroy(RStdNetUnixStream * a0) {
    r_std_net_unix_stream_destroy(a0);
}

void r_shim_r_std_net_unix_stream_move_initialize(RStdNetUnixStream * a0, RStdNetUnixStream * a1) {
    r_std_net_unix_stream_move_initialize(a0, a1);
}

void r_shim_r_std_process_child_destroy(RStdProcessChild * a0) {
    r_std_process_child_destroy(a0);
}

void r_shim_r_std_process_child_move_initialize(RStdProcessChild * a0, RStdProcessChild * a1) {
    r_std_process_child_move_initialize(a0, a1);
}

void r_shim_r_std_process_command_destroy(RStdProcessCommand * a0) {
    r_std_process_command_destroy(a0);
}

void r_shim_r_std_process_command_move_initialize(RStdProcessCommand * a0, RStdProcessCommand * a1) {
    r_std_process_command_move_initialize(a0, a1);
}

void r_shim_r_std_process_spawn_result_destroy(RStdProcessSpawnResult * a0) {
    r_std_process_spawn_result_destroy(a0);
}

void r_shim_r_std_process_spawn_result_move_initialize(RStdProcessSpawnResult * a0, RStdProcessSpawnResult * a1) {
    r_std_process_spawn_result_move_initialize(a0, a1);
}

void r_shim_r_std_process_wait_result_destroy(RStdProcessWaitResult * a0) {
    r_std_process_wait_result_destroy(a0);
}

void r_shim_r_std_process_wait_result_move_initialize(RStdProcessWaitResult * a0, RStdProcessWaitResult * a1) {
    r_std_process_wait_result_move_initialize(a0, a1);
}

void r_shim_r_std_rc_try_unwrap_result_destroy(RStdRcTryUnwrapResult * a0) {
    r_std_rc_try_unwrap_result_destroy(a0);
}

void r_shim_r_std_secret_buffer_destroy(RStdSecretBuffer * a0) {
    r_std_secret_buffer_destroy(a0);
}

void r_shim_r_std_secret_buffer_move_initialize(RStdSecretBuffer * a0, RStdSecretBuffer * a1) {
    r_std_secret_buffer_move_initialize(a0, a1);
}

void r_shim_r_std_secret_erase(void * a0, size_t a1) {
    r_std_secret_erase(a0, a1);
}

void r_shim_r_std_signal_listener_destroy(RStdSignalListener * a0) {
    r_std_signal_listener_destroy(a0);
}

void r_shim_r_std_signal_listener_move_initialize(RStdSignalListener * a0, RStdSignalListener * a1) {
    r_std_signal_listener_move_initialize(a0, a1);
}

void r_shim_r_std_string_destroy(RStdString * a0) {
    r_std_string_destroy(a0);
}

void r_shim_r_std_string_from_bytes_result_destroy(RStdStringFromBytesResult * a0) {
    r_std_string_from_bytes_result_destroy(a0);
}

void r_shim_r_std_string_from_bytes_result_move_initialize(RStdStringFromBytesResult * a0, RStdStringFromBytesResult * a1) {
    r_std_string_from_bytes_result_move_initialize(a0, a1);
}

void r_shim_r_std_string_move_initialize(RStdString * a0, RStdString * a1) {
    r_std_string_move_initialize(a0, a1);
}

void r_shim_r_std_sync_barrier_destroy(RStdSyncBarrier * a0) {
    r_std_sync_barrier_destroy(a0);
}

void r_shim_r_std_sync_barrier_move_initialize(RStdSyncBarrier * a0, RStdSyncBarrier * a1) {
    r_std_sync_barrier_move_initialize(a0, a1);
}

void r_shim_r_std_sync_channel_destroy(RStdSyncChannel * a0) {
    r_std_sync_channel_destroy(a0);
}

void r_shim_r_std_sync_channel_move_initialize(RStdSyncChannel * a0, RStdSyncChannel * a1) {
    r_std_sync_channel_move_initialize(a0, a1);
}

void r_shim_r_std_sync_condvar_destroy(RStdSyncCondvar * a0) {
    r_std_sync_condvar_destroy(a0);
}

void r_shim_r_std_sync_condvar_move_initialize(RStdSyncCondvar * a0, RStdSyncCondvar * a1) {
    r_std_sync_condvar_move_initialize(a0, a1);
}

void r_shim_r_std_sync_lock_result_destroy(RStdSyncLockResult * a0) {
    r_std_sync_lock_result_destroy(a0);
}

void r_shim_r_std_sync_mutex_destroy(RStdSyncMutex * a0) {
    r_std_sync_mutex_destroy(a0);
}

void r_shim_r_std_sync_mutex_guard_destroy(RStdSyncMutexGuard * a0) {
    r_std_sync_mutex_guard_destroy(a0);
}

void r_shim_r_std_sync_once_destroy(RStdSyncOnce * a0) {
    r_std_sync_once_destroy(a0);
}

void r_shim_r_std_sync_once_lock_destroy(RStdSyncOnceLock * a0) {
    r_std_sync_once_lock_destroy(a0);
}

void r_shim_r_std_sync_once_move_initialize(RStdSyncOnce * a0, RStdSyncOnce * a1) {
    r_std_sync_once_move_initialize(a0, a1);
}

void r_shim_r_std_sync_permit_destroy(RStdSyncPermit * a0) {
    r_std_sync_permit_destroy(a0);
}

void r_shim_r_std_sync_permit_move_initialize(RStdSyncPermit * a0, RStdSyncPermit * a1) {
    r_std_sync_permit_move_initialize(a0, a1);
}

void r_shim_r_std_sync_read_lock_result_destroy(RStdSyncReadLockResult * a0) {
    r_std_sync_read_lock_result_destroy(a0);
}

void r_shim_r_std_sync_receiver_destroy(RStdSyncReceiver * a0) {
    r_std_sync_receiver_destroy(a0);
}

void r_shim_r_std_sync_receiver_move_initialize(RStdSyncReceiver * a0, RStdSyncReceiver * a1) {
    r_std_sync_receiver_move_initialize(a0, a1);
}

void r_shim_r_std_sync_rw_lock_destroy(RStdSyncRwLock * a0) {
    r_std_sync_rw_lock_destroy(a0);
}

void r_shim_r_std_sync_rw_read_guard_destroy(RStdSyncRwReadGuard * a0) {
    r_std_sync_rw_read_guard_destroy(a0);
}

void r_shim_r_std_sync_rw_write_guard_destroy(RStdSyncRwWriteGuard * a0) {
    r_std_sync_rw_write_guard_destroy(a0);
}

void r_shim_r_std_sync_sender_destroy(RStdSyncSender * a0) {
    r_std_sync_sender_destroy(a0);
}

void r_shim_r_std_sync_sender_move_initialize(RStdSyncSender * a0, RStdSyncSender * a1) {
    r_std_sync_sender_move_initialize(a0, a1);
}

void r_shim_r_std_sync_sync_channel_destroy(RStdSyncSyncChannel * a0) {
    r_std_sync_sync_channel_destroy(a0);
}

void r_shim_r_std_sync_sync_channel_move_initialize(RStdSyncSyncChannel * a0, RStdSyncSyncChannel * a1) {
    r_std_sync_sync_channel_move_initialize(a0, a1);
}

void r_shim_r_std_sync_sync_sender_destroy(RStdSyncSyncSender * a0) {
    r_std_sync_sync_sender_destroy(a0);
}

void r_shim_r_std_sync_sync_sender_move_initialize(RStdSyncSyncSender * a0, RStdSyncSyncSender * a1) {
    r_std_sync_sync_sender_move_initialize(a0, a1);
}

void r_shim_r_std_sync_try_lock_result_destroy(RStdSyncTryLockResult * a0) {
    r_std_sync_try_lock_result_destroy(a0);
}

void r_shim_r_std_sync_try_read_lock_result_destroy(RStdSyncTryReadLockResult * a0) {
    r_std_sync_try_read_lock_result_destroy(a0);
}

void r_shim_r_std_sync_try_write_lock_result_destroy(RStdSyncTryWriteLockResult * a0) {
    r_std_sync_try_write_lock_result_destroy(a0);
}

void r_shim_r_std_sync_write_lock_result_destroy(RStdSyncWriteLockResult * a0) {
    r_std_sync_write_lock_result_destroy(a0);
}

void r_shim_r_std_thread_join_handle_destroy(RStdThreadJoinHandle * a0) {
    r_std_thread_join_handle_destroy(a0);
}

void r_shim_r_std_thread_join_result_destroy(RStdThreadJoinResult * a0) {
    r_std_thread_join_result_destroy(a0);
}

void r_shim_r_std_thread_panic_report_destroy(RStdThreadPanicReport * a0) {
    r_std_thread_panic_report_destroy(a0);
}

void r_shim_r_std_thread_panic_report_move_initialize(RStdThreadPanicReport * a0, RStdThreadPanicReport * a1) {
    r_std_thread_panic_report_move_initialize(a0, a1);
}

void r_shim_r_std_thread_scoped_join_handle_destroy(RStdThreadScopedJoinHandle * a0) {
    r_std_thread_scoped_join_handle_destroy(a0);
}

void r_shim_r_std_thread_thread_destroy(RStdThread * a0) {
    r_std_thread_thread_destroy(a0);
}

void r_shim_r_std_thread_thread_move_initialize(RStdThread * a0, RStdThread * a1) {
    r_std_thread_thread_move_initialize(a0, a1);
}
