#!/usr/bin/env python3
"""Generate the exhaustive checked-conversion compiler fixture."""

from __future__ import annotations

import argparse
from pathlib import Path


NUMERIC_TYPES = (
    "i8",
    "u8",
    "i16",
    "u16",
    "i32",
    "u32",
    "i64",
    "u64",
    "isize",
    "usize",
    "f32",
    "f64",
    "c_char",
    "c_schar",
    "c_uchar",
    "c_short",
    "c_ushort",
    "c_int",
    "c_uint",
    "c_long",
    "c_ulong",
    "c_llong",
    "c_ullong",
    "c_bool",
    "c_wchar",
    "c_wint",
    "c_int8",
    "c_uint8",
    "c_int16",
    "c_uint16",
    "c_int32",
    "c_uint32",
    "c_int64",
    "c_uint64",
    "c_intptr",
    "c_uintptr",
    "c_intmax",
    "c_uintmax",
    "c_float",
    "c_double",
    "c_long_double",
    "c_size",
    "c_ptrdiff",
)

R_NUMERIC_TYPE_COUNT = 12


def render_function(family: str, prefix: str, destination: str) -> list[str]:
    parameters = ", ".join(
        f"{source} source_{source}" for source in NUMERIC_TYPES
    )
    lines = [
        f"void {prefix}_{destination}({parameters}) throws std.convert::range_error {{"
    ]
    for source in NUMERIC_TYPES:
        lines.extend(
            (
                f"    {destination} result_{source} =",
                f"        {family}::checked_{destination}(source_{source});",
                f"    result_{source} as void;",
            )
        )
    lines.extend(("}", ""))
    return lines


def render_fixture() -> str:
    lines = [
        "// Generated by tools/generate_checked_codegen_fixture.py.",
        "module test.codegen.checked_matrix;",
        "",
    ]
    for destination in NUMERIC_TYPES:
        lines.extend(render_function("std.convert", "convert", destination))
    for destination in NUMERIC_TYPES[R_NUMERIC_TYPE_COUNT:]:
        lines.extend(render_function("std.c", "c", destination))
    lines.extend(("i32 main() {", "    return 0;", "}", ""))
    return "\n".join(lines)


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    rendered = render_fixture()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    if not arguments.output.exists() or arguments.output.read_text(encoding="utf-8") != rendered:
        arguments.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
