#!/usr/bin/env python3
"""Generate the calculator's typed dispatchers from the normative math signatures.

Each branch parses user operands, calls its exact public API and returns printable output.
This is application dispatch, not a fixture that discards computed values.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TYPES = ('f32', 'f64', 'c_float', 'c_double', 'c_long_double', 'complex_f32', 'complex_f64')
SIGNATURE = re.compile(r'^std\.math::(\w+)\((.*)\) -> (\S+)(?: throws .*)?$')


def source_type(name: str) -> str:
    return 'std.math::' + name if name.startswith('complex_') else name


def outputs() -> dict[str, str]:
    inventory = json.loads((ROOT / 'library/generated/api_inventory/implementation_inventory.json').read_text())
    groups: dict[str, list[tuple[str, list[str], str]]] = {name: [] for name in TYPES}
    for item in inventory['items']:
        if item['module'] != 'std.math' or item['item_kind'] not in {'operation', 'operation_specialization'}:
            continue
        if item['id'] == 'std.math::as_error':
            continue
        match = SIGNATURE.fullmatch(item['source_signature'])
        assert match is not None, item
        name, parameters, result = match.groups()
        kind = next(t for t in sorted(TYPES, key=len, reverse=True) if name.endswith('_' + t))
        operation = name[:-(len(kind) + 1)]
        types = [p.split(' ', 1)[0] for p in parameters.split(', ') if p]
        groups[kind].append((operation, types, source_type(result)))
    files = {}
    operations = sorted({operation for group in groups.values() for operation, _, _ in group})
    files['examples/calculator/src/operations.r'] = '\n'.join([
        '// Generated by tools/generate_calculator.py; operation names are user commands.',
        'module example.calculator.operations;', '', 'enum Operation {',
        *['    ' + op + ',' for op in operations], '};', '',
    ])
    for kind, group in groups.items():
        lines = [
            '// Generated by tools/generate_calculator.py. See README.md for CLI examples.',
            f'module example.calculator.number_{kind};', '',
            'import example.calculator.operations::{Operation};',
            'import example.calculator.common::{Usage, require_operands};', '',
            'std.string::string evaluate(Operation operation, str... operands)',
            '    throws Usage, std.convert::parse_error, std.math::math_error, std.alloc::alloc_error {',
            '    switch (operation) {',
        ]
        for operation, parameters, result in group:
            words = sum(2 if p.startswith('complex_') else 1 for p in parameters)
            lines.extend([f'    case Operation::{operation}:', f'        require_operands(operands, {words}usize);'])
            at = 0
            operands = []
            for i, parameter in enumerate(parameters):
                name = f'operand{i}'
                if parameter.startswith('complex_'):
                    component = parameter.removeprefix('complex_')
                    lines += [f'        {component} real{i} = std.convert::parse_{component}(operands[{at}]);',
                              f'        {component} imag{i} = std.convert::parse_{component}(operands[{at + 1}]);',
                              f'        std.math::{parameter} {name} = {{ .real = real{i}, .imag = imag{i} }};']
                    at += 2
                else:
                    radix = ', 10u32' if parameter == 'i32' else ''
                    lines.append(f'        {parameter} {name} = std.convert::parse_{parameter}(operands[{at}]{radix});')
                    at += 1
                operands.append(name)
            lines.append(f'        {result} value = std.math::{operation}({", ".join(operands)});')
            if 'complex_' in result:
                text = '{value.real} {value.imag}'
            elif 'fraction_parts_' in result:
                text = '{value.whole} {value.fraction}'
            elif 'binary_parts_' in result:
                text = '{value.fraction} {value.exponent}'
            else:
                text = '{value}'
            lines += [f'        std.string::string text = f"{text}\\n";', '        return move text;']
        lines += ['    default:', '        throw Usage { .message = "operation does not support this number type" };', '    }', '}', '']
        files[f'examples/calculator/src/{kind}.r'] = '\n'.join(lines)
    return files


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for name, content in outputs().items():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                raise SystemExit(f'calculator dispatcher is stale: {name}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)


if __name__ == '__main__':
    main()
