#!/usr/bin/env python3
"""Generate the closed compiler registry for source-visible standard types."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


INVENTORY_PATH = Path("library/generated/api_inventory/implementation_inventory.json")
OUTPUT_PATH = Path("compiler/semantic/standard_type_registry.generated.inc")
SCHEMA_NAME = re.compile(r"_[A-Z](?:$|_)")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def infer_arity(name: str, item: dict[str, Any], items: list[dict[str, Any]]) -> int:
    implementation = item.get("implementation")
    if isinstance(implementation, dict):
        arity = implementation.get("generic_arity")
        if type(arity) is int:
            require(0 <= arity <= 2, f"invalid generic arity for {name}")
            return arity
    source_signature = item.get("source_signature")
    if isinstance(source_signature, str):
        match = re.fullmatch(re.escape(name) + r"<([^<>()]*)>", source_signature)
        if match is not None:
            return match.group(1).count(",") + 1
    pattern = re.compile(re.escape(name) + r"<([^<>()]*)>")
    arities: set[int] = set()
    for candidate in items:
        signature = candidate.get("source_signature")
        if not isinstance(signature, str):
            continue
        for match in pattern.finditer(signature):
            arguments = match.group(1)
            if re.search(r"\b[A-Z]\b", arguments):
                arities.add(arguments.count(",") + 1)
    require(len(arities) <= 1, f"ambiguous generic arity for {name}: {sorted(arities)}")
    return next(iter(arities), 0)


def load_records(root: Path) -> list[tuple[str, int]]:
    inventory = json.loads((root / INVENTORY_PATH).read_text(encoding="utf-8"))
    items = inventory.get("items")
    require(isinstance(items, list), "inventory items must be an array")
    records: list[tuple[str, int]] = []
    for item in items:
        if not isinstance(item, dict) or item.get("facet") != "type":
            continue
        implementation = item.get("implementation")
        if isinstance(implementation, dict) and implementation.get("kind") == "r_source":
            # Types of standard modules written in R resolve as imported aggregates
            # (Core R-MOD-0002); the closed registry names compiler-recognized types only.
            continue
        name = item.get("id")
        require(isinstance(name, str) and name, "standard type id must be a string")
        if SCHEMA_NAME.search(name) is not None:
            continue
        records.append((name, infer_arity(name, item, items)))
    records.sort()
    require(records, "inventory contains no concrete standard types")
    require(len({name for name, _ in records}) == len(records), "duplicate standard type id")
    return records


def render(records: list[tuple[str, int]]) -> str:
    lines = [
        "/* Generated by tools/generate_standard_type_registry.py. */",
        "static const RStandardTypeRegistryEntry r_standard_type_registry[] = {",
    ]
    for name, arity in records:
        lines.append(
            f'    {{"{name}", sizeof("{name}") - 1U, UINT32_C({arity})}},'
        )
    lines.extend(("};", ""))
    return "\n".join(lines)


def update(path: Path, expected: str, write: bool) -> bool:
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        return True
    try:
        actual = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"missing generated file: {path}", file=sys.stderr)
        return False
    if actual != expected:
        print(f"stale generated file: {path}", file=sys.stderr)
        return False
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--verify", action="store_true")
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    try:
        records = load_records(root)
        return 0 if update(root / OUTPUT_PATH, render(records), arguments.write) else 1
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"standard type registry generation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
