#!/usr/bin/env python3
"""Generate a radix/representation calculator covering the closed integer and cast APIs."""
from __future__ import annotations
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
R_INTEGERS = ('i8','u8','i16','u16','i32','u32','i64','u64','isize','usize')
C_INTEGERS = ('c_char','c_schar','c_uchar','c_short','c_ushort','c_int','c_uint','c_long','c_ulong','c_llong','c_ullong','c_bool','c_wchar','c_wint','c_int8','c_uint8','c_int16','c_uint16','c_int32','c_uint32','c_int64','c_uint64','c_intptr','c_uintptr','c_intmax','c_uintmax','c_size','c_ptrdiff')
FLOATS = ('f32','f64','c_float','c_double','c_long_double')
OPS = ('parse','convert','c_convert','limits', *[p+'_'+o for p in ('checked','wrapping','saturating') for o in ('add','sub','mul')])
TYPES = R_INTEGERS + C_INTEGERS + FLOATS


def outputs() -> dict[str,str]:
    files={}
    files['examples/numbers/src/operation.r']='\n'.join(['// Generated by tools/generate_numeric_example.py.','module example.numbers.operation;','', 'enum Operation {',*['    '+op+',' for op in OPS], '};',''])
    for typ in TYPES:
        floating=typ in FLOATS
        lines=['// Generated by tools/generate_numeric_example.py.','module example.numbers.type_'+typ+';', '',
               'import example.numbers.operation::{Operation};',
               'import example.calculator.common::{Usage};','',
               f'protected std.string::string format_value({typ} value, u32 radix)',
               '    throws std.format::format_error {',
               '    std.format::builder builder = std.format::create();',
               '    u32 output_radix = radix == 0u32 ? 10u32 : radix;',
               '    builder.append(value'+('' if floating else ', output_radix')+');',
               '    std.string::string text = (move builder).finish();','    return move text;','}', '',
               'std.string::string evaluate(Operation operation, str first, str second, u32 radix)',
               '    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {']
        lines += ['    if (operation == Operation::convert) {',
                  '        f64 input = std.convert::parse_f64(first);',
                  f'        {typ} value = std.convert::checked_{typ}(input);',
                  '        std.string::string text = format_value(value, radix);','        return move text;','    }']
        if typ.startswith('c_'):
            lines += ['    if (operation == Operation::c_convert) {',
                      '        f64 input = std.convert::parse_f64(first);',
                      f'        {typ} value = std.c::checked_{typ}(input);',
                      '        std.string::string text = format_value(value, radix);','        return move text;','    }']
        if typ in R_INTEGERS:
            lines += ['    if (operation == Operation::limits) {',
                      f'        {typ} minimum = core::min_{typ};',f'        {typ} maximum = core::max_{typ};',
                      '        std.string::string low = format_value(minimum, radix);',
                      '        std.string::string high = format_value(maximum, radix);',
                      '        std.string::string text = f"{low} {high}";','        return move text;','    }']
        lines += [f'    {typ} left = std.convert::parse_{typ}(first'+('' if floating else ', radix')+');',
                  '    if (operation == Operation::parse) {','        std.string::string text = format_value(left, radix);','        return move text;','    }']
        if typ in R_INTEGERS:
            lines += [f'    {typ} right = std.convert::parse_{typ}(second, radix);','    switch (operation) {']
            for prefix in ('checked','wrapping','saturating'):
                for op in ('add','sub','mul'):
                    lines.append(f'    case Operation::{prefix}_{op}:')
                    if prefix=='checked':
                        lines += [f'        o<{typ}> result = core::{prefix}_{op}(left, right);','        switch (result) {',
                                  '        case variant o::some(value):', '            std.string::string text = format_value(*value, radix);',
                                  '            return move text;', '        case variant o::none:',
                                  '            std.string::string text = std.string::from_str("overflow");','            return move text;','        }','        break;']
                    else:
                        lines += [f'        {typ} value = core::{prefix}_{op}(left, right);',
                                  '        std.string::string text = format_value(value, radix);','        return move text;']
            lines += ['    default: throw Usage { .message = "unsupported integer operation" };','    }']
        lines+=['    throw Usage { .message = "operation requires an R integer type" };','}','']
        files['examples/numbers/src/'+typ+'.r']='\n'.join(lines)
    lines=['// Generated by tools/generate_numeric_example.py.','module example.numbers.dispatch;',
           'import example.numbers.operation::{Operation};','import example.calculator.common::{Usage};','import std.text;',
           *['import example.numbers.type_'+typ+';' for typ in TYPES],'',
           'std.string::string evaluate(Operation operation, str kind, str first, str second, u32 radix)',
           '    throws Usage, std.convert::parse_error, std.convert::range_error, std.format::format_error, std.alloc::alloc_error {']
    for typ in TYPES:
        lines += [f'    bool choose_{typ} = std.text::equal_ignore_ascii_case(kind, "{typ}");',
                  f'    if (choose_{typ} == true) {{',
                  f'        std.string::string text = example.numbers.type_{typ}::evaluate(operation, first, second, radix);',
                  '        return move text;','    }']
    lines+=['    throw Usage { .message = "unknown numeric type" };','}','']
    files['examples/numbers/src/dispatch.r']='\n'.join(lines)
    files['examples/numbers/modules.map']='\n'.join(['example.calculator.common = ../calculator/src/common.r',
        'example.numbers.operation = src/operation.r','example.numbers.dispatch = src/dispatch.r',
        *[f'example.numbers.type_{typ} = src/{typ}.r' for typ in TYPES],'example.numbers.main = src/main.r',''])
    return files


def main() -> None:
    parser=argparse.ArgumentParser(description=__doc__); parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for name,content in outputs().items():
        p=ROOT/name
        if args.check:
            if not p.exists() or p.read_text()!=content:raise SystemExit('stale numeric dispatcher: '+name)
        else:p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content)

if __name__=='__main__':main()
