#!/usr/bin/env python3
"""Generate the compiler registry for named Move-only standard types."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


INVENTORY_PATH = Path("library/generated/api_inventory/implementation_inventory.json")
TABLE_PATH = Path("compiler/source/named_standard_move_abi.generated.inc")
FIXTURE_PATH = Path("tests/fixtures/codegen_core_adopt_named_standard_move.r")
C_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def require(condition: bool, message: str) -> None:
    if not condition:
        raise ValueError(message)


def load_records(root: Path) -> list[dict[str, str]]:
    inventory = json.loads((root / INVENTORY_PATH).read_text(encoding="utf-8"))
    require(isinstance(inventory, dict), "inventory root must be an object")
    items = inventory.get("items")
    require(isinstance(items, list), "inventory items must be an array")
    records: list[dict[str, str]] = []

    for item in items:
        if not isinstance(item, dict) or item.get("facet") != "type":
            continue
        implementation = item.get("implementation")
        if not isinstance(implementation, dict):
            continue
        type_glue = implementation.get("type_glue")
        if type_glue is None:
            continue
        item_id = item.get("id")
        header = implementation.get("header")
        c_type = implementation.get("c_type")
        require(isinstance(item_id, str) and item_id, "Move type id must be a string")
        require(implementation.get("kind") == "header", f"Move type must map to header: {item_id}")
        require(isinstance(header, str) and header, f"missing header mapping: {item_id}")
        require(
            isinstance(c_type, str) and C_IDENTIFIER.fullmatch(c_type) is not None,
            f"invalid C type mapping: {item_id}",
        )
        require(isinstance(type_glue, dict), f"invalid type_glue mapping: {item_id}")
        move_initialize = type_glue.get("move_initialize")
        drop = type_glue.get("drop")
        require(
            isinstance(move_initialize, str) and C_IDENTIFIER.fullmatch(move_initialize) is not None,
            f"invalid move initializer: {item_id}",
        )
        require(
            isinstance(drop, str) and C_IDENTIFIER.fullmatch(drop) is not None,
            f"invalid drop function: {item_id}",
        )
        require(type_glue.get("linkage") == "static_inline", f"unsupported type glue linkage: {item_id}")
        generic_arity = implementation.get("generic_arity", 0)
        require(type(generic_arity) is int and 0 <= generic_arity <= 2,
                f"invalid generic arity: {item_id}")
        require((root / header).is_file(), f"mapped header does not exist: {header}")
        records.append(
            {
                "id": item_id,
                "header": Path(header).name,
                "c_type": c_type,
                "move_initialize": move_initialize,
                "drop": drop,
                "generic_arity": generic_arity,
            }
        )

    require(records, "inventory contains no named Move ABI records")
    records.sort(key=lambda record: record["id"])
    require(
        len({record["id"] for record in records}) == len(records),
        "duplicate named Move ABI record",
    )
    return records


def render_table(records: list[dict[str, str]]) -> str:
    headers = sorted({record["header"] for record in records})
    require(len(headers) <= 64, "named Move header set exceeds the 64-bit header mask")
    header_indices = {header: index for index, header in enumerate(headers)}
    lines = [
        "/* Generated by tools/generate_named_standard_move_abi.py. */",
        "static const char *const r_named_standard_move_abi_headers[] = {",
    ]
    for header in headers:
        lines.append(f'    "{header}",')
    lines.extend(
        (
            "};",
            "",
            "static const RNamedStandardMoveAbi r_named_standard_move_abi_records[] = {",
        )
    )
    for record in records:
        name = record["id"]
        lines.extend(
            (
                "    {",
                f'        "{name}",',
                f'        sizeof("{name}") - 1U,',
                f'        "{record["c_type"]}",',
                f'        "{record["move_initialize"]}",',
                f'        "{record["drop"]}",',
                f'        UINT32_C({record["generic_arity"]}),',
                f'        UINT32_C({header_indices[record["header"]]}),',
                "    },",
            )
        )
    lines.extend(("};", ""))
    return "\n".join(lines)


def render_fixture(records: list[dict[str, str]]) -> str:
    lines = ["module codegen.core_adopt_named_standard_move;", ""]
    for index, record in enumerate(records, start=1):
        type_name = record["id"]
        if record["id"] in {"std.json::detached", "std.json::reader"}:
            type_name += "<std.io::input>"
        elif record["generic_arity"] == 1:
            type_name += "<i32>"
        elif record["generic_arity"] == 2:
            type_name += "<i32, i64>"
        lines.extend(
            (
                f"void round_trip_{index:03d}(raw {type_name}* pointer) {{",
                "    unsafe {",
                f"        own {type_name}* owner = core::adopt(pointer);",
                f"        raw {type_name}* returned = core::release(move owner);",
                "        returned as void;",
                "    }",
                "}",
                "",
            )
        )
    lines.extend(("i32 main() {", "    return 0;", "}", ""))
    return "\n".join(lines)


def update_file(path: Path, expected: str, write: bool) -> bool:
    if write:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding="utf-8", newline="\n")
        return True
    try:
        actual = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        print(f"missing generated file: {path}", file=sys.stderr)
        return False
    if actual != expected:
        print(f"stale generated file: {path}", file=sys.stderr)
        return False
    return True


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, required=True)
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument("--write", action="store_true")
    action.add_argument("--verify", action="store_true")
    return parser.parse_args()


def main() -> int:
    arguments = parse_arguments()
    try:
        root = arguments.root.resolve()
        records = load_records(root)
        outputs = (
            (root / TABLE_PATH, render_table(records)),
            (root / FIXTURE_PATH, render_fixture(records)),
        )
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0 if all(update_file(path, text, arguments.write) for path, text in outputs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
