#!/usr/bin/env python3
"""Generate the compiler's closed std.math operation descriptor table."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path


SIGNATURE = re.compile(
    r"^std\.math::(?P<name>[a-z0-9_]+)\((?P<arguments>.*)\) -> "
    r"(?P<result>[^ ]+)(?: throws (?P<errors>.*))?$"
)


def operations(inventory: Path) -> list[dict[str, object]]:
    document = json.loads(inventory.read_text(encoding="utf-8"))
    result: list[tuple[str, dict[str, object]]] = []
    for item in document["items"]:
        if item.get("module") != "std.math" or item.get("item_kind") not in {
            "operation",
            "operation_specialization",
        }:
            continue
        result.append((item["id"], item))
    return [item for _, item in sorted(result)]


def descriptor_lines(inventory: Path) -> list[str]:
    items = operations(inventory)

    lines = ["/* Generated by tools/generate_standard_math_operations.py. */"]
    for item in items:
        match = SIGNATURE.fullmatch(item["source_signature"])
        if match is None:
            raise ValueError(f"unsupported std.math signature: {item['source_signature']}")
        arguments = match.group("arguments")
        argument_types = [
            argument.split(" ", 1)[0] for argument in arguments.split(", ") if argument
        ]
        if len(argument_types) > 2:
            raise ValueError(f"std.math operation has more than two arguments: {item['id']}")
        argument_types.extend([""] * (2 - len(argument_types)))
        implementation = item["implementation"]
        c_symbol = implementation.get("c_symbol")
        if not c_symbol:
            raise ValueError(f"std.math operation has no C symbol: {item['id']}")
        checked = bool(item["checked_effect"]["normalized_error_set"])
        rule_id = item["normative_rules"][0]
        values = (
            match.group("name"),
            c_symbol,
            match.group("result"),
            argument_types[0],
            argument_types[1],
            str(len([value for value in argument_types if value])),
            "true" if checked else "false",
            rule_id,
        )
        quoted = [f'"{value}"' for value in values[:5]]
        lines.append(
            "R_STANDARD_MATH_OPERATION(" + ", ".join((*quoted, values[5], values[6], f'"{values[7]}"')) + ")"
        )
    return lines


def source_type(name: str) -> str:
    if name in {"complex_f32", "complex_f64"}:
        return f"std.math::{name}"
    return name


def fixture_lines(inventory: Path, asynchronous: bool = False) -> list[str]:
    lines = [
        "// Generated by tools/generate_standard_math_operations.py.",
        "module audit."
        + ("async_std_math_all_operations;" if asynchronous else "std_math_all_operations;"),
        "",
    ]
    for index, item in enumerate(operations(inventory)):
        match = SIGNATURE.fullmatch(item["source_signature"])
        if match is None:
            raise ValueError(f"unsupported std.math signature: {item['source_signature']}")
        arguments = match.group("arguments")
        argument_types = [
            argument.split(" ", 1)[0] for argument in arguments.split(", ") if argument
        ]
        parameters = ", ".join(
            f"{source_type(argument_type)} value{argument_index}"
            for argument_index, argument_type in enumerate(argument_types)
        )
        operands = ", ".join(
            f"value{argument_index}" for argument_index in range(len(argument_types))
        )
        checked = bool(item["checked_effect"]["normalized_error_set"])
        lines.append(
            ("async " if asynchronous else "")
            + f"{source_type(match.group('result'))} probe_{index:03d}({parameters})"
            + (" throws std.math::math_error" if checked else "")
            + " {"
        )
        lines.append(f"    return std.math::{match.group('name')}({operands});")
        lines.append("}")
        lines.append("")
    lines.extend([("async " if asynchronous else "") + "i32 main() {", "    return 0;", "}"])
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inventory", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--fixture-output", type=Path)
    parser.add_argument("--async-fixture-output", type=Path)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    content = "\n".join(descriptor_lines(arguments.inventory)) + "\n"
    fixture_content = (
        "\n".join(fixture_lines(arguments.inventory)) + "\n"
        if arguments.fixture_output is not None
        else None
    )
    async_fixture_content = (
        "\n".join(fixture_lines(arguments.inventory, asynchronous=True)) + "\n"
        if arguments.async_fixture_output is not None
        else None
    )
    if arguments.check:
        if not arguments.output.is_file() or arguments.output.read_text(encoding="utf-8") != content:
            raise SystemExit("generated std.math operation table is stale")
        if fixture_content is not None and (
            not arguments.fixture_output.is_file()
            or arguments.fixture_output.read_text(encoding="utf-8") != fixture_content
        ):
            raise SystemExit("generated std.math frontend fixture is stale")
        if async_fixture_content is not None and (
            not arguments.async_fixture_output.is_file()
            or arguments.async_fixture_output.read_text(encoding="utf-8")
            != async_fixture_content
        ):
            raise SystemExit("generated async std.math frontend fixture is stale")
        return 0
    arguments.output.write_text(content, encoding="utf-8")
    if fixture_content is not None:
        arguments.fixture_output.write_text(fixture_content, encoding="utf-8")
    if async_fixture_content is not None:
        arguments.async_fixture_output.write_text(async_fixture_content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
