#!/usr/bin/env python3
"""Generate the closed compiler registry for source-visible standard operations."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


INVENTORY_PATH = Path("library/generated/api_inventory/implementation_inventory.json")
OUTPUT_PATH = Path("compiler/semantic/standard_operation_registry.generated.inc")
DISCARDABLE_OUTPUT_PATH = Path("compiler/semantic/standard_discardable_operations.generated.inc")
SCOPED_OUTPUT_PATH = Path("compiler/semantic/standard_scoped_operations.generated.inc")
DEADLINE_OUTPUT_PATH = Path("compiler/semantic/standard_deadline_operations.generated.inc")
DEADLINE_PARAMETER = "o<std.time::instant> deadline"
SCHEMA_NAME = re.compile(r"SUFFIX|_[A-Z](?:$|_)")


def load_records(root: Path) -> list[tuple[str, str, str, bool]]:
    inventory = json.loads((root / INVENTORY_PATH).read_text(encoding="utf-8"))
    items = inventory.get("items")
    if not isinstance(items, list):
        raise ValueError("inventory items must be an array")
    records: list[tuple[str, str, str, bool]] = []
    for item in items:
        if not isinstance(item, dict) or item.get("facet") != "operation":
            continue
        implementation = item.get("implementation")
        if isinstance(implementation, dict) and implementation.get("kind") == "r_source":
            # Functions of standard modules written in R are ordinary imported functions
            # (Core R-MOD-0002); the closed registry names compiler-recognized operations only.
            continue
        name = item.get("id")
        if not isinstance(name, str) or not name or SCHEMA_NAME.search(name) is not None:
            continue
        panics = item.get("panics_on_allocation_failure")
        if not isinstance(panics, bool):
            raise ValueError(f"operation lacks panics_on_allocation_failure: {name}")
        components = name.split("::")
        if len(components) == 2 and components[0] == "core":
            records.append(("core", "", components[1], panics))
        elif len(components) == 2 and components[0].startswith("std."):
            records.append(("std", components[0][4:], components[1], panics))
        else:
            raise ValueError(f"unsupported public operation name: {name}")
    records.sort()
    if not records or len(set(records)) != len(records):
        raise ValueError("operation registry is empty or contains duplicates")
    return records


def load_flagged_operations(root: Path, flag: str, description: str) -> list[str]:
    """Enumerator names of the compiler-recognized operations carrying one inventory flag.

    The spelling follows the RStandardCallOperation convention: `core::name` is
    R_STANDARD_CALL_CORE_NAME and `std.module::name` is R_STANDARD_CALL_MODULE_NAME. A name
    outside the convention fails to compile, which keeps the inventory and the enum in step."""
    inventory = json.loads((root / INVENTORY_PATH).read_text(encoding="utf-8"))
    items = inventory.get("items")
    if not isinstance(items, list):
        raise ValueError("inventory items must be an array")
    names: list[str] = []
    for item in items:
        if not isinstance(item, dict) or item.get("facet") != "operation":
            continue
        if item.get(flag) is not True:
            continue
        implementation = item.get("implementation")
        if isinstance(implementation, dict) and implementation.get("kind") == "r_source":
            raise ValueError(f"R-source operation cannot be a registry entry: {item.get('id')}")
        name = item.get("id")
        if not isinstance(name, str) or SCHEMA_NAME.search(name) is not None:
            raise ValueError(f"{description} operation must be a concrete public name: {name}")
        components = name.split("::")
        if len(components) == 2 and components[0] == "core":
            names.append(f"R_STANDARD_CALL_CORE_{components[1].upper()}")
        elif len(components) == 2 and components[0].startswith("std."):
            names.append(f"R_STANDARD_CALL_{components[0][4:].upper()}_{components[1].upper()}")
        else:
            raise ValueError(f"unsupported public operation name: {name}")
    names.sort()
    if not names or len(set(names)) != len(names):
        raise ValueError(f"{description} operation table is empty or contains duplicates")
    return names


def render_scoped(names: list[str]) -> str:
    lines = [
        "/* Generated by tools/generate_standard_operation_registry.py. */",
        "static const RStandardCallOperation r_standard_scoped_operations[] = {",
    ]
    lines.extend(f"    {name}," for name in names)
    lines.extend(("};", ""))
    return "\n".join(lines)


def load_discardable_operations(root: Path) -> list[str]:
    """Enumerator names of the compiler-recognized operations with discardable_result (R-LIB-0026).

    The spelling follows the RStandardCallOperation convention: `core::name` is
    R_STANDARD_CALL_CORE_NAME and `std.module::name` is R_STANDARD_CALL_MODULE_NAME. A name
    outside the convention fails to compile, which keeps the inventory and the enum in step."""
    inventory = json.loads((root / INVENTORY_PATH).read_text(encoding="utf-8"))
    items = inventory.get("items")
    if not isinstance(items, list):
        raise ValueError("inventory items must be an array")
    names: list[str] = []
    for item in items:
        if not isinstance(item, dict) or item.get("facet") != "operation":
            continue
        if item.get("discardable_result") is not True:
            continue
        implementation = item.get("implementation")
        if isinstance(implementation, dict) and implementation.get("kind") == "r_source":
            raise ValueError(f"R-source operation cannot be a registry entry: {item.get('id')}")
        name = item.get("id")
        if not isinstance(name, str) or SCHEMA_NAME.search(name) is not None:
            raise ValueError(f"discardable operation must be a concrete public name: {name}")
        components = name.split("::")
        if len(components) == 2 and components[0] == "core":
            names.append(f"R_STANDARD_CALL_CORE_{components[1].upper()}")
        elif len(components) == 2 and components[0].startswith("std."):
            names.append(f"R_STANDARD_CALL_{components[0][4:].upper()}_{components[1].upper()}")
        else:
            raise ValueError(f"unsupported public operation name: {name}")
    names.sort()
    if not names or len(set(names)) != len(names):
        raise ValueError("discardable operation table is empty or contains duplicates")
    return names


def render_discardable(names: list[str]) -> str:
    lines = [
        "/* Generated by tools/generate_standard_operation_registry.py. */",
        "static const RStandardCallOperation r_standard_discardable_operations[] = {",
    ]
    lines.extend(f"    {name}," for name in names)
    lines.extend(("};", ""))
    return "\n".join(lines)


def signature_parameters(signature: str) -> list[str]:
    """Top-level parameters of a source signature `name(parameters) -> result`."""
    start = signature.find("(")
    if start < 0:
        raise ValueError(f"signature lacks a parameter list: {signature}")
    depth = 0
    parameters: list[str] = []
    current: list[str] = []
    for character in signature[start + 1 :]:
        if character in "(<[":
            depth += 1
        elif character in ")>]":
            if depth == 0 and character == ")":
                break
            depth -= 1
        if character == "," and depth == 0:
            parameters.append("".join(current).strip())
            current = []
            continue
        current.append(character)
    else:
        raise ValueError(f"unterminated parameter list: {signature}")
    tail = "".join(current).strip()
    if tail:
        parameters.append(tail)
    return parameters


def load_deadline_operations(root: Path) -> list[tuple[str, str, int]]:
    """Operations whose last parameter is `o<std.time::instant> deadline` (R-SLIB-ASYNC-0008).

    The compiler lets a call omit that trailing argument, which then is o::none and leaves the
    operation the deadline of its task (Core R-STMT-0019)."""
    inventory = json.loads((root / INVENTORY_PATH).read_text(encoding="utf-8"))
    items = inventory.get("items")
    if not isinstance(items, list):
        raise ValueError("inventory items must be an array")
    records: list[tuple[str, str, int]] = []
    for item in items:
        if not isinstance(item, dict) or item.get("facet") != "operation":
            continue
        signature = item.get("source_signature")
        if not isinstance(signature, str) or DEADLINE_PARAMETER not in signature:
            continue
        parameters = signature_parameters(signature)
        if not parameters or parameters[-1] != DEADLINE_PARAMETER:
            raise ValueError(f"deadline parameter is not last: {item.get('id')}")
        components = str(item.get("id")).split("::")
        if len(components) != 2 or not components[0].startswith("std."):
            raise ValueError(f"unsupported deadline operation name: {item.get('id')}")
        records.append((components[0][4:], components[1], len(parameters)))
    records.sort()
    if not records or len(set(records)) != len(records):
        raise ValueError("deadline operation table is empty or contains duplicates")
    return records


def render_deadline(records: list[tuple[str, str, int]]) -> str:
    lines = [
        "/* Generated by tools/generate_standard_operation_registry.py. */",
        "static const RStandardDeadlineOperation r_standard_deadline_operations[] = {",
    ]
    lines.extend(f'    {{"{module}", "{operation}", {count}U}},' for module, operation, count in records)
    lines.extend(("};", ""))
    return "\n".join(lines)


def render(records: list[tuple[str, str, str, bool]]) -> str:
    lines = [
        "/* Generated by tools/generate_standard_operation_registry.py. */",
        "static const RStandardOperationRegistryEntry r_standard_operation_registry[] = {",
    ]
    for scope, module, operation, panics in records:
        flag = "true" if panics else "false"
        lines.append(f'    {{"{scope}", "{module}", "{operation}", {flag}}},')
    lines.extend(("};", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path("."))
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--verify", action="store_true")
    arguments = parser.parse_args()
    root = arguments.root.resolve()
    outputs = (
        (root / OUTPUT_PATH, render(load_records(root))),
        (root / DISCARDABLE_OUTPUT_PATH, render_discardable(load_discardable_operations(root))),
        (
            root / SCOPED_OUTPUT_PATH,
            render_scoped(load_flagged_operations(root, "scoped", "scoped")),
        ),
        (root / DEADLINE_OUTPUT_PATH, render_deadline(load_deadline_operations(root))),
    )
    try:
        stale = False
        for output, expected in outputs:
            if arguments.write:
                output.parent.mkdir(parents=True, exist_ok=True)
                output.write_text(expected, encoding="utf-8", newline="\n")
                continue
            if output.read_text(encoding="utf-8") != expected:
                print(f"stale generated file: {output}", file=sys.stderr)
                stale = True
        return 1 if stale else 0
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"standard operation registry generation failed: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
