#!/usr/bin/env python3
"""Validate the explicit standard-method catalogue and generate compiler bindings."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def generate(root: Path) -> str:
    inventory = json.loads((root / "library/generated/api_inventory/implementation_inventory.json").read_text())
    operations = {item["id"]: item for item in inventory["items"]}
    catalogue = json.loads((root / "library/standard_methods.json").read_text())
    assert catalogue["schema_version"] == 1
    for family in catalogue["overloads"]:
        if not family["sources"] or len(family["sources"]) != len(set(family["sources"])):
            raise ValueError(f"invalid overload family: {family['name']}")
        for source in family["sources"]:
            if source not in operations or operations[source]["facet"] != "operation":
                raise ValueError(f"unknown overload source: {source}")
    if inventory.get("source_aliases") != catalogue["overloads"]:
        raise ValueError("inventory source aliases differ from the standard call catalogue")

    lines = ["/* Generated by tools/generate_standard_methods.py. */",
             "static const RStandardMethodDescriptor r_standard_methods[] = {"]
    seen: set[tuple[str, str]] = set()
    for method in sorted(catalogue["methods"], key=lambda item: (item["owner"], item["name"])):
        identity = (method["owner"], method["name"])
        if identity in seen:
            raise ValueError(f"duplicate standard method: {identity}")
        seen.add(identity)
        operation = operations[method["source"]]
        if operation["module"] != method["module"]:
            raise ValueError(f"method source module mismatch: {identity}")
        if method["receiver"] not in {"shared", "exclusive", "value"}:
            raise ValueError(f"invalid receiver: {identity}")
        if not isinstance(method["argument_index"], int) or not 0 <= method["argument_index"] < 8:
            raise ValueError(f"invalid receiver argument index: {identity}")
        owner, name = identity
        fields = [owner, name, method["module"].removeprefix("std."), method["operation"]]
        signature = operation.get("source_signature", "")
        asynchronous = " -> task(" in signature or signature.startswith("async ")
        lines.append("    {" + ", ".join(json.dumps(field) for field in fields)
                     + f", R_SEMANTIC_RECEIVER_{method['receiver'].upper()}, "
                     + f"{method['argument_index']}U, {'true' if asynchronous else 'false'}" + "},")
    lines.extend(["};", "", "static const RStandardResultDescriptor r_standard_results[] = {"])
    for identity, operation in sorted(operations.items()):
        effect = operation.get("checked_effect") or {}
        result = (effect.get("invocation") or {}).get("value_type")
        if result and not result.startswith("task("):
            lines.append("    {" + json.dumps(identity) + ", " + json.dumps(result) + "},")
    lines.extend(["};", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    output = options.root / "compiler/semantic/standard_methods.generated.inc"
    text = generate(options.root)
    if options.check:
        if not output.is_file() or output.read_text() != text:
            raise SystemExit("standard method bindings are stale")
        print("standard method catalogue and compiler bindings are synchronized")
    else:
        output.write_text(text)


if __name__ == "__main__":
    main()
