#!/usr/bin/env python3
"""Generate exhaustive sync and async core integer-intrinsic coverage."""

from __future__ import annotations

import argparse
from pathlib import Path


INTEGER_TYPES = (
    "i8",
    "u8",
    "i16",
    "u16",
    "i32",
    "u32",
    "i64",
    "u64",
    "isize",
    "usize",
)

CHECKED_OPERATIONS = ("checked_add", "checked_sub", "checked_mul")
VALUE_OPERATIONS = (
    "wrapping_add",
    "wrapping_sub",
    "wrapping_mul",
    "saturating_add",
    "saturating_sub",
    "saturating_mul",
)


def render_fixture() -> str:
    lines = [
        "// Generated by tools/generate_core_integer_fixture.py.",
        "module test.codegen.core_integer_all;",
        "",
    ]
    for operation in CHECKED_OPERATIONS:
        for value_type in INTEGER_TYPES:
            lines.extend(
                (
                    f"o<{value_type}> {operation}_{value_type}(",
                    f"    {value_type} left, {value_type} right) {{",
                    f"    return core::{operation}_{value_type}(left, right);",
                    "}",
                    "",
                )
            )
    for operation in VALUE_OPERATIONS:
        for value_type in INTEGER_TYPES:
            lines.extend(
                (
                    f"{value_type} {operation}_{value_type}(",
                    f"    {value_type} left, {value_type} right) {{",
                    f"    return core::{operation}_{value_type}(left, right);",
                    "}",
                    "",
                )
            )
    for value_type in INTEGER_TYPES:
        lines.extend(
            (
                f"{value_type} minimum_{value_type}() {{ return core::min_{value_type}; }}",
                f"{value_type} maximum_{value_type}() {{ return core::max_{value_type}; }}",
                "",
            )
        )
    lines.append("async i32 exercise_async() {")
    for operation in CHECKED_OPERATIONS:
        for value_type in INTEGER_TYPES:
            result = f"result_{operation}_{value_type}"
            lines.extend(
                (
                    f"    o<{value_type}> {result} =",
                    f"        core::{operation}_{value_type}(1{value_type}, 1{value_type});",
                    f"    {result} as void;",
                )
            )
    for operation in VALUE_OPERATIONS:
        for value_type in INTEGER_TYPES:
            result = f"result_{operation}_{value_type}"
            lines.extend(
                (
                    f"    {value_type} {result} =",
                    f"        core::{operation}_{value_type}(1{value_type}, 1{value_type});",
                    f"    {result} as void;",
                )
            )
    lines.extend(("    return 0;", "}", "", "i32 main() {"))
    for index, value_type in enumerate(INTEGER_TYPES, start=1):
        lines.extend(
            (
                f"    if (core::wrapping_add_{value_type}(",
                f"            core::max_{value_type}, 1{value_type}) != core::min_{value_type}) {{",
                f"        return {index};",
                "    }",
            )
        )
    for index, value_type in enumerate(("u8", "u16", "u32", "u64", "usize"), start=11):
        lines.extend(
            (
                f"    if (core::min_{value_type} != 0{value_type}) {{",
                f"        return {index};",
                "    }",
            )
        )
    lines.extend(("    return 0;", "}", ""))
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    arguments = parser.parse_args()
    rendered = render_fixture()
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    if not arguments.output.exists() or arguments.output.read_text(encoding="utf-8") != rendered:
        arguments.output.write_text(rendered, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
